### ISSUE TITLE
IOS 17 screenshot efficiency is relatively slow

### ISSUE THREAD

**Issue by hyfand** [doronz88/pymobiledevice3#1002]
IOS 17 screenshots have a relatively slow efficiency, taking about 2 seconds to complete. May I ask what is the principle behind this screenshot

**Comment by doronz88** [comment]
They relies on the DVT, which adds more network layers we need to wrap for things to work.
Also, this question should be posted on the [discussions](https://github.com/doronz88/pymobiledevice3/issues/1002) instead
