### ISSUE TITLE
pmd3 creates a new "~" directory in the working path

### ISSUE THREAD

**Issue by prosch88** [doronz88/pymobiledevice3#1022]
**Test environment**
- Manjaro KDE, Manjaro XFCE, Windows 11
- any idevice

**Describe the bug**
On execution, a new directory "~" is created (e.g by calling "usbmux list". Sometimes it also contains a subdirectory named "pymobiledevice3"

**To Reproduce**
1. Update to latest version
2. execute a pmd3 command aside from "version"

**Expected behavior**
Don't create new directorys.

**Additional context**
Might be related to the "get_home_folder()" fix 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Just created a PR for that - Please verify

**Comment by doronz88** [comment]
You can retry now with latest release.

**Comment by prosch88** [comment]
It's solved 👍
