### ISSUE TITLE
[URGENT] LocationSimulator doesnt work on iOS 17 and upper

### ISSUE THREAD

**Issue by D3vMohab** [doronz88/pymobiledevice3#1029]
I wrote a code for the location simulator using the lockdown tunnel, it seems to be working only on iOS 16 and lower, iOS 17 is exclude (DOESNT WORK)

**Comment by doronz88** [comment]
The iOS 17 API uses a dvt channel instead as the README suggests
Also - this should be discussed in the "discussions" section

**Comment by D3vMohab** [comment]
Do you know a work around for LocationSimulator on iOS 17?

**Comment by doronz88** [comment]
Reade the README

**Comment by D3vMohab** [comment]
@doronz88 I read it, iOS 17 works for some features, LocationSimulator isnt one of them?!

**Comment by doronz88** [comment]
From README:
![image](https://github.com/doronz88/pymobiledevice3/assets/19665147/b6dcd487-ef8d-4b93-a939-6133a754f4ab)
