### ISSUE TITLE
Replace M2Crypto with pyOpenSSL

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#103]
M2Crypto doesn't support windows (the windows port is unmaintained and cannot be installed on newer systems).
I suggest using [pyOpenSSL](https://github.com/pyca/pyopenssl) instead.
It might be possible to use just [cryptography](https://github.com/pyca/cryptography) but I'm not sure.

**Comment by doronz88** [comment]
Actually the only piece of code that uses `M2Crypto` is optional for communicating with iOS<=12 and was copied from the original `pymobiledevice` project. Since I don't have an iOS 12 device (or below) I cannot test it.
It's also discussed in:
https://github.com/doronz88/pymobiledevice3/issues/44

**Comment by vToMy** [comment]
For reference, here's what we have:
https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/ca.py
and here's an alternative implementation:
https://github.com/YueChen-C/py-ios-device/blob/main/ios_device/util/ca.py

**Comment by doronz88** [comment]
Since I don't have an iOS 12 device to test it with I cannot copy the code and hope for the best. If you have one, then you are more then welcome to open us a PR after you have tested it and I'll be happy to merge it right away.

**Comment by doronz88** [comment]
If you are having trouble making a PR I can modify it myself on a seperate branch but I'll need you to help me test it. Please PM me (doron88@gmail.com) if you prefer this option.

**Comment by vToMy** [comment]
I'll open one when when I have some time for proper testing. I added the reference for documentation in case anyone else is up up for the task or has the same issue.

**Comment by doronz88** [comment]
#116

**Comment by vToMy** [comment]
@doronz88 Thanks! There's still some leftover M2Crypto in the readme though.

**Comment by doronz88** [comment]
Fixed that :).

Fortunately we got our hands on an iOS 8 device and got to test everything now works on all versions.
