### ISSUE TITLE
Unable to start webdriveragentrunner on iOS 17.5.1

### ISSUE THREAD

**Issue by mega6453** [doronz88/pymobiledevice3#1037]
I've used the below command to start the webdriveragentrunner, but it's not starting. Am I doing something wrong or is there any issue?
Pymobiledevice3 version : 4.6.0
iOS version : 17.5.1
WDA version : 8.6.0

Mounted disk image using : pymobiledevice3 mounter auto-mount
Ran this command in separate cmd window(running) : pymobiledevice3 remote tunneld

In another window, below command:

C:\Users\mc>pymobiledevice3 developer dvt xcuitest --rsd fdd0:3fbb:fe83::1 59014 com.facebook.WebDriverAgentRunner.xctrunner
C:\Users\mc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
2024-05-28 18:19:27 PC-VQ4 pymobiledevice3.__main__[5632] WARNING Trying again over tunneld since it is a developer command
2024-05-28 18:19:27 PC-VQ4 pymobiledevice3.__main__[5632] ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
          https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

- Apple removed this service

- A bug. Please file a bug report:
  https://github.com/doronz88/pymobiledevice3/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

---------------------------------
This command launches the wda --> pymobiledevice3 developer dvt launch com.facebook.WebDriverAgentRunner.xctrunner

**Comment by mega6453** [comment]
@doronz88

**Comment by doronz88** [comment]
1. There's no point in tagging me. I'll get to the issue eventually.
2. Tunneld is a completely alternate way to `--rsd` option. Either use one or the other
3. pymobile does not support xcuitest for 17 - there is already an open issue
