### ISSUE TITLE
Implement unpair command

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#104]
Same as in [libimobiledevice ](https://github.com/libimobiledevice/libimobiledevice/blob/25059d4c7d75e03aab516af2929d7c6e6d4c17de/tools/idevicepair.c)

**Comment by doronz88** [comment]
We'll be implemented very soon, as part of a major release:
https://github.com/doronz88/pymobiledevice3/tree/feature/idevicerestore
