### ISSUE TITLE
A tunnel created with usbmux in the window environment cannot be used to start an application

### ISSUE THREAD

**Issue by cyrilchans** [doronz88/pymobiledevice3#1044]
**Test environment**
   iphone 12
   ios17.5.1
**Describe the bug**
A tunnel created with usbmux in the window environment cannot be used to start an application，An error occurs when executing related commands。

Original mode：
   
![1](https://github.com/doronz88/pymobiledevice3/assets/74752545/6f0433c0-b408-4bee-b640-79e9368a982c)

In usbmux mode：
![2](https://github.com/doronz88/pymobiledevice3/assets/74752545/95505717-e21b-4076-91d8-1d80c64e06d5)

**Comment by doronz88** [comment]
In order to start the tunnel with usbmux:
```shell
# NOT over remote which IS NOT usbmux, but instead over remoted
pymobiledevice3 lockdown start-tunnel
```

Also, as I cannot reproduce your issue, feel free to debug it further and submit a PR of a working fix
