### ISSUE TITLE
"Device Not Connected" in Windows

### ISSUE THREAD

**Issue by ruokbb** [doronz88/pymobiledevice3#1046]
**Test environment**
- Host OS version - win10
- Target device model and iOS version -ios17.3

**Describe the bug**
After changing the bonjour_timeout to 60 in win_util.py and executing `python -m pymobiledevice3 remote start-tunnel`, the error message is: "Device is not connected".

**Expected behavior**
Obtain the RSD address of iOS 17 on Windows.

**Additional context**
when executing `python -m pymobiledevice3 usbmux list`, the output is as follows:
```
[
    {
        "BuildVersion": "21D50",
        "ConnectionType": "USB",
        "DeviceClass": "iPhone",
        "DeviceName": "BD's iPhone",
        "Identifier": "00008130-001A75222EE0001C",
        "ProductType": "iPhone16,2",
        "ProductVersion": "17.3",
        "UniqueDeviceID": "00008130-001A75222EE0001C"
    }
]
```
Executing `python -m pymobiledevice3 remote browse` returns the following result:
```
{
    "usb": [],
    "wifi": []
}
```

Even after trying different Windows computers and devices with lower iOS versions, `python -m pymobiledevice3 remote browse` still cannot discover devices.
However, when executing `python -m pymobiledevice3 remote tunneld`, everything is correct.
```
INFO:     Started server process [17712]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151/ (Press CTRL+C to quit)
INFO:     [127.0.0.1:64773](http://127.0.0.1:64773/) - "GET /hello HTTP/1.1" 200 OK
INFO:     [127.0.0.1:64774](http://127.0.0.1:64774/) - "GET /hello HTTP/1.1" 200 OK
INFO:     [127.0.0.1:64787](http://127.0.0.1:64787/) - "GET /hello HTTP/1.1" 200 OK
```
At the end of #569, I saw someone successfully create a tunnel to obtain the RSD address for iOS 17.0, but I don't know why my device can't be discovered by the Bonjour service.
On the other hand, I have been studying iOS testing recently. In the introduction to a certain testing tool, it was mentioned that during wireless testing, Windows often fails to receive Bonjour broadcasts. Regardless of whether it is an ordinary local area network or a proxy local area network, you need to enter the IP address of the iOS device. Is it helpful to discover the device through the IP address within the same local area network for this issue?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This is the expected bahavior.

As the documentation states. For tunnel creation on windows you'll need either a special driver or ios version > 17.4.

Otherwise, will only work on Mac

**Comment by ruokbb** [comment]
> This is the expected bahavior.
> 
> As the documentation states. For tunnel creation on windows you'll need either a special driver or ios version > 17.4.
> 
> Otherwise, will only work on Mac

The term "special driver" might refer to something similar to the driver provided by WeTest? I noticed there was a Windows branch that included a  script `pywintunx_pmd3.install_wetest_driver()` to install the driver. The master branch has merged with it before, but I'm not sure why there is no related content now.

**Comment by doronz88** [comment]
Too many people were asking for its removal since it had too many bugs and also was not open-source, making it not trustwortyh enough
