### ISSUE TITLE
full backup info error

### ISSUE THREAD

**Issue by xuemingyang** [doronz88/pymobiledevice3#1052]
**Test environment**
- Host OS version.
- Target device model and iOS version.

**Describe the bug**
when i use the command [ pymobiledevice3 backup2 backup --full "D:\backup\b1"],
but, the backup info shows that [fullBackup=0], why??
![image](https://github.com/doronz88/pymobiledevice3/assets/15265376/453eaaf3-dee5-46a2-a8cd-03487014ace7)

**Logs**
PS C:\WINDOWS\system32> pymobiledevice3 backup2 info "D:\backup\b1"
<MBStatus: version=3.3, date=2024-06-05 18:32:09 +0000, backupState=new, snapshotState=finished, fullBackup=0>
<MBDriveProperties: version=10.0, systemDomainsVersion=24.0, requiredProductVersion=(null), date="2024-06-05 18:31:59 +0000", encrypted=0, passcodeSet=0, lockdownKeys={com.apple.MobileDeviceCrashCopy: {}, com.apple.TerminalFlashr: {}, com.apple.mobile.data_sync: {Bookmarks: {AccountNames: ["iCloud"], Sources: ["iCloud"]}, Contacts: {AccountNames: ["iCloud"], Sources: ["iCloud"]}, Calendars: {AccountNames: ["iCloud"], Sources: ["iCloud"]}, Notes: {AccountNames: ["iCloud"], Sources: ["iCloud"]}}, com.apple.Accessibility: {MonoAudioEnabledByiTunes: 0, VoiceOverTouchEnabledByiTunes: 0, ClosedCaptioningEnabledByiTunes: 0, SpeakAutoCorrectionsEnabledByiTunes: 0, InvertDisplayEnabledByiTunes: 0, ZoomTouchEnabledByiTunes: 0}, ProductVersion: "16.7.2", ProductType: "iPhone10,3", BuildVersion: "20H115", com.apple.mobile.iTunes.accessories: {}, com.apple.mobile.wireless_lockdown: {EnableWifiConnections: 1}, UniqueDeviceID: "xxxxxx", SerialNumber: "xxxx", DeviceName: "1"}>

**Comment by doronz88** [comment]
Well, this is what the device reports, so looks like an error on Apple's side

**Comment by xuemingyang** [comment]
iPhone 6sp, iPhoneX
