### ISSUE TITLE
Unable to access DVT via device UDID

### ISSUE THREAD

**Issue by lnguyen234** [doronz88/pymobiledevice3#1064]
**Test environment**
- Host OS version: MacOS Ventura
- Target device model and iOS version: iPadOS 17.4
- `pymobiledevice3` 4.9.5

**Describe the bug**
Tunnel is already started via `usbmuxd` by: ```pymobiledevice3 lockdown start-tunnel```. However, I could not call any DVT functions, eg ```pymobiledevice3 developer dvt launch com.apple.mobilesafari --tunnel  <device_udid>```.  The command should run fine if I replace `--tunnel UDID` with the `--rsd` string.

**Expected behavior**
Safari app should be launched

**Logs**
pymobiledevice3.__main__[85627] ERROR Unable to connect to Tunneld. You can start one using:
```sudo python3 -m pymobiledevice3 remote tunneld```

**Comment by doronz88** [comment]
You are confusing two completely seperate ways to use tunnels.
Simplest is to execute on one shell:
```shell
sudo pymobiledevice3 remote tunneld
```
Then on the other, whatever command with no special options. For example:
```shell
pymobiledevice3 developer dvt launch com.apple.mobilesafari
```
