### ISSUE TITLE
WARNING:pymobiledevice3.tunneld:[mobdev2-#UDID+IP#] failed to start CoreDeviceTunnelProxy - skipping 

### ISSUE THREAD

**Issue by penter666** [doronz88/pymobiledevice3#1071]
![chrome_1bKJXez6Cg](https://github.com/doronz88/pymobiledevice3/assets/55096308/bc0c23b0-571d-4556-8c17-abc775cbcb59)

Whats the cause of this, im trying to run sidejit

**Comment by boooody03** [comment]
Did you find a solution to this problem

**Comment by thatkid662** [comment]
+1 for this, experiencing on Debian Linux
Could OP share the solution?

**Comment by doronz88** [comment]
This is the expected behaviour on iOS<17.4

**Comment by boooody03** [comment]
> This is the expected behaviour on iOS<17.4

I am on 17.0, is there a solution ?
I don't want to upgrade as I'm waiting for trollstore but I would still like to access JIT if possible

**Comment by doronz88** [comment]
For windows there is no public solution
This requires special drivers

**Comment by boooody03** [comment]
> For windows there is no public solution This requires special drivers

What about macos ?

**Comment by doronz88** [comment]
Should work out of the box

**Comment by boooody03** [comment]
> Should work out of the box

Unfortunately I'm facing the same issue on macos
I'm using macos sequoia 18.1 beta and the same issue occurs

**Comment by boooody03** [comment]
sorry if I'm bothering you and thank you for responding

**Comment by doronz88** [comment]
Please submit a new issue detailing everything

**Comment by boooody03** [comment]
OK, Will do
Thank you so much
