### ISSUE TITLE
Mounting iOS developer image results in error: Please make sure your user has the necessary permissions

### ISSUE THREAD

**Issue by morellexf13** [doronz88/pymobiledevice3#1074]
**Test environment**
-  MacOS 13.6.7.
- iPhone 8 iOS 16.7.8

**Describe the bug**
When I try to mount iOS developer image I get the following error: 

`DeveloperDiskImage could not be saved to Xcode default path (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/16.7). Please make sure your user has the necessary permissions`

**To Reproduce**
1. Try to mount developer image
2. See error

**Comment by doronz88** [comment]
Did you try to set the permissions on the path pointed out by the error?

**Comment by morellexf13** [comment]
> Did you try to set the permissions on the path pointed out by the error?
<img src="https://github.com/doronz88/pymobiledevice3/assets/73654994/7c408223-625b-4745-b70e-944e3c0cb1e8" width="200px"/>

oh, apparently when Xcode is intalled using App Store you don't have [your user] read & write permissions. You have a "system" user!

**Comment by doronz88** [comment]
Simply `sudo chmod`
