### ISSUE TITLE
How activate developer mode in first iphone conection (ios17 & ios16)?

### ISSUE THREAD

**Issue by Vasa211** [doronz88/pymobiledevice3#1075]
How activate developer mode in first iphone conection (ios17 & ios16)?
I write python code for working with iphone (its not in terminal commads, its python code), how check if developer mode active and if not then add dev mode to iphone?

**Comment by doronz88** [comment]
Read https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/amfi.py cli implementation

**Comment by Vasa211** [comment]
> Read https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/amfi.py cli implementation

Thx, its work
