### ISSUE TITLE
How to build xpc File Transfer

### ISSUE THREAD

**Issue by Karl0226** [doronz88/pymobiledevice3#1097]

**Comment by doronz88** [comment]
what?

**Comment by Karl0226** [comment]
> what?

XpcMessageType.FILE_TRANSFER

**Comment by doronz88** [comment]
This is used when downloading the DSC
What else do you require?

**Comment by Karl0226** [comment]
> This is used when downloading the DSC What else do you require?

OK thanks
I rebuilt xcuitest and received the message "Unable to invoke message sent to invalid channel" when launching xcuitest under iOS 17. Have you ever encountered this message?

**Comment by doronz88** [comment]
No. I'm not a user of xcuitest myself, but please create a seperate issue for that if you're encountering
