### ISSUE TITLE
How to Start iProxy?

### ISSUE THREAD

**Issue by DRCRecoveryData** [doronz88/pymobiledevice3#1100]
Hi,

From libimobiledevice.1.2.1-r1122-win-x64 have iProxy.exe

the command is:```.\iproxy.exe 22 44```

And i wanna connect by ```pymobiledevice3``  method so how command from ```pymobiledevice3`` is?

**Comment by doronz88** [comment]
```shell
# you can add `-d` option for it to be in background
pymobiledevice3 usbmux forward 22 44
```
