### ISSUE TITLE
How to install pwndfu mode when ios devices in dfu mode on Windows OS

### ISSUE THREAD

**Issue by DRCRecoveryData** [doronz88/pymobiledevice3#1107]
Hi,

I have boot ramdisk with irecovery.exe:

‘‘‘
irecovery -f iBSS.img4
sleep 1
irecovery -f iBSS.img4
sleep 1
irecovery -f iBEC.img4
sleep 1
irecovery -c go
sleep 1
irecovery -f ramdisk
sleep 1
irecovery -c ramdisk
sleep 1
irecovery -f devicetree.img4
sleep 1
irecovery -c devicetree
sleep 1
irecovery -f trustcache.img4
sleep 1
irecovery -c firmware
sleep 1
irecovery -f kernelcache.img4
sleep 1
irecovery -c bootx
‘‘‘

But before it i want to install libusbk as driver for apple DFU like zadig do go to PWNDFU mode

How install that libusbk driver on windows automate with python and the pymobiledevice3 library instead of irecovery.exe?

**Comment by doronz88** [comment]
There is no CLI interface for that, though you are welcome to PR one.
You can do so from python:

```python
import time
from pymobiledevice3.irecv import IRecv

irecv = IRecv()
irecv.send_buffer(open('iBSS.img4', 'rb').read())
time.sleep(1)
# ...
irecv.send_command('bootx')
```

**Comment by doronz88** [comment]
Feel free to reopen if the issue is not resolved
