### ISSUE TITLE
我就想问一下这个是谁写的

### ISSUE THREAD

**Issue by lezhi12** [doronz88/pymobiledevice3#1108]
请原谅我的才疏学浅和没见过世面，我只是想问一下，Understanding iDevice protocol layers.MD 是谁写的
- 原理为啥了解的这么清楚
-英语语法为啥毫无 chnglish 的感觉
-表达的也是如此流畅感觉完全就是官方范。
我非常好奇，求告知，多谢了，即便是嘲笑我没见过世面，也请告诉我一下是怎么做的在嘲笑我。

**Comment by doronz88** [comment]
Please rewrite the issue in english, as I think google-translate doesn't do a good job here

**Comment by alkydog** [comment]
he want to know who write this document

**Comment by alkydog** [comment]
> Please rewrite the issue in english, as I think google-translate doesn't do a good job here

he want to know who write this document

**Comment by doronz88** [comment]
I was the author

**Comment by lezhi12** [comment]
> I was the author

thanks  for  your nice job!
it  helps  me a lot !
