### ISSUE TITLE
get_device_list is no longer defined in the newest update!

### ISSUE THREAD

**Issue by D3vMohab** [doronz88/pymobiledevice3#1110]
Traceback (most recent call last):
  File "/Users/mohabhisham/Desktop/iSpoofer_PC/new/tmp/5.py", line 8, in <module>
    print(get_device_list())
          ^^^^^^^^^^^^^^^
NameError: name 'get_device_list' is not defined

**Comment by doronz88** [comment]
Please create a clear and concise issue
I have no idea what are you trying to do

**Comment by D3vMohab** [comment]
I am trying to start a tunnel in a py file, can you help?
