### ISSUE TITLE
HouseArrestService  BUG

### ISSUE THREAD

**Issue by huan1936** [doronz88/pymobiledevice3#1115]
**Test environment**
- Host OS version.  Windows 10
- Target device model and iOS version. 13 mini 15.0

**Describe the bug**
HouseArrestService, when initializing, calls the send_command function by default. When the application is unreadable, it triggers
pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed.
However, the connection is not closed, which will cause the HouseArrestService to be prohibited from creating further connections after approximately 300~600 failures due to too many connections, necessitating a device restart.

**To Reproduce**
1. Starting the HouseArrestService for applications that do not have UIFileSharingEnabled enabled.
2. 300~600 consecutive times.
3. Execute again

**Expected behavior**
Even if an error occurs, the service should be closed in time

**Logs**

```
Traceback (most recent call last):
  File "ttt2.py", line 51, in <module>
    test()
  File "ttt2.py", line 37, in test
    service = HouseArrestService(lockdown=dev.lockdown,
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\house_arrest.py", line 26, in __init__
    self.send_command(bundle_id, cmd)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\house_arrest.py", line 32, in send_command
    raise PyMobileDevice3Exception(error)
pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed
```

**Connection forbidden Error log**
```
Traceback (most recent call last):
  File "D:\pyCode\other\ttt2.py", line 50, in <module>
    test()
  File "D:\pyCode\other\ttt2.py", line 37, in test
    service = HouseArrestService(lockdown=dev.lockdown,
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\house_arrest.py", line 18, in __init__
    super().__init__(lockdown, self.SERVICE_NAME)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\afc.py", line 221, in __init__
    super().__init__(lockdown, service_name)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\services\lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\lockdown.py", line 67, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\lockdown.py", line 499, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\lockdown.py", line 489, in get_service_connection_attributes
    response = self._request('StartService', options)
  File "D:\pyCode\other\venv\lib\site-packages\pymobiledevice3\lockdown.py", line 577, in _request
    raise exception_errors.get(error, LockdownError)(error, self.identifier)
pymobiledevice3.exceptions.MissingValueError: MissingValue
```

**Additional context**
```
def test():
    service = HouseArrestService(lockdown=dev.lockdown,
                                 bundle_id='com.tencent.mqq',
                                 documents_only=True)

    service.exists('/Documents')


pool = ThreadPoolExecutor(20)
for _ in range(500):
    pool.submit(test)

pool.shutdown()
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Doesn't using it in a context-manager solve all? Sounds like you forgot to close the resource

**Comment by huan1936** [comment]
[Look at this](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/house_arrest.py#L26)
It is an error in the `__init__ `function, Function  `__enter__` has not yet been run.
context-manager won't work

**Comment by huan1936** [comment]
After simplification

```
class Test:

    def __init__(self):
        print("Test init")
        raise Exception("Test init")

    def __enter__(self):
        print("Test enter")
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        print("Test exit")
        return True


if __name__ == '__main__':
    with Test() as t:
        print("Test with")

```

**Comment by huan1936** [comment]
> Doesn't using it in a context-manager solve all? Sounds like you forgot to close the resource

So what I'm talking about is that when the UIFileSharingEnabled is not enabled

**Comment by doronz88** [comment]
I'm sorry but I'm failing to understand your claim. Did you refactor your code to use a context-manager or did you not? If you did not, the service socket will remain open which could explain your bug.

I don't understand what other behavior you would expect

**Comment by huan1936** [comment]
UIFileSharingEnabled  is not enabled 
So when executing send_command, an error will occur, but the service is already connected at this time, and the service is not closed after the error

**Comment by doronz88** [comment]
Oh, so you mean the socket remains open till python's GC closes it because the object cannot be created in the first place?

**Comment by huan1936** [comment]
···
	def __init__(self, lockdown: LockdownServiceProvider, bundle_id: str, documents_only: bool = False):
        if isinstance(lockdown, LockdownClient):
            super().__init__(lockdown, self.SERVICE_NAME)
        else:
            super().__init__(lockdown, self.RSD_SERVICE_NAME)
        if documents_only:
            cmd = VEND_DOCUMENTS
        else:
            cmd = VEND_CONTAINER
        self.documents_only = documents_only
        self.send_command(bundle_id, cmd)  # Error location  Here self.service is already connected
···

**Comment by doronz88** [comment]
You could simply answer my question.
Anyhow, feel free to submit a PR to fix that

**Comment by huan1936** [comment]
Python will recycle but Apple has a bug that will prohibit connections if too many services are connected

**Comment by doronz88** [comment]
Sounds like a simple `try... finally...` fix that

**Comment by huan1936** [comment]
yes

**Comment by huan1936** [comment]
[ limited number of connections.](https://github.com/libimobiledevice/libimobiledevice/issues/680)
Therefore, you must implement `try... finally...` in `__init__`, otherwise you cannot use context-manager

**Comment by huan1936** [comment]
Or remove `self.send_command(bundle_id, cmd)` in `__init__`

**Comment by doronz88** [comment]
I prefer the `try finally` since otherwise the service practically will be of no use and this service object has no meaning

**Comment by huan1936** [comment]
Yes, so please fix it.
I have currently added a try-finally block after inheriting.
Do not forget to add a check to see if the self.service attribute exists.
In special cases, self.service may not be present.

**Comment by huan1936** [comment]
You can't write like this
This will cause it to close immediately after initialization.

**Comment by huan1936** [comment]
He should be like this

![image](https://github.com/user-attachments/assets/b2d43009-e708-4ac0-8592-f4d9d05cd3b5)

**Comment by huan1936** [comment]
And why not use __del__ to ensure that it is closed when recycled?

**Comment by doronz88** [comment]
Overriding`__del__` is not a good practice. I'm failing to see the problem you are pointing at. If you have a reproduceable issue, please explain.

**Comment by huan1936** [comment]
```
with HouseArrestService(lockdown=dev.lockdown,
                             bundle_id='com.tencent.mqq',
                             documents_only=True) as service:
    print(service.exists('/Documents'))  # Expected: True  # Actual: [WinError 10038] 
```

Because the service has been shut down.
So `service.exists('/Documents')` cannot be executed

**Comment by huan1936** [comment]
```
    def __init__(self, lockdown: LockdownServiceProvider, bundle_id: str, documents_only: bool = False):
        if isinstance(lockdown, LockdownClient):
            super().__init__(lockdown, self.SERVICE_NAME)
        else:
            super().__init__(lockdown, self.RSD_SERVICE_NAME)
        if documents_only:
            cmd = VEND_DOCUMENTS
        else:
            cmd = VEND_CONTAINER
        self.documents_only = documents_only
        try:
            self.send_command(bundle_id, cmd)
        finally:
            self.close()  # close() is called even if no exception occurs.
```

**Comment by huan1936** [comment]
> Overriding`__del__` is not a good practice. I'm failing to see the problem you are pointing at. If you have a reproduceable issue, please explain.

`__del__`is not a good practice.   use weakref.finalize ? for example
```
    def __init__(...):
         self._finalizer = weakref.finalize(self, self.close)


    def close(self):
        self._finalizer()
```

**Comment by huan1936** [comment]
> Overriding`__del__` is not a good practice. I'm failing to see the problem you are pointing at. If you have a reproduceable issue, please explain.覆盖 `__del__` 不是一个好的做法。我没有看到你指出的问题。如果您有可重现的问题，请解释。

So what about this?
```
    def __init__(...):
         self._finalizer = weakref.finalize(self, self.service.close)


    def close(self):
        self._finalizer()
```
