### ISSUE TITLE
DVT Applist not showing all apps installed

### ISSUE THREAD

**Issue by gino0210** [doronz88/pymobiledevice3#1138]
**Test environment**
- ios 17.4.1

**Describe the bug**
Certain apps are not registering on the app list while under Pymobiledevice3 developer dvt applist 
but will show up under pymobiledevice3 apps list

this is causing en error when trying to use sidejitserver saying that the certain app cannot be found.

if anyone knows what to change\do i would highly appreciate it.

**Comment by doronz88** [comment]
That's not a bug - that's just what the device replies. Sounds like `sidejitserver` should use the correct API instead
