### ISSUE TITLE
Error: No such command 'remote'.

### ISSUE THREAD

**Issue by wangyu0303** [doronz88/pymobiledevice3#1159]
I ran “python3 -m pymobiledevice3 remote pair”
 and got this error Usage: 
python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...
Try 'python -m pymobiledevice3 --help' for help.

Error: No such command 'remote'.
Translate into English

then，i input this“python -m pymobiledevice3 --help”，There is no remote here：
Usage: python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  afc              FileSystem utils
  apps             application options
  backup2          backup utils
  crash            crash report options
  developer        developer options.
  diagnostics      diagnostics options
  list-devices     list connected devices
  lockdown         lockdown options
  mounter          mounter options
  notification     notification options
  pcap             sniff device traffic
  power-assertion  Create a power assertion (wraps...
  processes        processes cli
  profile          profile options
  provision        privision options
  restore          restore options
  springboard      springboard options
  syslog           syslog options

Hope to get help from everyone！thank you

**Comment by doronz88** [comment]
Please make sure you are using the latets version (since by your post it isn't)

**Comment by wangyu0303** [comment]
> Please make sure you are using the latets version (since by your post it isn't)

Thank you for your reply. I followed the steps in the readme to install it. This is my version：
pymobiledevice3       1.9.11
Looking forward to your reply，thank you.

**Comment by wangyu0303** [comment]
Thank you for your suggestion. After I try to update, I can support remote.

**Comment by wangyu0303** [comment]
> Please make sure you are using the latets version (since by your post it isn't)

Thank you for your suggestion. After I try to update, I can support remote.
