### ISSUE TITLE
cli <apps list> result can't json

### ISSUE THREAD

**Issue by e790a8** [doronz88/pymobiledevice3#1161]
**Test environment**
Windows10

**Describe the bug**
result last have '\x1b[0m'

```python
result = subprocess.run('pymobiledevice3 apps list --udid 00008110001E49CC0239401E', shell=True, capture_output=True, encoding='utf-8')
result.stdout[:20]
# '{\n    "com.apple.AAU'
apps_list = json.loads(result.stdout)
'''
Traceback (most recent call last):
  File "D:\App\JetBrains\Python\ui-app-client\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-51-455a49a2b318>", line 1, in <module>
    apps_list = json.loads(result.stdout)
  File "D:\Users\yongkunhuang\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Users\yongkunhuang\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 40466 column 1 (char 1766759)
'''
result.stdout[-20:]
# '      ]\n    }\n}\n\x1b[0m'
```

**Debug**
It is normal to exit immediately after output
![image](https://github.com/user-attachments/assets/80f2c10c-5ddd-455f-bb7e-4e3d440c56e9)
```python
result.stdout[-20:]
#'"\n        ]\n    }\n}\n'
```

**Comment by e790a8** [comment]
Python 3.9.13

**Comment by doronz88** [comment]
Since you are running the process from a TTY process pymobile cannot detect it is not desired to colorize the output so you need to specify it explicitly with the `--no-color` option

**Comment by e790a8** [comment]
invalid
![image](https://github.com/user-attachments/assets/19696746-1730-4dd0-9c03-1b61cdcb2056)

**Comment by doronz88** [comment]
What version of the package is it?

**Comment by doronz88** [comment]
On latest version your example is non-reproducable
Even without the `--no-color` option

**Comment by e790a8** [comment]
![image](https://github.com/user-attachments/assets/30e5ce58-f75f-4b5a-a5c3-13069cbfc1f4)

**Comment by doronz88** [comment]
![image](https://github.com/user-attachments/assets/acf57d03-3c23-4942-8a84-1f20b3bdee0e)

**Comment by doronz88** [comment]
Sounds like something wrong with your code

**Comment by e790a8** [comment]
Thank you for your answer.

I don't know why
But I dealt with it 
![image](https://github.com/user-attachments/assets/0055d5b9-7996-4872-9cbb-b39d239b4341)

**Comment by doronz88** [comment]
Since your using python code to interact with it, the better option in general would be using pymobile's API directly instead of invoking it as shell commands

**Comment by e790a8** [comment]
Okay, I'll try
