### ISSUE TITLE
capture home screen and lock screen as soon as the iOS device is connected. 

### ISSUE THREAD

**Issue by Lautarob1** [doronz88/pymobiledevice3#1168]
**Is your feature request related to a problem? Please describe.**
It would be useful, to grab the homescreen.png of an iOS device as soon as it get connected

**Describe the solution you'd like**
There are some Apps that as soon as the iOS device is connected, it grabbed both the home screen and the lock screen. (Although it may be similar to take a screenshot, it is not, is more like to extract the deviceID or info)

**Describe alternatives you've considered**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
pymobiledevice3 is used to interact with a connected iphone. If you wish to wait for the connection event, simply check for it

**Comment by Lautarob1** [comment]
Sorry, perhaps I did not ask the question properly. It is not that I want or need to wait for the connection event. 
I was trying to ask a very specific question: I have seen some apps that as soon as they get connected to the iOS device, they grab the home screen (and also lock screen). Is that possible within pymobiledevice3 framework?

**Comment by doronz88** [comment]
You probably mean this?

```shell
pymobiledevice3 springboard wallpaper-preview-image homescreen /tmp/homescreen.png -r
pymobiledevice3 springboard wallpaper-preview-image lockscreen /tmp/lockscreen.png -r

**Comment by Lautarob1** [comment]
Yes, something like that is what I want. However, the command "wallpaper-preview-image" is not recognized:
Error: No such command 'wallpaper-preview-image'.

while checking the help for springboard (pymobiledevice3 springboard -h) it turns out that the closest command is "wallpaper" (only) and it partially grabs an existing homescreen on the phone, but NOT the current one, which is coming from an album seated on the device. However, one of the apps I referred, is able to capture de actual one and also changes it when varies. So there must be a way to capture this images as their as seen on the device.

None of the options available in walpaper command seems to address specifically the images i'm referring to:

Usage: pymobiledevice3 springboard wallpaper [OPTIONS] OUT

  get wallpapaer (typo in the original)

Options:
  --rsd <TEXT INTEGER>...  RSD hostname and port number NOTE: This argument is
                           mutually exclusive with  arguments:
                           [rsd_service_provider_using_tunneld].
  --tunnel TEXT            Either an empty string to force tunneld device
                           selection, or a UDID of a tunneld discovered device
                           NOTE: This argument is mutually exclusive with
                           arguments: [rsd_service_provider_manually].
  --usbmux TEXT            usbmuxd listener address (in the form of either
                           /path/to/unix/socket OR HOST:PORT
  --udid TEXT              Device unique identifier. You may pass
                           PYMOBILEDEVICE3_UDID environment variable to pass
                           this option as well
  -v, --verbose
  -v, --verbose
  --color / --no-color     colorize output
  -h, --help               Show this message and exit.

**Comment by doronz88** [comment]
Then you are using an old version of pmd3. Update it

**Comment by Lautarob1** [comment]
After update pymobiledevice to 4.13 it worked!! Thank you so much!
