### ISSUE TITLE
Cannot afc shell rm lock file produced by realm databases

### ISSUE THREAD

**Issue by ViRb3** [doronz88/pymobiledevice3#1195]
**Test environment**
- Host OS version: macOS 14.6.1
- Target device model and iOS version: iPhone 15 Pro, iOS 17.6.1

**Describe the bug**
I'm trying to remove a folder from an app's Documents folder using afc. It works for normal files, but for `lock.fifo` files created as part of realm databases, the deletion hangs forever and never succeeds. Example structure:

```
example.realm
example.realm.lock
example.realm.management
├── access_control.control.mx
├── access_control.new_commit.cv
├── access_control.pick_writer.cv
├── access_control.versions.mx
├── access_control.write.mx
└── lock.fifo
example.realm.note
```

**To Reproduce**
```
pymobiledevice3 apps afc com.example.app
cd Documents
rm example.realm.management/lock.fifo
```

**Expected behavior**
Deletion succeeds

**Logs**
N/A, it just hangs

**Additional context**
N/A

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by ViRb3** [comment]
For what is worth, iMazing also errors on the same file, so this may be an issue with Apple's implementation, but I don't know enough to tell.

**Comment by doronz88** [comment]
This does sounds like an internal device error. You could try to view the syslog for any relevant hints in debugging this:

```shell
pymobiledevice3 syslog live -mi lock.fifo
```

**Comment by prosch88** [comment]
I have this errors too on realm.db related files. It's not really pmd3 related. You get the same errors with libimobiledevice. If you try to pull these you get "lock.fifo isn't a file". ... Which is quite correct, as fifo "files" don't have content on the filesystem.
