### ISSUE TITLE
"file" command in afc shell appears to run on host instead of inside device

### ISSUE THREAD

**Issue by ViRb3** [doronz88/pymobiledevice3#1196]
**Test environment**
- Host OS version: macOS 14.6.1
- Target device model and iOS version: iPhone 15 Pro, iOS 17.6.1

**Describe the bug**
I'm trying to run the `file` command to see information about a file on my device. However, I always get an error that the file does not exist. If I use tab auto-complete, I get suggestions for files in the current working directory of my host, not my iDevice. Surely enough, it also executes file if I specify a file on my host.

**To Reproduce**
```
pymobiledevice3 apps afc com.example.app
file example.txt
```

**Expected behavior**
Result from device is returned

**Logs**
Result from host is returned instead

**Additional context**
N/A

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Yeah that's because the provided shell isn't a real shell but a mock instead. pmd defines aliases to make it work with connected device, but when u run any other command that isn't mapped as an alias, it runs on your local machine instead. If you want, you can add an implementaion for `file` which reads the file from the device, and then executes the `file` command`

**Comment by ViRb3** [comment]
Ah, I figured that's what happens, but I noticed that `file` is in the available commands from `show-help`. I assumed that list comes from AFC itself, so maybe a mapping/alias is just missing?

**Comment by ViRb3** [comment]
Found the relevant code, seems like this is there for a reason:

https://github.com/doronz88/pymobiledevice3/blob/dae7c727ed94d11095ac2b3651e60b716a306c62/pymobiledevice3/services/afc.py#L778-L785

**Comment by doronz88** [comment]
Created this on xonsh repo:

https://github.com/xonsh/xonsh/issues/5683

If this issue is resolved, I can remove the `file` hack.
It was just there so it won't break the shell.
