### ISSUE TITLE
python -m pymobiledevice3 diagnostics battery monitor     Why the command is not once a second to refresh the data

### ISSUE THREAD

**Issue by gkls** [doronz88/pymobiledevice3#1230]

**Comment by gkls** [comment]
![7231CD3A-D92B-41DF-A0E7-0CBD0ACBE7D4](https://github.com/user-attachments/assets/01079c8a-1502-472f-b0e0-eac9d6b24a55)

**Comment by doronz88** [comment]
What are you going at?

**Comment by gkls** [comment]
> What are you going at?

At the moment I execute this command, and it takes a few seconds to refresh the data, how to refresh the data once a second

**Comment by doronz88** [comment]
Cannot be controlled. Determined by device

**Comment by gkls** [comment]
> Cannot be controlled. Determined by device

At present, the frame rate of the device can refresh the data once a second, and the power consumption can be refreshed once every few seconds, is this normal?

**Comment by doronz88** [comment]
You're welcome to submit a PR the prints the info only when it does indeed change
