### ISSUE TITLE
Can't `pymobiledevice3 remote pair` to AppleTV connected via Ethernet

### ISSUE THREAD

**Issue by corrrso** [doronz88/pymobiledevice3#1234]
**Test environment**
- AppleTV 4K A2169

**Describe the bug**
`pymobiledevice3 remote pair` can't find any device, I get error `pymobiledevice3.cli.remote[340] ERROR No devices were found during bonjour browse`. Device is connected to my client via Ethernet (no USB-C on this device).

The interesting thing is that I can see the device if I do `pymobiledevice3 bonjour remotepairing`, which I would have expected to be empty if the device was unreachable.
```
[
    {
        "hostname": "192.168.9.20",
        "port": 49152
    }
]
```

Am I missing some steps to be able to pair?

**Comment by doronz88** [comment]
For the pairing over wifi you need to see the device via:

```shell
pymobiledevice3 bonjour remotepairing-manual-pairing
```

**Comment by corrrso** [comment]
Thanks.

By going in Settings → Remotes and Devices → Remote App and Devices, I can see the device and can pair successfully.

The issue now is that the command `pymobiledevice3 remote tunneld` takes between 3 and 5 minutes to set up a connection. Is this normal? Is there a way to speed this up?

Also, another question: do you know where the pairing information is stored?

**Comment by corrrso** [comment]
Just found that if all the various tunneld parameters are specified so that only wifi research is enabled, the opening of the tunnel becomes as fast as usual (a bunch of seconds)

`pymobiledevice3 remote tunneld --no-usb --no-usbmux --no-mobdev2 --wifi`. Thanks for the support once more!

**Comment by doronz88** [comment]
Interesting, if u figure out what caused it please submit a PR for that
