### ISSUE TITLE
install_driver_if_required  can't be found in the pymobiledevice3 

### ISSUE THREAD

**Issue by wangruiz** [doronz88/pymobiledevice3#1243]
**Test environment**
- Host OS version.
- Target device model and iOS version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Pymobile no longer provides an api to install drivers. You need to get them elsewhere
