### ISSUE TITLE
For macOS15.0, pymobiledevice3 remote start-tunnel doesn't work

### ISSUE THREAD

**Issue by ianyumi** [doronz88/pymobiledevice3#1245]
Test environment

macOS 15.0
iPhone 11，iOS17.7

Describe the bug

Launch a tunnel-server named tunneld to automatically detect devices and establish connections
execute the command: sudo python3 -m pymobiledevice3 remote start-tunnel --udid xxxx

Logs
ERROR Device is not connected

**Comment by doronz88** [comment]
Probably a bug with your device setup. Verify with xcode
