### ISSUE TITLE
sslpsk-pmd3 Macmini

### ISSUE THREAD

**Issue by KingRat0011** [doronz88/pymobiledevice3#1247]
MacOS Sequola Version 15.0.1

`python3 -m pip install -U pymobiledevice3
......
copying sslpsk_pmd3/test/example_server.py -> build/lib.macosx-14.0-x86_64-cpython-313/sslpsk_pmd3/test
      copying sslpsk_pmd3/test/__main__.py -> build/lib.macosx-14.0-x86_64-cpython-313/sslpsk_pmd3/test
      running egg_info
      writing sslpsk_pmd3.egg-info/PKG-INFO
      writing dependency_links to sslpsk_pmd3.egg-info/dependency_links.txt
      writing requirements to sslpsk_pmd3.egg-info/requires.txt
      writing top-level names to sslpsk_pmd3.egg-info/top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'sslpsk_pmd3.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      adding license file 'NOTICE'
      writing manifest file 'sslpsk_pmd3.egg-info/SOURCES.txt'
      copying sslpsk_pmd3/_sslpsk.c -> build/lib.macosx-14.0-x86_64-cpython-313/sslpsk_pmd3
      running build_ext
      building 'sslpsk_pmd3._sslpsk_openssl1' extension
      creating build/temp.macosx-14.0-x86_64-cpython-313/sslpsk_pmd3
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DOPENSSL_VER=openssl1 -DINIT_SSLPSK_OPENSSL=init_sslpsk_openssl1 -DPYINIT_SSLPSK_OPENSSL=PyInit__sslpsk_openssl1 -Iopenssl1/include/ -I/Users/diginetiot/pymobile/include -I/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c sslpsk_pmd3/_sslpsk.c -o build/temp.macosx-14.0-x86_64-cpython-313/sslpsk_pmd3/_sslpsk.o
      sslpsk_pmd3/_sslpsk.c:19:10: fatal error: 'openssl/ssl.h' file not found
         19 | #include <openssl/ssl.h>
            |          ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sslpsk-pmd3
Failed to build sslpsk-pmd3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sslpsk-pmd3)
minimac:~ diginetiot$`

Can anyone please point me in the right direction please

**Comment by KingRat0011** [comment]
It was a problem with my python3 install

**Comment by w6w6w** [comment]
why

**Comment by radovanvacek** [comment]
what kind of problem?

**Comment by doronz88** [comment]
Python 3.13 is not yet supported
