### ISSUE TITLE
Device update

### ISSUE THREAD

**Issue by E3lleyyaa** [doronz88/pymobiledevice3#1268]
s it possible to download only the latest update instead of downloading and installing the full system image? Since the image is about 10 GB, while the update itself is around 1-2 GB, it would also take less time. Or is this related to the issue of receiving incremental updates from Apple?
@doronz88

**Comment by E3lleyyaa** [comment]
@doronz88 https://github.com/libimobiledevice/idevicerestore/issues/691

**Comment by doronz88** [comment]
You're talking about an OTA update which is only possible on-device

**Comment by E3lleyyaa** [comment]
@doronz88 Sorry for spamming you. Do you know anything about the issue I mentioned earlier? It’s the first time I’ve ever seen that.
