### ISSUE TITLE
Developer commands on Win11 causing issues

### ISSUE THREAD

**Issue by jjensen554git** [doronz88/pymobiledevice3#1269]
**Test environment**
- Host OS version  Win11
- Target device model and iOS version. 17.4.1 (and apparently above)
- iTunes is installed

**Describe the bug**
Developer commands ("developer dvt proclist" for example) that did work on a Win10 workstation are not working on a Win11 workstation.  Typically I use --udid but that elicits an error:
"024-10-30 14:22:04 SEA1-PC-... __main__[40316] WARNING Got an InvalidServiceError. Trying again over tunneld since it is a developer command". But no response from the re-try over tunneld.
Re-trying manually using the --rsd option works as normal.  A seperate issue is getting the rsd ID from an elevated cmd window running "UseShellExecute" - no redirect to a file.

**To Reproduce**
Run tunneld command
Run specific developer commands using the --udid option

**Expected behavior**
Commands work as expected on Win11

**Logs**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Wasn't able to reproduce any of the errors

**Comment by jjensen554git** [comment]
Not surprised. I was able to capture the --rsd outputs from the tunneld command and that resolved my issues. Basically added the issue for awareness in case someone else runs across it.
