### ISSUE TITLE
Extract developer image and signature

### ISSUE THREAD

**Issue by Majhool** [doronz88/pymobiledevice3#1270]
**Test environment**
- Host OS version.
- Target device model and iOS version.
Host: macOS
iOS: 18.0.1
**Describe the bug**
I need to extract developer image and signature to use it with Jitterbug

**Comment by doronz88** [comment]
What do you mean by extract? does it even relate to pymobile?

**Comment by Majhool** [comment]
I mean when I execute this command
pymobiledevice3 mounter list
My device backup image appear and image signature details in JSON File can I use it?

**Comment by doronz88** [comment]
You need to understand better what you are requesting
