### ISSUE TITLE
```pymobiledevice3 bonjour rsd``` Not showing up devices

### ISSUE THREAD

**Issue by HarukaB** [doronz88/pymobiledevice3#1273]
**Test environment**
- Windows 11 23H2 (22631.4317)
- iPhone17,2 iOS 18.2 Beta 2 (22C5125e)

**Describe the bug**
The ```pymobiledevice3 bonjour rsd``` command does not show up my device on either USB or WiFi.
**To Reproduce**
1. Open a privileged terminal.
2. Run ```pymobiledevice3 bonjour rsd``` command.
3. See an empty output

**Expected behavior**
```pymobiledevice3 bonjour rsd``` show up my device.

**Logs**
```
PS C:\Users\> pymobiledevice3 bonjour rsd -v
[]
```
**Additional context**
other 2 subcommands for ```pymobiledevice3 bonjour``` is working correctly, but ```remotepairing-manual-pairing``` don't.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
That is the expected behaviour. Rsd is for usb only and on windows requires special drivers. Assuming you have an iOS which is at least 17.4 you can use the new lockdown tunnels instead

**Comment by HarukaB** [comment]
Got it, however lockdown also can’t create tunnel for my device over WiFi On Nov 9, 2024, at 10:57, doronz88 ***@***.***> wrote:﻿
That is the expected behaviour. Rsd is for usb only and on windows requires special drivers. Assuming you have an iOS which is at least 17.4 you can use the new lockdown tunnels instead
