### ISSUE TITLE
"Fix Battery" Option to Force Battery Health Data Resynchronization After Firmware Restore 

### ISSUE THREAD

**Issue by Johnny314** [doronz88/pymobiledevice3#1278]
I’d like to request a new feature to be added to the tool. Specifically, I'm looking for a "Fix Battery" option that forces iOS to resynchronize and retrieve fresh battery health data from the Battery Management System (BMS) during or after a firmware restore.

Background:
In tools like 3uTools, there is a useful feature called "Fix Battery" that is commonly used after replacing an iPhone battery. This option forces iOS to fetch accurate battery health information (capacity, cycle count, etc.) from the BMS chip, which can fix incorrect or missing battery health statistics in iOS.

Currently, when replacing an iPhone battery or after a firmware restore, iOS may not automatically refresh the battery health status, leading to inaccurate data being displayed in Settings. This feature is particularly useful in cases where:

The battery was recently replaced.
Battery health data was corrupted or not displayed properly.

**Comment by doronz88** [comment]
I first tried 3utools, and it looks like at least on my iPhone 15 Pro I don't such an option to test it

**Comment by doronz88** [comment]
By the looks of it from YouTube, doesn't either a factory-reset or `pymobiledevice3 restore update --erase` simply does the same?

**Comment by Johnny314** [comment]
i tried with update -- erase but it does not update the battery health 
below is the logs of 3utool
Unmounting Filesystem
Creating Partition Map
Creating Filesystem
FIXING BATTERY WEALTH
Detecting connection
Found a device with mode: Restore
Detecting ProductType
matching device type through original information
Detected iDevice did not exit the last restore process, try to reboot
Reboot
seems like they are sending something while device in restore mode

**Comment by doronz88** [comment]
As I said, I have no way of knowing how this works, as my 3uTools doesn't offer this option at least for my product type.

**Comment by Johnny314** [comment]
![Capture](https://github.com/user-attachments/assets/86fbed92-b4ce-4861-a39c-00a01e5df789)
this is the option in 3u

**Comment by doronz88** [comment]
![image](https://github.com/user-attachments/assets/1246355e-239e-4328-970f-877271812abf)
Doesn't look like this on my version
