### ISSUE TITLE
ios12 can not get wifi info

### ISSUE THREAD

**Issue by cyrilchans** [doronz88/pymobiledevice3#1284]
**Test environment**
- device_version: ios 12.5.7

**Describe the bug**
The wifi information obtained through the command is returned as null

![76f33ab7-c292-4be8-ab93-3408521aeaba](https://github.com/user-attachments/assets/ba429ca6-de96-4f4e-92f0-82bd858f0be6)

**Comment by doronz88** [comment]
Probably your device uses another entry in the devicetree. Can you upload it?

**Comment by cyrilchans** [comment]
Sure, I can provide the device tree, but I'm not sure how to obtain it. Could you please guide me on how to retrieve the device tree

**Comment by doronz88** [comment]
Can be find in somewhere inside the sysdiagnose archive

**Comment by cyrilchans** [comment]
[IODeviceTree.txt](https://github.com/user-attachments/files/17943900/IODeviceTree.txt)
Is that it?

**Comment by cyrilchans** [comment]
I found it , ios 12 devices retrieve wifi network names with this parameter: IO80211Interface.

**Comment by doronz88** [comment]
Yeah, you can play with the options for this command to find the correct query according to your IORegistry tree:
```shell
pymobiledevice3 diagnostics ioregistry --help
```
Afterwards please either supply with the correct arguments needed for this query in here so I'll create a PR for you to test if this fixes the issue

**Comment by cyrilchans** [comment]
![image](https://github.com/user-attachments/assets/e43b2477-a6f7-4224-98ee-fea4225d44c6)
ioclass：IO80211Interface

**Comment by doronz88** [comment]
Can you please verify #1296 solves the issue?

**Comment by cyrilchans** [comment]
it looks like it fixes the issue. Great job!

**Comment by cyrilchans** [comment]
👍👍👍👍👍👍👍👍
