### ISSUE TITLE
Error with DiagnosticsServiceService.capture_sysdiagnose 

### ISSUE THREAD

**Issue by klekks** [doronz88/pymobiledevice3#1285]
**Test environment**
- Windows 11 + python3.10 + pymobiledevice3 latest
- iPhone 11 Pro Max , iOS 18.1 .

**Describe the bug**
I got an error when I ran the following code:

```
    addr = ("fdb9:a956:1735::1", 52540)
    rsds = RemoteServiceDiscoveryService(addr)
    await rsds.connect()
    dss = DiagnosticsServiceService(rsds)
    await dss.connect()

    res = await dss.capture_sysdiagnose(True)
```

Error message:
  

> packages\pymobiledevice3\remote\core_device\core_device_service.py", line 36, in invoke
>     raise CoreDeviceError(f'Failed to invoke: {feature_identifier}. Got error: {response}')
> pymobiledevice3.exceptions.CoreDeviceError: Failed to invoke: com.apple.coredevice.feature.capturesysdiagnose. Got error: {'CoreDevice.error': {'userInfoWithNSSecureCoding': b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\nX$versionY$archiverT$topX$objects\x12\x00\x01\x86\xa0_\x10\x0fNSKeyedArchiver\xd1\x08\tTroot\x80\x01\xa8\x0b\x0c\x17\x18\x19\x1c"#U$null\xd3\r\x0e\x0f\x10\x13\x16WNS.keysZNS.objectsV$class\xa2\x11\x12\x80\x02\x80\x03\xa2\x14\x15\x80\x04\x80\x06\x80\x07\\NSCodingPath_\x10\x12NSDebugDescription\xd2\x0e\x0f\x1a\x1b\xa0\x80\x05\xd2\x1d\x1e\x1f Z$classnameX$classesWNSArray\xa2\x1f!XNSObject_\x10\x1dExpected to find key options.\xd2\x1d\x1e$%\\NSDictionary\xa2$!\x00\x08\x00\x11\x00\x1a\x00$\x00)\x002\x007\x00I\x00L\x00Q\x00S\x00\\\x00b\x00i\x00q\x00|\x00\x83\x00\x86\x00\x88\x00\x8a\x00\x8d\x00\x8f\x00\x91\x00\x93\x00\xa0\x00\xb5\x00\xba\x00\xbb\x00\xbd\x00\xc2\x00\xcd\x00\xd6\x00\xde\x00\xe1\x00\xea\x01\n\x01\x0f\x01\x1c\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00&\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x1f', 'code': 4865, 'userInfo': {'NSDebugDescription': 'Expected to find key options.', 'NSCodingPath': '[]'}, 'domain': 'NSCocoaErrorDomain'}}

**Expected behavior**
I expect the function to be executed successfully.

**Additional context**

As I understand it, some key is missing in the transmitted data. Could you tell me what the problem might be?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This service was initially supposed to only expected to work on internal devices. Looks like now it's available publicly

**Comment by klekks** [comment]
@doronz88 

What do you mean by an internal device in terms of an iPhone? Is it meant for internal use by Apple?

**Comment by doronz88** [comment]
This service is an old one, but previous uses just yielded an error of "your device cannot use this". Now this looks like they chose to enable it

**Comment by doronz88** [comment]
Can you test this PR?
https://github.com/doronz88/pymobiledevice3/pull/1288

**Comment by klekks** [comment]
@doronz88 
Well, it is seems to be working. Anyway, sysdiagnose started on the device. Thank you very much!

I noticed that you added  to the request `"options": {'collectfullogs': True}`. Could you tell me, how did you get the information that exactly such parameters are needed?

UPD. I noticed that the sysdiagnose file is being copied very slowly. I have encountered such a copying problem with libimobiledevice. There was a problem because of the small size of the buffer. Maybe in the case of pymobiledevice3, you can also somehow increase the buffer?

**Comment by doronz88** [comment]
Literally from the error the device responded with in your original issue
