### ISSUE TITLE
BlockingIOError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by 0xrasel** [doronz88/pymobiledevice3#1290]
**Test environment**
- Host OS - MacOS Sequoia Version 15.1.1
- Device - iPhone SE (2020)
- iOS version **18.1**

**To Reproduce**
1. start remote tunnel `sudo pymobiledevice3 remote tunneld`
2. open your app in suspended mode `pymobiledevice3 developer core-device launch-application --suspended myapp.MyNewApp`
3. attach the process from debug menu from xcode `xcode > debug > attach process`
4. forward the port `pymobiledevice3 usbmux forward 27042 27042`
5. `objection -N -h 127.0.0.1 -p 27042 explore` after run the objection command you will see the error.

**Expected behavior**
It should handle the socket data properly.

**Logs**
❯ pymobiledevice3 usbmux forward 27042 27042                                             
2024-11-24 17:21:29 MacBookPro pymobiledevice3.tcp_forwarder[15755] INFO connection established from local to remote
2024-11-24 17:21:29 MacBookPro pymobiledevice3.tcp_forwarder[15755] ERROR Exception when sending data to socket
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymobiledevice3/tcp_forwarder.py", line 121, in _handle_data
    other_sock.sendall(data)
BlockingIOError: [Errno 35] Resource temporarily unavailable
2024-11-24 17:21:29 MacBookPro pymobiledevice3.tcp_forwarder[15755] INFO connection <socket.socket [closed] fd=-1, family=2, type=1, proto=0> was closed

pymobiledevice3 output

<img width="928" alt="image" src="https://github.com/user-attachments/assets/bcac9db8-633b-4a51-acae-458f3cbb4e77">

Objection output

<img width="693" alt="image" src="https://github.com/user-attachments/assets/bc5afb37-8980-4024-beb7-ee52075ea376">

# Solution

I have figured out the solution for this issue after reviewing the [urllib3 issue](https://github.com/urllib3/urllib3/issues/63#issuecomment-15447770).

update `/usr/local/lib/python3.12/site-packages/pymobiledevice3/tcp_forwarder.py`  **_handle_data** function with below code and `import time`

```
import time

    def _handle_data(self, from_sock, closed_sockets):
        self.logger.debug(f"Handling data from {from_sock}")
        try:
            data = from_sock.recv(1024)
            if not data:
                raise ConnectionResetError("Connection closed by the peer.")
        except BlockingIOError:
            self.logger.warning(f"Non-blocking read failed on {from_sock}, retrying later.")
            return
        except OSError as e:
            self.logger.error(f"Error reading from socket {from_sock}: {e}")
            self._handle_close_or_error(from_sock)
            closed_sockets.add(from_sock)
            return

        other_sock = self.connections.get(from_sock)
        if not other_sock:
            self.logger.error(f"No connection mapping found for {from_sock}.")
            return

        try:
            total_sent = 0
            while total_sent < len(data):
                try:
                    sent = other_sock.send(data[total_sent:])
                    total_sent += sent
                except BlockingIOError:
                    self.logger.warning(f"Socket buffer full for {other_sock}, retrying in 100ms.")
                    time.sleep(0.1)  # Introduce a small delay
                except BrokenPipeError:
                    self.logger.error(f"Broken pipe error on {other_sock}.")
                    raise
        except OSError as e:
            self.logger.error(f"Unhandled error while forwarding data: {e}")
            self._handle_close_or_error(from_sock)
            closed_sockets.add(from_sock)
            closed_sockets.add(other_sock)
            
```

**Comment by doronz88** [comment]
Instead of pasting a whole chunk of code, please explaion the fix and why

**Comment by 0xrasel** [comment]
### Fix Explanation

The fixed code introduces improvements to handle these edge cases gracefully:

---

#### **Handling `BlockingIOError` in `recv`**
- **Retry Logic**:
  - If `BlockingIOError` occurs during `recv`, the code logs a warning and skips further processing for the current call, allowing the event loop to retry later.
- **Why This Works**:
  - Non-blocking sockets often require multiple attempts to complete operations as data arrives asynchronously.

---

#### **Handling `BlockingIOError` in `send`**
- **Retry with Delay**:
  - If the socket buffer is full during `send`, the code catches `BlockingIOError` and pauses briefly (100 ms) using `time.sleep`, then retries sending the remaining data.
- **Why This Works**:
  - By introducing a short delay, the buffer has time to free up, and data can be sent without overwhelming the socket or consuming excessive CPU cycles.

---

### **Additional Improvements**

#### **Detecting Closed Connections**:
- If `recv` returns no data (`data` is empty), the connection is considered closed, and a `ConnectionResetError` is raised. This ensures proper cleanup.

#### **Better Error Handling**:
- Distinguishes between different socket errors (`BlockingIOError`, `BrokenPipeError`, `OSError`) for more specific and actionable logging.
- Cleans up sockets (adds to `closed_sockets` set) in all failure scenarios.

#### **Graceful Socket Mapping**:
- Ensures the corresponding socket (`other_sock`) exists before trying to send data.

**Comment by doronz88** [comment]
Why is the sleep necessary? Doesn't the io syscall wait without exhausting the CPU?

**Comment by 0xrasel** [comment]
### **Non-blocking I/O Behavior**
- Non-blocking sockets return control to the program immediately if an operation (e.g., `send`, `recv`) cannot proceed. They raise a `BlockingIOError` if the socket is not ready.
- Without a mechanism to wait or retry, the program would continuously attempt the operation in a tight loop, consuming 100% CPU.

---

### **`time.sleep` Reduces Busy-Waiting**
- The `time.sleep(0.1)` introduces a small delay before retrying the I/O operation. This:
  - **Prevents the program** from repeatedly hammering the socket with I/O syscalls.
  - **Frees up CPU cycles** for other tasks or threads during the wait.

---

### **Doesn’t the I/O Syscall Wait Without Exhausting the CPU?**

#### **Blocking I/O**:
- In blocking mode, **yes**, the syscall waits without exhausting CPU because the kernel pauses the thread until the operation can proceed.

#### **Non-blocking I/O**:
- In non-blocking mode, the syscall **returns immediately** if the socket is not ready, which requires the application to manage retries explicitly.

**Comment by doronz88** [comment]
Thanks for your very detailed explaination! will merge this fix soon :)

**Comment by irdkwmnsb** [comment]
I don't think this approach is reasonable. If a small delay is introduced and write is attempted later - there is no need to use non blocking IO - you can literally set `setblocking(True)` and the code would be faster - since this patch is literally the definition of blocking IO.  
ChatGPT generated answers don't help either. For proxying having blocking IO is unacceptable.  
The proper approach would be not to read data from the opposing socket when our socket is full.
See https://github.com/doronz88/pymobiledevice3/pull/1277 for reasons why blocking was turned off.

**Comment by doronz88** [comment]
@irdkwmnsb feel free to submit a PR
