### ISSUE TITLE
Command `sudo python3 -m pymobiledevice3 remote start-tunnel` has performance issues

### ISSUE THREAD

**Issue by HackHarry** [doronz88/pymobiledevice3#1294]
**Test environment**
- Host OS version：macOS 15.1
- Target device model and iOS version: 
    - iPhone 11, iOS 17.7.1
    - iPhone 13，iOS 17.1.1
    - iPhone 14 Pro，iOS 18.0

**Describe the bug**
I discovered that the trusted tunnel established by `sudo python3 -m pymobiledevice3 remote start-tunnel` has some performance issues. For instance, when getting `com.apple.instruments.server.services.coreprofilesessiontap` data, although 10 minutes have actually passed, we usually only receive approximately 5 minutes worth of return data.

Because I need use iOS 17.0 ~ iOS 17.3 device, so I don't use command `sudo python3 -m pymobiledevice3 lockdown start-tunnel`.

**To Reproduce**
- This only happens on certain Mac devices. These devices may have a high USB transfer load, which are using WDA at the same time.
- I use command `sudo python3 -m pymobiledevice3 remote start-tunnel` to start tunnel.
- And use another tools to collect `com.apple.instruments.server.services.coreprofilesessiontap` data relying the tunnel started by pymobiledevice3
- Then I found when 10 minutes hava actually passed, I only receive approximately 5 minutes's data.
- I try to use another tools to start tunnel writing by golang, and do the same thing on the same Mac device using the same iPhone, this data delay problem no longer exists.

**Expected behavior**
I want to know why this data delay happends and hope it can be solved.

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This is probably mainly to the fact the QUIC implementation is done in pure-python.
However, if you're using Python 3.13 which added native SSLPSK support, `pymobiledevice3` will use TCP tunnels instead which are implemented at the OS-level and therefore much faster.

For reference: https://github.com/doronz88/pymobiledevice3/commit/903103bcacb9df5bd10129d5f4c0a5ff83a98ed3

**Comment by HackHarry** [comment]
Great！Thanks for you reply. 
I will try to use Python 3.13 later. But my project have many other dependencies, it may take some time to check if support Python 3.13, so I close this issue for now.
