### ISSUE TITLE
pymobiledevice3 bonjour remotepairing return nothing

### ISSUE THREAD

**Issue by qdk0901** [doronz88/pymobiledevice3#1295]
**Test environment**
- windows 11
- iphone 15, ios 18, with developer mode enabled

**Describe the bug**
execute `pymobiledevice3 bonjour remotepairing`, but return with empty result
execute `pymobiledevice3 bonjour mobdev2`, can see my iphone

**To Reproduce**

**Expected behavior**
something should show up when `pymobiledevice3 bonjour remotepairing`, and pymobiledevice3 can connect the iphone without usb connecting, am I wrong?

**Logs**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Make sure device is in developer mode since it only exposes itself as a network device if it's in developer mode

**Comment by doronz88** [comment]
Feel free to reopen
