### ISSUE TITLE
pymobiledevice3 developer dvt simulate-location play not working on iOS 18

### ISSUE THREAD

**Issue by gabrielmarmen** [doronz88/pymobiledevice3#1305]
**Test environment**
- MacOS 15.1.1
- iPhone 15 Pro Max iOS 18.1.1

**Describe the bug**
The `simulate-location play` command is not working on my device running iOS 18.1.1. I don't get any error but the location in iOS doesn't change at all when using this command.

The command `simulate-location set` does work correctly and changes my location in Maps.

**To Reproduce**

Use this command:
`pymobiledevice3 developer dvt simulate-location play --rsd fdcb:e24e:2a6::1 61028 location.gpx`

**Expected behavior**
My location should change on the device.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
I couldn't reproduce your issue using a static location as follows (using a running `tunneld`):

```shell
developer dvt simulate-location set -- 40.690008 -74.045843
```

Can you test if this works? If not, please share your specific gpx file

**Comment by gabrielmarmen** [comment]
Hello, 

Yes, indeed, the command you ran also works on my side. 

Here is the gpx file to test with `play` instead. 
[boston.zip](https://github.com/user-attachments/files/18052612/boston.zip)

Thanks !

**Comment by gabrielmarmen** [comment]
Ok, I just tried with another random gpx I found online and it works correctly. I think my issue is that my GPX is using waypoints and it requires a track instead.

I'll try modifying my gpx and report back.

Thanks !

**Comment by gabrielmarmen** [comment]
Solution was to use a track instead of waypoints in the gpx file.

**Comment by BiancoChiu** [comment]
Hi! Would you please share how to generate a track gpx file? Is there any recommondations for online websites?
