### ISSUE TITLE
FEATURE REQUEST: CoreDevice delete file command or copy to command

### ISSUE THREAD

**Issue by HackHarry** [doronz88/pymobiledevice3#1309]
**Is your feature request related to a problem? Please describe.**
I found that devices running iOS 17+ save data related to xcode testmanagerd under the coreDevice file path, causing the phone's storage space to be continuously occupied by the "System Data" section and unable to be deleted. Later, I discovered that space can be freed by using the `devicectl device copy to` command to overwrite the original large files with empty files, which resolves my issue. However, `devicectl` depends on the Xcode version, and I found that pymobiledevice3 supports reading coreDevice files but don't support deleting or copying. 

**Describe the solution you'd like**
I hope it can support deletion as well. If deletion is not possible, I hope it can support the `devicectl copy to` related command.

**Comment by doronz88** [comment]
Can you provide the output of this command while performing your file write?

```shell
pymobiledevice3 syslog live -pn dtfileserviced
```

**Comment by doronz88** [comment]
Also, you can try the new `propose-file` subcommand in this PR https://github.com/doronz88/pymobiledevice3/pull/1310. Maybe it can write to your path?

**Comment by doronz88** [comment]
Feel free to reopen this is the issue is not resolved

**Comment by HackHarry** [comment]
Thanks for your work, it is exactly what I need. But when I use this command, find some problems and fix it

PR: https://github.com/doronz88/pymobiledevice3/pull/1313
