### ISSUE TITLE
`opack` overrides `pymobiledevice3` script

### ISSUE THREAD

**Issue by m1stadev** [doronz88/pymobiledevice3#1311]
The [`opack`](https://github.com/loriwitt/opack) library, which was included in v2.0.4, [installs a broken `pymobiledevice3` script when installed.](https://github.com/loriwitt/opack/blob/main/pyproject.toml#L34-L35) This seems like an honest mistake, but an issue for it was opened in October that hasn't been addressed yet (loriwitt/opack#6), and the author hasn't had any public activity on GitHub in nearly a year.

Perhaps pymd3 could switch to a fork of `opack` with the script removed until the author fixes it on their end?

**Comment by doronz88** [comment]
Oh wow didn't know about that! I'll create my own fork for that.
