### ISSUE TITLE
Unplug USB and then can't connect to iPhone.

### ISSUE THREAD

**Issue by PlanetartRoc** [doronz88/pymobiledevice3#1321]
**Test environment**
- Host OS version
   windows 11
- Target device model and iOS version.
  17.6.1

**Describe the bug**
Unplug USB and then can't connect to iPhone.

**To Reproduce**
1. IPhone connects to the computer via a data cable.
2. use command: pymobiledevice3 usbmux list
```
[
    {
        "BuildVersion": "21G93",
        "ConnectionType": "USB",
        "DeviceClass": "iPhone",
        "DeviceName": "HZ QA \u2019s iPhone",
        "Identifier": "00008130-0010292836E2001C",
        "ProductType": "iPhone16,1",
        "ProductVersion": "17.6.1",
        "UniqueDeviceID": "00008130-0010292836E2001C"
    }
]
```
4. use command: pymobiledevice3 lockdown start-tunnel:
```
C:\Windows\System32>pymobiledevice3 lockdown start-tunnel
2024-12-24 16:29:18 Roc-ThinkBook16 pymobiledevice3.cli.remote[26904] INFO tunnel created
Identifier: 00008130-0010292836E2001C
Interface: pywintun
Protocol: TunnelProtocol.TCP
RSD Address: fd08:1add:59bf::1
RSD Port: 59365
Use the follow connection option:
--rsd fd08:1add:59bf::1 59365
```
5. Use command: pymobiledevice3 lockdown wifi-connections on --returned nothing
6. Use command: pymobiledevice3 remote browse
```
{
    "usb": [],
    "wifi": []
}
```
7. Use command: pymobiledevice3 developer dvt ls / --rsd fd08:1add:59bf::1 59365
```
/usr
/bin
/sbin
/.file
/etc
/System
/var
/Library
/private
/.b
/dev
/tmp
/Applications
/Developer
/cores
```
8. Unplug the cable, will print the message below "pymobiledevice3 lockdown start-tunnel"：
```
pymobiledevice3.cli.remote[26904] INFO tunnel was closed
```
9. Use command again: pymobiledevice3 lockdown start-tunnel
```
2024-12-24 16:45:00 Roc-ThinkBook16 pymobiledevice3.__main__[10272] ERROR Device is not connected
```
pymobiledevice3 remote start-tunnel
```
2024-12-24 16:47:33 Roc-ThinkBook16 pymobiledevice3.__main__[22960] ERROR Device is not connected
```
And then the connection to the iPhone is lost, I can do nothing.
Is there something wrong with me?

**Comment by doronz88** [comment]
Sounds the windows iTunes service doesn't search for network devices. You can use tunneld instead which will attempt to the device via all the possible ways:
```shell
sudo pymobiledevice3 remote tunneld
```

**Comment by PlanetartRoc** [comment]
Hmmm...
That's wright: The iTunes service can't search for network devices.
This command also can't find network devices: sudo pymobiledevice3 remote tunneld
I think this is a matter of corporate firewall group policy? But I can do nothing with it...
Thank you for your reply.

**Comment by doronz88** [comment]
It searches for network devices found in your LAN by sending a multicast message. If you're not on the same subnet then it's not possible

**Comment by PlanetartRoc** [comment]
The final confirmation is the network router set-up problem, thank you for the support

**Comment by ruokbb** [comment]
@PlanetartRoc Hello, we're experiencing the same issue as you. You mentioned it's a network router problem—could you please share the solution?
