### ISSUE TITLE
GPL 3.0 Licence issue. 

### ISSUE THREAD

**Issue by GotoHack** [doronz88/pymobiledevice3#143]
Hello ! 
Thank you for the pymobiledevice update to python3.
As you stated the project has started as a pymobiledevice fork and you still have some pieces of code of the original project. 
Pymobiledevice is licenced under GPL 3.0. which is contaminent. 
Please upgrade the Licence ? 
Regards

**Comment by doronz88** [comment]
can you verify the PR solves the issue correctly?

**Comment by doronz88** [comment]
@GotoHack many people are asking for license change to LGPL. What is your opinion on the matter?
