### ISSUE TITLE
Pass environment variables to process

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#192]
In `ProcessControl.launch` please add the ability to pass environment variables to the app.
You can pass them as a dictionary between the arguments and the bundle id (currently an empty dictionary is being passed)

**Comment by doronz88** [comment]
Please checkout `feature/process_launch_with_env` to verify this works well for you. I wasn't sure what's the best CLI interface for this. Currently you can do something like:

```shell
pymobiledevice3 developer dvt launch com.apple.mobilesafari --environment '{"a": "bla"}'
```

What do you think?

**Comment by doronz88** [comment]
Changed the CLI usage to the following:
```shell
pymobiledevice3 developer dvt launch com.apple.mobilesafari --env KEY1 VALUE1 --env KEY2 VALUE2
```
Please verify this works well

**Comment by doronz88** [comment]
Tested the variables are passed well :)
This feature is now officially available on:
https://github.com/doronz88/pymobiledevice3/releases/tag/v1.14.6

**Comment by vToMy** [comment]
You are fast... thanks!
