### ISSUE TITLE
Merge #200 broke Windows AFC service functionality

### ISSUE THREAD

**Issue by Starwarsfan2099** [doronz88/pymobiledevice3#208]
**Test environment**
- Windows 10
- iPhone 12 (iOS 14.3)

**Describe the bug**
Merge #200 broke some Windows functionality, specifically connecting to a device via AFC. The new way of performing `ls` uses `pygnuutils`. `pygnuutils` requires the package `fcntl` which does not support Windows. Windows support has been great for me at least until this change. 

**To Reproduce**
`python .\tests\services\test_afc.py`

**Expected behavior**
Expected a succsesful test. 

**Logs**
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\afflux\pymobiledevice3\tests\services\test_afc.py", line 7, in <module>
    from pymobiledevice3.services.afc import AfcService, afc_error_t, MAXIMUM_READ_SIZE
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pymobiledevice3-1.16.0-py3.9.egg\pymobiledevice3\services\afc.py", line 20, in <module>
    from pygnuutils.ls import Ls, LsStub
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pygnuutils-0.0.3-py3.9.egg\pygnuutils\ls.py", line 1, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by doronz88** [comment]
Thanks for the report! I created a PR that fixes the issue but in a somewhat patchy way. I discussed with @matan1008 and he plans to add windows support for `pygnuutils` so this is just a quick solution for the meantime.

Can you verify the PR solves the issue on your setup?

**Comment by Starwarsfan2099** [comment]
The PR does solve the issue on my setup! Thank you!

**Comment by doronz88** [comment]
`pygnuutils` now has windows support.
Can you verify once more this PR solves the issue? you should now have full `ls` capabilities on windows within AFC. If so, I'll publish this release.

**Comment by Starwarsfan2099** [comment]
I have verified this PR solves my issue on Windows and is still functioning perfectly on Linux. Thank you!

**Comment by doronz88** [comment]
Thanks again for the report and testing :). I've merge this change and published a new release with the solution:
https://github.com/doronz88/pymobiledevice3/releases/tag/v1.16.1

We also modified the github CI script to include test installation on `windows-latest` so such things won't break again.
