### ISSUE TITLE
How to run shell commands on device?

### ISSUE THREAD

**Issue by vadimszzz** [doronz88/pymobiledevice3#214]
Any way to access (jailbroken) shell? How to do this directly or using ssh?

**Comment by doronz88** [comment]
Jailbroken devices aren't the scope of `pymobiledevice3`. This project focuses on the exposed APIs by the `lockdownd` daemon on iOS devices.

Assuming you already have a jailbroken device connected via USB, you can use `pymobiledevice3` to create a tunnel from a local port on your machine to the device's ssh port. 

For example (assuming the SSH server listens on tcp port 44):

```shell
# forward local tcp port 4444 to device's local tcp port 44
# use this command on a seperate shell:
pymobiledevice3 lockdown forward 4444 44 -vvv

# OR, this one to tunnel the ports daemonized (supported only on *nix os):
pymobiledevice3 lockdown forward 4444 44 -d

# now just connect to the device
ssh root@localhost -p 4444
```

**Comment by vadimszzz** [comment]
Thanks
