### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by vadimszzz** [doronz88/pymobiledevice3#223]
**Test environment**
- Host: macOS Big Sur
- Target: iPhone 7 iOS 14.6

**Describe the bug**
```python
import os, sys
import traceback
import struct
import time

from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.services.pcapd import PcapdService, PCAP_HEADER, PACKET_HEADER

from exynex import utils, frida_utils
from exynex.termcolors import *


def capture_network_to_pcap(lockdown_device: LockdownClient, frida_device, remote_pid,
	pcap_output, keylog_output, packets_count, capturing_timeout):
	""" Capture packets on a device and log SSLKEYLOG. """
	session = frida_device.attach(remote_pid)
	with open(pcap_output, "wb") as pcap_output_fd, \
	     open(keylog_output, "w") as keylog_output_fd:
		# Run sslkeydump
		sslkeylog_script = frida_utils.get_agent_script("sslkeylog.js")
		sslkeylog_agent = session.create_script(sslkeylog_script)
		sslkeylog_agent.on("message", frida_utils.message_handler(on_payload=keylog_output_fd.write))

		# Start capturing packets
		service = PcapdService(lockdown=lockdown_device)
		packets_generator = service.watch(process=remote_pid)

		...
```

```python
BrokenPipeError: [Errno 32] Broken pipe
 File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/process.py", line 26, in capture_network_to_pcap
   service = PcapdService(lockdown=lockdown_device)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pymobiledevice3/services/pcapd.py", line 327, in __init__
   self.service = self.lockdown.start_service(self.SERVICE_NAME)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 300, in start_service
   attr = self.get_service_connection_attributes(name, escrow_bag=escrow_bag)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pymobiledevice3/lockdown.py", line 290, in get_service_connection_attributes
   self.service.send_plist(request)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pymobiledevice3/service_connection.py", line 110, in send_plist
   return self.sendall(message + payload)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pymobiledevice3/service_connection.py", line 61, in sendall
   self.socket.sendall(data)
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/ssl.py", line 1204, in sendall
   v = self.send(byte_view[count:])
 File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/ssl.py", line 1173, in send
   return self._sslobj.write(data)
```

This exception throws from time to time when I start the script too often.

**Comment by doronz88** [comment]
Thanks for the report!
Usually `BrokenPipeError` occurs when the other endpoint (the device) closes the socket on its end which sounds a bit strange. Can you provide a link to the full source code where I can reproduce the bug?

Also, does it occur when using this feature from the CLI (`pymobiledevice3 pcap --process process_name`)?

**Comment by doronz88** [comment]
Another suggestion that might work, instead of passing an already active connection to `lockdown`, try to intiailize a new `LockdownClient` object on function entry.

**Comment by vadimszzz** [comment]
> Another suggestion that might work, instead of passing an already active connection to `lockdown`, try to intiailize a new `LockdownClient` object on function entry.

I'm working on it.

**Comment by vadimszzz** [comment]
> does it occur when using this feature from the CLI?

No, CLI is ok. Only library usage.


Reconnecting fixed this.

**Comment by vadimszzz** [comment]
Btw it would be nice to reconnect automatically if you can implement it. Manual reconnection looks like a quick fix.

**Comment by doronz88** [comment]
The fact this doesn't seem to occur from the CLI leads me to believe this has something to do with whatever is happening on your device (maybe related to a patch? Or a process crashing?). I rather the excpetion will be raised instead of ignoring it silently since this is indeed a bug that requires attention.
If you can reproduce the bug maybe you can check if a crash report is generated each time?

**Comment by vadimszzz** [comment]
> The fact this doesn't seem to occur from the CLI leads me to believe this has something to do with whatever is happening on your device (maybe related to a patch? Or a process crashing?). I rather the excpetion will be raised instead of ignoring it silently since this is indeed a bug that requires attention. If you can reproduce the bug maybe you can check if a crash report is generated each time?

It fails when:

```
lockdown = LockdownClient(udid=udid)
time.sleep(180)
# using lockdown now
```

**Comment by doronz88** [comment]
That's really interesting. From my understanding till now, this happens right after the following log message is written:
```
2022-03-03 20:00:50.072209 lockdownd{lockdownd}[99] <Notice>: _select_socket: receive secure message timeout!
```

After reversing `_select_socket`, this seems like that after exactly 60 seconds, if no socket endpoint received any data, `select` will return from a timeout, print this message and exit. I'm trying to figure out the best possible solution to handle this situation - but it does seem like the correct solution would be to re-establish the connection when this occurs.

**Comment by doronz88** [comment]
@matan1008 @vadimszzz @vToMy what do you think about adding a `@verify_connection` decorator for methods such as the `start_service` inside `LockdownClient`? It can catch the `BrokenPipeError` and re-establish the connection, making it completely transparent for the user

**Comment by vToMy** [comment]
As long as there's some kind of logging upon reconnection that's a fine workaround.
It may also be possible to keep the connection open using `HeartbeatService` - I never used it though - need to verify what is the frequency of those "marco polo" (lol) messages.

**Comment by doronz88** [comment]
@vToMy I've already implemented the [`HeartbeatService`](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/heartbeat.py), but this will only work when using the same `ServiceConnection` object (I forgot to refactor it to use `BaseService` 😅)- meaning it won't solve this

**Comment by doronz88** [comment]
@vadimszzz can you verify [v1.19.3](https://github.com/doronz88/pymobiledevice3/releases/tag/v1.19.3) solves the issue?

**Comment by vadimszzz** [comment]
Yeah I will try in a few days. You’ve done a great job ☺️
We already refactored all our code to reconnect every time before using LockdownService but I can revert it

**Comment by vadimszzz** [comment]
Verified
