### ISSUE TITLE
More permissive license 

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#224]
Is it possible to change the license to LGPL3 (instead of GPL3)?
The main difference is described here:
https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL

**Comment by doronz88** [comment]
As I understand this, this means the project using this library can be of closed source. If so, we don't want this.

**Comment by vToMy** [comment]
I see. Thanks for clarifying.

**Comment by andrei91ro** [comment]
Hello and congratulations for your work.

From this conversation I understand that you do not intend to change the current license from GPL3 to LGPL3.

But have you considered dual licensing where you could maintain the existing open-source license as GPL3 and also offer a paid version in a commercial-friendly license such as Apache2 or MIT?
