### ISSUE TITLE
Apple File Conduit 2 support?

### ISSUE THREAD

**Issue by vadimszzz** [doronz88/pymobiledevice3#227]
**Is your feature request related to a problem? Please describe.**
Can you tell please is it hard to modify AFC module to access AFC"2" device root?
I understand that jailbroken devices are not the point.

**Describe alternatives you've considered**
I can't find any docs or source code for AFC2 on python or ruby.
I'll contribute if you can help.

**Comment by doronz88** [comment]
This actually should be quite easy. It's the same AFC service but with just a different name. This code for example should open an interactive shell

```python
from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.services.afc import AfcShell
AfcShell(lockdown=LockdownClient(), service_name='com.apple.afc2').cmdloop()
```

As you can see in here:
https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/afc.py

You can simply pass any other `service_name` to access another lockdown service which exports AFC apis.

**Comment by doronz88** [comment]
I'll also add that I think accessing the filesystem on a JB device is much simpler using SSH and SCP utils.

**Comment by vadimszzz** [comment]
Thanks very much!
