### ISSUE TITLE
TcpForwarder.listening_event and TcpForwarder.stopped

### ISSUE THREAD

**Issue by WorkHardes** [doronz88/pymobiledevice3#239]
**Test environment**
- Ubuntu 20.04
- Python 3.8.10
- Pymobiledevice3 1.16.3
OpenSSL 1.1.1l
IPhone X
iOS 13.5.1

My code:
```python
import signal
import threading

from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.tcp_forwarder import TcpForwarder


exit_event = threading.Event()
 
def ios_forward_port(
    lockdown_client: LockdownClient, src_port: int, dst_port: int
) -> None:
    forwarder = TcpForwarder(
        lockdown_client, src_port, dst_port, listening_event=exit_event
    )
    forwarder.start()
   

def sigint_handler(signum, frame) -> None:
    exit_event.set()

if __name__ == "__main__":
    udid = "XXX"
    lockdown_client = LockdownClient(udid) 
    src_port = dst_port = 8080
    signal.signal(signal.SIGINT, sigint_handler)
    ios_forward_port(lockdown_client, src_port, dst_port)
```

Please pay attention to the line where there is the following: listening_event=exit_event.
I give exit_event as TcpForwarder argument and I expect the program to end when clicked Ctrl+C, but it doesn't.

In terminal:
```bash
(venv) hella@hella-wofpc:~/examples/ios$ python3 ./forwarding.py 
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

It mabey not a bug, but I suggest the following solution:
Source - file pymobiledevice3/tcp_forwarder.py, class TcpForwarder 42 and 43 strings:
These strings I suggest to delete.
```python
# if self.listening_event:
        #     self.listening_event.set()
```
Same file and class and 49 string:
Replace self.stopped on self.listening_event
```python
if self.listening_event.is_set():
```

---

## I don't understand why you need self.stopped if there is self.listenning_event?
Please correct me if I'm wrong. But my sollution works for me.

**Comment by doronz88** [comment]
I have fixed the documentation regarding the `listening_event` usage.  This event is only used to notify when the listening actually occured so if this code is ran from an external thread it can notify the rest of the project when a connection could be made.

In order to stop the forwarding you should call the `stop()` method instead of setting the `listening_event`. Can you also review the PR and notify if something is still unclear regarding the usage?

**Comment by WorkHardes** [comment]
Ok, I understand, Thank you!
