### ISSUE TITLE
self._dl_handlers[command](message) KeyError: 'DLMessagePurgeDiskSpace'

### ISSUE THREAD

**Issue by asqude** [doronz88/pymobiledevice3#252]
I get this error when I try to backup my iPhone X with iOS 14.6:

```
\venv\lib\site-packages\pymobiledevice3\services\device_link.py", line 62, in dl_loop
    self._dl_handlers[command](message)
KeyError: 'DLMessagePurgeDiskSpace'
```

I think that the error only appears directly with iOS 14 and found this post about the error at the Official Library.
[https://github.com/libimobiledevice/libimobiledevice/issues/1071](url)

**Comment by doronz88** [comment]
I guess the error occurs when there is not enough disk space on the host for the device to upload all its contents on to it.
One of the messages it "asks" the host is `DLMessageGetFreeDiskSpace` which then can tell the device if the host has enough disk space. I see `libimobiledevice` just ignores this message (https://github.com/libimobiledevice/libimobiledevice/blob/a64fcc3988f75cb4fc2388013c245e5e884bb96f/tools/idevicebackup2.c#L2263) so I can do the same, but not sure this is the best practice. 

An exception, or at least a warning should be required to handle this.

**Comment by doronz88** [comment]
@PutzMeinScuf please verify if #253 solves the issue well. This is just the same solution as `libimobiledevice`

**Comment by doronz88** [comment]
BTW, `libimobiledevice` is not an official library. Unfortunately, Apple does not provide any official library to work with their products programatically.

**Comment by asqude** [comment]
This time i get another error:
`\venv\lib\site-packages\pymobiledevice3\services\device_link.py", line 59, in dl_loop   
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 3, 'ErrorDescription': 'Failed to create snapshot: File exists (17) at path "/private/var" (MBErrorDomain/3)', 'MessageName': 'Response'}`

**Comment by doronz88** [comment]
What exactly did you run? Please send the full command with a backtrace.
Also, this is an error reported from within the device so it sounds like it's doing something fishy.

**Comment by asqude** [comment]
Unfortunately I can't reproduce the error anymore.
