### ISSUE TITLE
Will HTTP proxy support be set on the monitored device?

### ISSUE THREAD

**Issue by timwang-ai** [doronz88/pymobiledevice3#312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by doronz88** [comment]
Please clarify your request more clearly. What is it that you want? Define "monitored device".
If all you want is to sniff out HTTP from a connected device, you can use:
https://github.com/doronz88/harlogger

Or if you need actual proxy-ing, I recommend:
https://proxyman.io/

**Comment by timwang-ai** [comment]
Similar to lockdown set_ Value ("en", key ='language ', domain ='com. Apple. International'), set the proxy in WLAN - configure proxy manual server / port

**Comment by doronz88** [comment]
I looked into that, but could not find a lockdown interface to set this value. If you discover one, feel free to reopen this issue.

**Comment by timwang-ai** [comment]
Is it possible to use the certificate mode? So as to realize the global network proxy of iOS

**Comment by doronz88** [comment]
What do you mean by "certificate mode"? It's possible to install certificates via:

```shell
pymobiledevice3 profile install /path/to/cer
```

**Comment by timwang-ai** [comment]
Use this command to install the certificate, but you still need to manually enter the password. Does it support parameterized passwords?

**Comment by timwang-ai** [comment]
Use this command to install the certificate, but you still need to manually enter the password. Does it support parameterized passwords?

**Comment by timwang-ai** [comment]
Use this command to install the certificate, but you still need to manually enter the password. Does it support parameterized passwords?

**Comment by doronz88** [comment]
If device has a password set, I think it must be unlocked first to be able to access private data.
