### ISSUE TITLE
Can I use dfu_enter_recovery function without ispw?

### ISSUE THREAD

**Issue by WorkHardes** [doronz88/pymobiledevice3#322]
**Test environment**
- Fedora 36
- IPhone S (IOS 15.6.1)

There is class Recovery in path pymobiledevice3.restore.recovery and this class has  method dfu_enter_recovery.
I want put device from dfu mode into recovery mode.
My code now for using this function:
```python
from pymobiledevice3.irecv import IRecv
from pymobiledevice3.restore.device import Device
from pymobiledevice3.restore.recovery import Recovery


ecid = "MY_ECID"
irecv = IRecv(ecid)
device = Device(irecv=irecv)

with open("./1.ipsw", "rb") as f:
    ipsw = io.BytesIO(f.read())
recovery_device = Recovery(ipsw=ipsw, device=device)
recovery_device.dfu_enter_recovery()
```

But I don't want to use ipsw file. I just want to device from dfu mode into recovery mode.
I want to see something like that:
```python
from pymobiledevice3.irecv import IRecv
from pymobiledevice3.restore.device import Device
from pymobiledevice3.restore.recovery import Recovery


ecid = "MY_ECID"
irecv = IRecv(ecid)
device = Device(irecv=irecv)
recovery_device = Recovery(device=device)
recovery_device.dfu_enter_recovery()
```

How can i do this without ispw file?

**Comment by doronz88** [comment]
If I understand this correctly, you're currently sending an iBEC image which acts as the Recovery image loaded from RAM and may be different from the one that is actually flashed (you can verify by querying the version).

What you want instead is just an option to make DFU load the preloaded Recovery, right?

If so, the Recovery class  is currently designed around software updates. I'll add an option from an IRecv instance to change this mode directly.

**Comment by doronz88** [comment]
After looking a bit more into that, from my understanding DFU doesn't allow exiting it without sending an iBEC first (there's no "go" command" at this stage) so it should be impossible without a signed firmware or a key combination. I'd be happy to be corrected on this.

**Comment by WorkHardes** [comment]
> 

Yes, that's what I want, you're absolutely right. I'll wait for the finalization of the class)

**Comment by doronz88** [comment]
As I said in:
https://github.com/doronz88/pymobiledevice3/issues/322#issuecomment-1232188723
From my understanding, this shouldn't be possible

**Comment by WorkHardes** [comment]
OK. Thanks for the help.)
