### ISSUE TITLE
how to build command to win32 exe?

### ISSUE THREAD

**Issue by yuanjifeng** [doronz88/pymobiledevice3#331]

**Comment by doronz88** [comment]
what do you mean? simply installing and running?

**Comment by yuanjifeng** [comment]
yes simply running.

**Comment by doronz88** [comment]
Windows installation isn't different from any other OS. Install via pypi and use. You'll still have to run iTunes to find the device and establish a connection

**Comment by vadimszzz** [comment]
- Press `Win+R`
- type `cmd`
- then type

```
pip install pymobiledevice3
```

```
pymobiledevice3
```
