### ISSUE TITLE
iPhone 8 restore using 

### ISSUE THREAD

**Issue by SternXD** [doronz88/pymobiledevice3#337]
**Test environment**
- Debian 11.5
- iPhone 8 (10,1) iOS 15.6 RC

**Describe the bug**
usbmuxd problem

**Expected behavior**
A normal restore

**Logs**
[error.txt](https://github.com/doronz88/pymobiledevice3/files/9691360/error.txt)

**Comment by doronz88** [comment]
It seems `usbmuxd` wasn't running. Added an error handler and a friendlier message for that
