### ISSUE TITLE
Any way to get enable-developer-mode on iOS 16+ with a device password?

### ISSUE THREAD

**Issue by rpayne381** [doronz88/pymobiledevice3#339]
**Test environment**
- Windows 10 with python3.10.4
- iPhone XR with 16.1 beta 2

**Describe the bug**
When running amfi enable-developer-mode, is there any way that we can pass/support a password-protected device? I don't have a Mac and my device is enrolled with a MDM and a device password is required.

**Logs**
```
(pymobileENV) C:\pymobiledevice3-1.29.3>python -m pymobiledevice3 amfi enable-developer-mode
2022-10-03 18:24:42 PCname __main__[41600] ERROR Cannot enable developer-mode when passcode is set
```

**Comment by doronz88** [comment]
Unfortunately, as you can see, `amfid` contains an explicit `if` statement to verify the automatic enablement cannot occur when a password is configured (but at least it gives a very indicative response).

<img width="638" alt="image" src="https://user-images.githubusercontent.com/19665147/193694933-599cd67a-dc63-40fc-982e-5d9ed5498e21.png">

**Comment by rpayne381** [comment]
Thanks for the fast reply
