### ISSUE TITLE
Simulate location with speed, heading and altitude

### ISSUE THREAD

**Issue by chmiiller** [doronz88/pymobiledevice3#340]
Hi there, thanks for the awesome work you have already done!

I want to be able to simulate location with `lat` and `lon` but also be able to simulate speed, heading and altitude.
With `pymobiledevice3 developer simulate-location set x y` we can simulate a position, but do you know if it's possible to extend it in order to support speed for example? I've tried a thing or two myself but I couldn't understand how do you guys reverse all the options that a service or daemon offers.

Thanks!

**Comment by doronz88** [comment]
Thanks! Unfortunately, Apple do not provide APIs for this. `DTSimulateLocation` only supports setting longtitude and latitude parameters.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/19665147/193879751-893ddcdd-3307-4bf6-a749-f664be668812.png">

I haven't checked, but maybe the GPX file option could help for "playing" multiple dots? Or does it don't count for speed?

**Comment by chmiiller** [comment]
thanks for checking into it! I can see that `location` is a CLLocation, so it should be possible but it seems that they don't care about other properties and never implemented it.
What would be the `GPX option`? Does `pymobiledevice3` allow us to use a GPX file?

**Comment by doronz88** [comment]
We've impleneted an option to "play" a gpx file using:
```shell
pymobiledevice3 developer simulate-location play tur_de_franch.gpx
```
This will just set a series of points with the same API. I don't know if maybe the platform will recognize this as going into a specific direction, or just make each point "stand still".

You can also just set a bunch of points yourself on the same lockdown connection instead and check if this works.

**Comment by chmiiller** [comment]
thanks for the suggestions @doronz88 but it doesn't work. I've tried adding the `<time>` tag to the GPX file too with no luck. I've tried asking on the original libimobiledevice's repo if this is possible and the answer is also a "not possible" https://github.com/libimobiledevice/libimobiledevice/issues/1370

Closing this issue then ¯\_(ツ)_/¯
Thanks for replying!
