### ISSUE TITLE
Does pymobiledevice3 developer support the Open and practice VoiceOver on iPhone?

### ISSUE THREAD

**Issue by timwang-ai** [doronz88/pymobiledevice3#355]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by doronz88** [comment]
Yes
  https://github.com/doronz88/pymobiledevice3/blob/9a6f30e4a77d17d4910f198befac95bd077c6509/pymobiledevice3/lockdown.py#L216

**Comment by timwang-ai** [comment]
Very good. Does it support uploading p.12 files?

**Comment by doronz88** [comment]
p12 as in the private key format? i don't see how this relate

**Comment by timwang-ai** [comment]
Yes，That is, update the p.12 file and push it into the device and It supports remote connection. No, I want to use this to remotely execute voice_ Over function

**Comment by mike1023** [comment]
@doronz88 is there any way I can handle voiceover by this library? I mean simulate gestures to switch elements in the screen.

**Comment by doronz88** [comment]
I don't know of any lockdown relay allowing this. I think its only Bluetooth related. If you know otherwise, feel free to point me at the right relay

**Comment by mike1023** [comment]
@doronz88 Thanks. I searched a lot and got the same results, it seems no API can be found.
