### ISSUE TITLE
Read Carrier Lock information from device

### ISSUE THREAD

**Issue by Dantee296** [doronz88/pymobiledevice3#368]
Hi , is there any way to read this value using pymobiledevice3 project ?
apple introduced it in ios 14 

**Carrier Lock/Unlock Status retrieving logic is as follows:**

- libCommCenterCommandDrivers.dylib (\System\Library\Frameworks\CoreTelephony.framework\Support\) communicate with BasebandDriver and retrieves carrier lock status,
- CommCenter (\System\Library\Frameworks\CoreTelephony.framework\Support\) retrieves this value via libCommCenterBase,  deliver to CoreTelephony.
- CoreTelephony store this value as CTActivationPolicyState structure,
- GeneralSettingsUI retrieves this value and output to  Setting UI.

![image](https://user-images.githubusercontent.com/25308637/204190698-c075a648-daa5-4133-ab0e-50ebb44dc6da.png)

@doronz88

**Comment by doronz88** [comment]
I don't know of a lockdown or a MobileGestalt key to retrieve that. Maybe it can be read from one of the backup files

**Comment by Dantee296** [comment]
@doronz88 i looked into backup files couldn't find anything related to carrier lock info

although  i found some data in syslog but than it ll show it as "private" 
`<CTActivationPolicyState 0x2839df0d0, carrierLock=<private>`
is there any way i can have syslog show me this private information while printing logs ?

**Comment by doronz88** [comment]
https://github.com/EthanArbuckle/unredact-private-os_logs
