### ISSUE TITLE
SysLogService stuck when device disconnected when watch() is working on fetching logs

### ISSUE THREAD

**Issue by uncommonthinker** [doronz88/pymobiledevice3#389]
**Test environment**
- Ubuntu 20.04, OSX Ventura 13.0.1
- iPhone 7, iOS 15.7

```python
from pymobiledevice3.lockdown import LockdownClient
from pymobiledevice3.services.syslog import SyslogService
import time
import traceback

class LibimobileDeviceWrapper:

    def __init__(self):
        print("Libimbile Init")
        self.lockdown = None
        pass

    def lockdownInit(self):
        print("Lockdown Init")
        self.lockdown = LockdownClient()

    def checkLogs(self):
        try:
            print("checkLogs")
            if self.lockdown is None:
                print(f"lockdown is None {self.lockdown}")
                self.lockdownInit()
            print(f"lockdown {self.lockdown}")

            for line in SyslogService(lockdown=self.lockdown).watch():
                # just print all syslog lines as is
                print(line)

            print("====================================")
            print(f"====== Pairing Validation : {self.lockdown.validate_pairing()}===============")
            if self.lockdown.validate_pairing() == False:
                self.lockdown = None
                return -1

        except Exception as ex:
            print("Exception")
            print(traceback.print_exc())
            return -1

if __name__ == '__main__':
    libiobj = LibimobileDeviceWrapper()
    while libiobj.checkLogs() == -1:
        print("+")
        time.sleep(1)
```

**Describe the bug**
While the code is being executed and when the control is on the watch statement and logs are being printed, there is no way to break the watcher if the device is disconnected in between.

**To Reproduce**
Steps to reproduce the behavior, Run the attached code above

**Expected behavior**
An exception should be thrown stating device disconnected error

**Logs**
The above code generates relevant logs.

**Additional context**
The syslog.py under the pymobiledevice3 folder needs to check the device connected status in the while loop which can then raise an error which the user can handle at application level.

**Comment by doronz88** [comment]
Please verify the latest PR solves the issue.

Also:

- [`OsTraceService`](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/os_trace.py) is the much preferred relay which includes much more structured data. `SyslogService` is considered deprecated and I don't know of any client outside of `libimobiledevice` that uses it.
- I don't understand if you want the `LockdownClient` to validate the pairing. If so, it has an optional parameter just for that.
- Calling this class `LibimobileDeviceWrapper` is a bit funny, since there's nothing here that relies on `libimobiledevice`. This library is pure python and a completely standalone project

**Comment by uncommonthinker** [comment]
I know sounds funny but i was testing out some things until i came across this library. So please ignore the class names.

I will try the OSTraceService and test once. Thank you for your suggestions.

--
Thanks and Regards,
Abhishek Shah
+91-9867-246703

**Comment by uncommonthinker** [comment]
Thanks for your suggestions and references, I was able to use the OSTraceService and fetch the structured logs. Thanks
