### ISSUE TITLE
NoModule error for _queue

### ISSUE THREAD

**Issue by blacktop** [doronz88/pymobiledevice3#40]
Hi! This is an exciting project, looking forward to using heavily. 

I tried installing offline today and go the import error for `import _queue` and a quick search didn't find it referenced in any other files or defined anywhere. 

I was using latest 1.6.1

**Comment by matan1008** [comment]
Could you supply us with your python version (or the interpreter welcome message) please?

**Comment by matan1008** [comment]
Also, could you please try branch https://github.com/doronz88/pymobiledevice3/tree/hotfix/dvt-fix-queue-empty-exception

**Comment by matan1008** [comment]
Also, could you please try branch https://github.com/doronz88/pymobiledevice3/tree/hotfix/dvt-fix-queue-empty-exception

**Comment by blacktop** [comment]
It was python 3.6 on Ubuntu 18. I assume _queue is in Stdlib in a later version of python3?

I'll let you know as soon as I test it. Thank you for such a quick turnaround! 👍

**Comment by blacktop** [comment]
I tested latest master today and no longer that error! Thank you!!
