### ISSUE TITLE
Anyway to get a specific app size ?

### ISSUE THREAD

**Issue by sanidhya-saraswat** [doronz88/pymobiledevice3#415]

**Comment by doronz88** [comment]
I don't know of any explicit way to do so. I can think of two workarrounds:

- Using `pymobiledevice3 apps afc <bundle-identifier>` and summing the size of the items
- Using `pymobiledevice3 backup2 backup --full /path/to/backup` and summing the size of the items of the specific bundle identifier.

**Comment by sanidhya-saraswat** [comment]
Running the command:

`pymobiledevice3 apps afc --udid xxxxxxxxxxxxxxxx notion.id`

gives the following error:

`2023-03-03 16:43:52 sanidhya*con-XXXXXXXX pymobiledevice3.services.house_arrest[12430] ERROR notion.id: InstallationLookupFailed`

**Comment by doronz88** [comment]
sounds like you are not passing the correct bundle identifier. the device failed to search for it

**Comment by sanidhya-saraswat** [comment]
For Notion app, the bundle id is `notion.id`. Tried with other apps too.

**Comment by doronz88** [comment]
Not all applications allow this feature. Most of them don't. If you'll try to access their container data you'll see the following in syslog:

```
2023-03-08 08:17:48.246940 mobile_house_arrest{mobile_house_arrest}[820] <Notice>: <private> is not an allowed app bundle or extension: InstallationLookupFailed
```

In that case, you can only view this data using a backup.

**Comment by khrithik** [comment]
We can list the files(or folders) inside the directory `/private/var/containers/Bundle/Application/` where the Apps reside using the command `pymobiledevice3 developer dvt ls`. 
Is it possible to get the size of the directories being listed?

Also, we get App size data in Settings App - `General` -> `iPhone Storage`.
Is there any way we can access this data?

**Comment by doronz88** [comment]
You can get the information as shown in finder.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/19665147/232487005-ef4a63cc-16bc-4393-8f81-0959bb780276.png">

But I don't think this helps

**Comment by khrithik** [comment]
Needed to get the App size via code from the library. 
Not sure if we can get the data as the Setting app does(to get the app size).

if we can get the data similar to `pymobiledevice3 lockdown info` where we get data in the form of key-value pairs.
OR if we can get the size of the files/directories being listed by `pymobiledevice3 developer dvt ls`

**Comment by doronz88** [comment]
As I said, you only have what is available in Finder, which can be extracted from `lockdown info --all`. The `dvt ls` won't provide any other metadata regarding the files.

**Comment by khrithik** [comment]
Found a way to get the app size:
`options = {
    'ReturnAttributes': ['CFBundleIdentifier', 'StaticDiskUsage', 'DynamicDiskUsage'],
    'ApplicationType': 'User'
}`
`lockdown = LockdownClient()`
`InstallationProxyService(lockdown).lookup(options)`

`StaticDiskUsage` in the response is the app size as shown in the settings app.

**Comment by doronz88** [comment]
@khrithik96 nice one! I've created a PR to include this information on every `get_apps()`
