### ISSUE TITLE
Developer shell not working

### ISSUE THREAD

**Issue by sanidhya-saraswat** [doronz88/pymobiledevice3#416]
**Test environment**
- Host OS version: Montery 12.6.3
- Target device model and iOS version iPhone 13 and 16.2

**Describe the bug**
While running the following command

`pymobiledevice3 developer shell --udid xxxxxxxxxxxxxxxxxxxxxxxx
`

getting the following error

```
Usage: pymobiledevice3 developer shell [OPTIONS] SERVICE
Try 'pymobiledevice3 developer shell -h' for help.

Error: Missing argument 'SERVICE'.
```

**Comment by doronz88** [comment]
you are not using the service as described. the command receives a service name meant for your to investiagte, such as: [com.apple.dt.fetchsymbols](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/services/dtfetchsymbols.py)
