### ISSUE TITLE
Unintended wireless interactions

### ISSUE THREAD

**Issue by Hoangdus** [doronz88/pymobiledevice3#426]
**Test environment**
- macOS 12.6.3 Monterey MacBook Pro 14.1
- iPad mini 6 iPadOS 15.2 

**Describe the bug**
Full interactions with iPad that supports sidecar without having sync over Wi-Fi on 

**To Reproduce**
1. Grab an iPad that supports sidecar and login with the same Apple ID as the Mac that also supports sidecar and make sure sync over Wi-Fi is off in finder 
2. After that you could do basically everything from getting the device name to shutdown and enter recovery

**Expected behavior**
Nothing should happened because sync over Wi-Fi is off and the device isn't connected with USB

**Logs**

**Additional context**
I was just playing around with the lib in python to print out the battery capacity in a loop and I turn on my iPad to check something and I turn over to my MacBook and I saw my iPad battery capacity got printed out the screen

**Comment by Hoangdus** [comment]
Oops forgot to remove the log placeholder

**Comment by doronz88** [comment]
I'm not sure I understand the case, but can you verify the `wifi-connections` feature is really off?

```shell
# print it
pymobiledevice3 lockdown wifi-connections

# set to off
pymobiledevice3 lockdown wifi-connections off
```

**Comment by Hoangdus** [comment]
So I just checked and it was on so I turned that off and the problem is gone now

**Comment by Hoangdus** [comment]
Don't know that it's on by default 
I thought it was a bug. Thanks

**Comment by Hoangdus** [comment]
Weird that it's on by default for supported iPad
