### ISSUE TITLE
list-devices appears to be unsupported

### ISSUE THREAD

**Issue by redromnon** [doronz88/pymobiledevice3#445]
**Test environment**
- Host OS version - Pop OS 22.04 LTS (Linux)
- Target device model and iOS version - iPhone SE 2 (iOS 16.4.1)

**Describe the bug**
`list-devices` doesn't seem to be supported, while it is mentioned in the readme. I'm not aware if this argument was discarded.

**To Reproduce**
1. Run `python -m pymobiledevice3 list-devices`
2. See error saying `Error: No such command 'list-devices'.`

**Expected behavior**
The command should display a list of connected iOS devices.

**Logs**
```
Usage: python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...
Try 'python -m pymobiledevice3 -h' for help.

Error: No such command 'list-devices'.
```

**Additional context**

**Comment by doronz88** [comment]
@redromnon thanks of the issue report! We refactored all CLI commands to be in the format of: `protocol command params`, and as such, this command was changed to `usbmux list`. This fix was just merged.

**Comment by redromnon** [comment]
Thanks!
