### ISSUE TITLE
Unable to list files in directory 'DiagnosticLogs/sysdiagnose' | `READ_DIR failed with status: PERM_DENIED`

### ISSUE THREAD

**Issue by StephenGemin** [doronz88/pymobiledevice3#464]
**Test environment**
- Windows 10
- iPhoneXR, iOS 16.5, model MRY42
  - this phone is located in India (not sure if that makes any difference)
- pymobiledevice3 == 1.42.4

**Describe the bug**
***This issue is only observed on this particular device.  I'm at a loss for the best approach to debug and solve this issue.***

On sysdiagnose collection, the following error occurs. I've included a stacktrace at the bottom.
`pymobiledevice3.exceptions.AfcException: [Errno PERM_DENIED] opcode: READ_DIR failed with status: PERM_DENIED`

**To Reproduce**
Pre-condition:  modify device settings to trigger analytics by double tapping the assistive touch icon

1. Double tap the assistive touch icon
2. Run the following pseudo code.
```python
# wrapper class
class CrashReports:
  def __init__(self, service):
    self.service = service
  ...

crm = CrashReportsManager(LockdownClient(serial="00008020-000A6D5A0220802E"))
crash_reports = CrashReports(crm)
files = crash_reports.service.ls('DiagnosticLogs/sysdiagnose')
# in stacktrace below, the above line appears as
# files = self.service.ls("/DiagnosticLogs/sysdiagnose")
```

**Expected behavior**
Able to read the files within the "DiagnosticLogs/sysdiagnose" directory

**Logs**
The following log line indicates pairing was successful, the trust popup has been handled from the phone.
`[2023-06-08 15:02:06.673851] DEBUG: pymobiledevice3.lockdown: Using usbmuxd pair record for identifier: 00008020-000A6D5A0220802E`

Stacktrace
```
  ...
  File "C:\Python37\lib\site-packages\phone_lib\ios\crash_reports.py", line 95, in collect_sysdiagnose
    local_path = self.get_new_sysdiagnose(timeout=timeout, local=local)
  File "C:\Python37\lib\site-packages\phone_lib\ios\crash_reports.py", line 156, in get_new_sysdiagnose
    f_completed = self._in_progress_sysdiagnose(exit_time)
  File "C:\Python37\lib\site-packages\phone_lib\ios\crash_reports.py", line 167, in _in_progress_sysdiagnose
    files = self.service.ls("/DiagnosticLogs/sysdiagnose")
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\crash_reports.py", line 55, in ls
    return list(self.afc.dirlist(path, depth))[1:]  # skip the root path '/'
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\afc.py", line 518, in dirlist
    for folder, dirs, files in self.walk(root):
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\afc.py", line 514, in walk
    for walk_result in self.walk(posixpath.join(dirname, d)):
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\afc.py", line 501, in walk
    for fd in self.listdir(dirname):
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\afc.py", line 362, in listdir
    data = self._do_operation(afc_opcode_t.READ_DIR, afc_read_dir_req_t.build({'filename': filename}))
  File "C:\Python37\lib\site-packages\pymobiledevice3\services\afc.py", line 569, in _do_operation
    raise exception(f'opcode: {opcode} failed with status: {status}', status)
pymobiledevice3.exceptions.AfcException: [Errno PERM_DENIED] opcode: READ_DIR failed with status: PERM_DENIED
```

**Additional context**
None

**Comment by doronz88** [comment]
- Looks like bad path handling on windows. I'll look it at when I have a windows machine to test it with
- Try to `cd` into the directory first and then `ls`

**Comment by StephenGemin** [comment]
> * Looks like bad path handling on windows. I'll look it at when I have a windows machine to test it with
> * Try to `cd` into the directory first and then `ls`

I'll try that suggestion.

It is only for that particular device.  The same code is used on other Windows setups, different phone models, different OS versions, etc.
Are there any logs you could recommend collecting that might help debug the issue further?

**Comment by doronz88** [comment]
Unfortunately I wasn't able to reproduce this error on my windows machine.
Can you provide syslog lines while this happens?

```shell
python3 -m pymobiledevice3 syslog live -mi crash
```

**Comment by StephenGemin** [comment]
Our team has reported this issue happening again.  Thank you for the feedback.  I'll make sure if reporting this issue again syslog will be provided.
