### ISSUE TITLE
ios 17 | cant change location despite mounting personal image

### ISSUE THREAD

**Issue by Geczy** [doronz88/pymobiledevice3#471]
**Test environment**
- macos 13.4
- iphone 13 pro max 17

 ```sh
 python3 -m pymobiledevice3 mounter mount-personalized /Users/mgates/Desktop/022-15533-053.dmg /Users/mgates/Desktop/022-15533-053.dmg.trustcache /Users/mgates/Desktop/BuildManifest.plist

2023-06-15 11:58:41 M7V6KFVVNL pymobiledevice3.cli.mounter[81858] ERROR Given image was already mounted

➜  ~ pymobiledevice3 developer simulate-location set 0 0
Readline features including tab completion have been disabled because
no supported version of readline was found. To resolve this, install
pyreadline3 on Windows or gnureadline on Linux/Mac.

2023-06-15 11:58:46 M7V6KFVVNL pymobiledevice3.__main__[81865] ERROR Failed to access an invalid lockdown service, possibly from DeveloperDiskImage.dmg or a Cryptex. You may try: python3 -m pymobiledevice3 mounter auto-mount
```

huh ? it says personalized image already mounted, but then i cant change location because it says no image mounted?

_Originally posted by @Geczy in https://github.com/libimobiledevice/libimobiledevice/issues/1452#issuecomment-1593427096_

**Comment by doronz88** [comment]
The simulate location and all other developer relays have been refactored to be over remotexpc. Still working on it

**Comment by GreystoneRDFirmware** [comment]
Hi @doronz88,

Thanks for your hard work.
iOS17 can mount successfully. "pymobiledevice3.cli.mounter[3067] INFO Personalized image mounted successfully".
But I can not run the screenshot command. The log is below. "__main__[3088] ERROR Failed to access an invalid lockdown service, possibly from DeveloperDiskImage.dmg or a Cryptex. You may try: python3 -m pymobiledevice3 mounter auto-mount"
Please advise!

**Comment by doronz88** [comment]
The screenshot relay is yet another developer service that requires rework.
In general, everything in the `developer` category will work only if the old DeveloperDiskImage is mounted.
We'll probably add a new "personalized" category for the new personalized disk image once we finished the development. Apple has completely reworked this so it takes time to figure out how to implement everything yet again.

**Comment by truonggiang0710** [comment]
> The screenshot relay is yet another developer service that requires rework.
> In general, everything in the `developer` category will work only if the old DeveloperDiskImage is mounted.
> We'll probably add a new "personalized" category for the new personalized disk image once we finished the development. Apple has completely reworked this so it takes time to figure out how to implement everything yet again.

Have you completed this, men?

**Comment by Karl0226** [comment]
I use remoteXpc but I receive this data
SettingsFrame(stream_id=0, flags=[]): settings={3: 100, 4: 1048576}
WindowUpdateFrame(stream_id=0, flags=[]): window_increment=983041
SettingsFrame(stream_id=0, flags=['ACK']): settings={}
HeadersFrame(stream_id=1, flags=['END_HEADERS']): exclusive=False, depends_on=0, stream_weight=0, data=None
RstStreamFrame(stream_id=1, flags=[]): error_code=5
None closing stream 1 on port 58783

what should I do

**Comment by doronz88** [comment]
@Karl0226 What command did you use?

Also there are a lot of changes so it will take some time. I can put you in the loop if you are willing to help with the implementation.

**Comment by Karl0226** [comment]
@doronz88  I use "remote create-listener"
When doing "self.peer_info = self.service.receive_response" I will receive RstStreamFrame

**Comment by doronz88** [comment]
Then `remoted` is probably killing your socket. 
Try stopping it before:

```shell
sudo pkill -SIGSTOP remoted
```

**Comment by Karl0226** [comment]
I used the "sudo pkill -SIGSTOP remoted" command. I saw no change in Activity Monitor. I also tried turning remoted off on Activity Monitor, but the remoted process will restart

**Comment by Karl0226** [comment]
@doronz88 I got that!

**Comment by doronz88** [comment]
I think I'll soon publish a post explaining how it all works, where we are now and what's left to do so others can maybe find a way to join the effort. There's quite a lot for a single person

**Comment by doronz88** [comment]
Location setting is now officially supported - starting at [v2.2.0](https://github.com/doronz88/pymobiledevice3/releases/tag/v2.2.0)

**Comment by truonggiang0710** [comment]
> Location setting is now officially supported - starting at [v2.2.0](https://github.com/doronz88/pymobiledevice3/releases/tag/v2.2.0)

How about screenshot @doronz88 ?

**Comment by doronz88** [comment]
Also already supported and over DVT:
```shell
pymobiledevice3 developer dvt screenshot /path/to/screenshot.png --rsd HOST PORT
```

**Comment by truonggiang0710** [comment]
Thanks @doronz88

**Comment by imvab** [comment]
@doronz88 can you please define HOST and PORT? What values needs to be passed there?

**Comment by imvab** [comment]
Found the solution for it #502

**Comment by argunv** [comment]
sudo pymobiledevice3 developer dvt simulate-location set --udid {udid} -- x y 

The location of the devices did not change after using this command. (I looked in the Maps application). The devices are iPhone 14, and iPad Pro 11' (4th Gen). All devices are updated to the latest version.

**Comment by Fidetro** [comment]
> sudo pymobiledevice3 developer dvt simulate-location set --udid {udid} -- x y
> 
> The location of the devices did not change after using this command. (I looked in the Maps application). The devices are iPhone 14, and iPad Pro 11' (4th Gen). All devices are updated to the latest version.

Starting at iOS 17.0,
```
sudo python3 -m pymobiledevice3 remote start-tunnel
pymobiledevice3 developer dvt simulate-location set --rsd HOST PORT -- x y
```
