### ISSUE TITLE
Where can I get the HOST and PORT in this parameter?

### ISSUE THREAD

**Issue by gimguang** [doronz88/pymobiledevice3#502]
Where can I get the HOST and PORT in this parameter?
pymobiledevice3 developer dvt simulate-location set --rsd HOST PORT -- x y

**Comment by doronz88** [comment]
Please look at:
https://github.com/doronz88/pymobiledevice3/blob/master/misc/RemoteXPC.md#reusing-the-macos-trusted-tunnel

I believe you also require either Instruments or Xcode to be open in order for the tunnel to be established.
I'll add this info in the main README.

**Comment by HackHarry** [comment]
Hello, is there any way to get host and port on windows  or linux?

**Comment by doronz88** [comment]
Not currently. Windows will take much longer to implement (if ever).
The linux currently even has difficulity establishing connection over the USB Ethernet

**Comment by HackHarry** [comment]
Got it. Thanks a lot.
