### ISSUE TITLE
Detect replacement part!

### ISSUE THREAD

**Issue by truonggiang0710** [doronz88/pymobiledevice3#519]
Is the library capable of detecting replacement parts on iDevices?

**Comment by doronz88** [comment]
Not that I know of. Possibly by querying MobileGestalt or some other exported API

**Comment by truonggiang0710** [comment]
Thank @doronz88 !

**Comment by truonggiang0710** [comment]
Hello @doronz88 , I found 4Tools can do this. Link to download the tool https://www.i4.cn.
But I don't know how the tool do that.
Can you help check ?
Thank!

**Comment by doronz88** [comment]
I don't know this software, nor can I read stuff from it. Can you point at non-chinese software?

**Comment by truonggiang0710** [comment]
> I don't know this software, nor can I read stuff from it. Can you point at non-chinese software?

Yes, it is Chinese software. Do you have any means to capture traffic data and identify the service within the software?

**Comment by doronz88** [comment]
You could try using `usbmux_sniff.sh` in the `misc` subdir just to tell which lockdown service is used.
If this is for iOS 17 over RSD, you can instead just sniff the tunnel.

**Comment by truonggiang0710** [comment]
> You could try using `usbmux_sniff.sh` in the `misc` subdir just to tell which lockdown service is used.
> If this is for iOS 17 over RSD, you can instead just sniff the tunnel.

How do I use it? Could you advise?

**Comment by doronz88** [comment]
On second thought, I think the easiest way for you would be:

```shell
sudo ifconfig XHC20 up
```

- Sniff `XHC20` using wireshark to generate a `.pcap`
- Use `misc/extract_plist_from_pcaps.py` to extract all the request/responses from the `.pcap`

**Comment by truonggiang0710** [comment]
> On second thought, I think the easiest way for you would be:
> 
> ```shell
> sudo ifconfig XHC20 up
> ```
> 
>  * Sniff `XHC20` using wireshark to generate a `.pcap`
> * Use `misc/extract_plist_from_pcaps.py` to extract all the request/responses from the `.pcap`

OK. I try now.

**Comment by truonggiang0710** [comment]
> > On second thought, I think the easiest way for you would be:
> > ```shell
> > sudo ifconfig XHC20 up
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Sniff `XHC20` using wireshark to generate a `.pcap`
> > * Use `misc/extract_plist_from_pcaps.py` to extract all the request/responses from the `.pcap`
> 
> OK. I try now.

I failed at first command.
sudo ifconfig XHC20 up
ifconfig: interface XHC20 does not exist

tcpdump -D            
1.en0 [Up, Running]
2.llw0 [Up, Running]
3.utun0 [Up, Running]
4.utun1 [Up, Running]
5.utun2 [Up, Running]
6.en4 [Up, Running]
7.en7 [Up, Running]
8.lo0 [Up, Running, Loopback]
9.bridge0 [Up, Running]
10.en2 [Up, Running]
11.en3 [Up, Running]
12.en1 [Up]
13.gif0 [none]
14.stf0 [none]
15.p2p0 [none]
16.awdl0 [none]

Do you have any way to resolve it?

**Comment by doronz88** [comment]
In general, you want to sniff the USB traffic. I don't know which interface your mac/pc is using

**Comment by truonggiang0710** [comment]
> In general, you want to sniff the USB traffic. I don't know which interface your mac/pc is using

I cannot capture USB traffic using WireShark, but I can run usbmux_sniff.sh. What should be my next step?

**Comment by doronz88** [comment]
That depends on how the software is communicating the the device. Only real USB sniffing can detect all methods. In general, I would recommend making the Wireshark sniffing work.
