### ISSUE TITLE
FEATURE REQUEST: audio forword 

### ISSUE THREAD

**Issue by Blue-FatMan** [doronz88/pymobiledevice3#521]
Hello, Will develop an audio forwarding function？I am testing the live broadcast of the monitor in iphone, so i want get audio from iphone.
Thanks.

**Comment by doronz88** [comment]
Do you have reason to believe its supposed to be possible over USB/WiFI without any extras installed? Can you send a link?

**Comment by Blue-FatMan** [comment]
So far, I haven't seen it
