### ISSUE TITLE
Cant use simulate-location command on iOS 17.0

### ISSUE THREAD

**Issue by UrDone4** [doronz88/pymobiledevice3#526]
**Test environment**
- Host OS version: macOS 13.5, Python 3.9.17 (VENV)
- Target device model and iOS version: iPhone 11 Pro, iOS 17

**Describe the bug**
When trying to run the command: 

sudo pymobiledevice3 developer simulate-location set --rsd fd2b:a882:f372::1 59362 -- 30.86863 -94.83988

I receive this error: 
pymobiledevice3.__main__[17506] ERROR Failed to access an invalid lockdown service, possibly from DeveloperDiskImage.dmg or a Cryptex. You may try: python3 -m pymobiledevice3 mounter auto-mount

If I try to run the suggested command: python3 -m pymobiledevice3 mounter auto-mount

I receive: 
pymobiledevice3.cli.mounter[17543] ERROR DeveloperDiskImage already mounted

Other commands work fine (such as: pymobiledevice3 syslog live -m SpringBoard)

**To Reproduce**
1. Run command to get rsd: sudo python3 -m pymobiledevice3 remote start-quic-tunnel
2. Run command for simulate-location

Any help would be appreciated!

**Comment by doronz88** [comment]
As part of iOS 17, Apple moved the simulate-location functionality into the DVT.
The new API will be:
```shell
sudo pymobiledevice3 developer dvt simulate-location set --rsd fd2b:a882:f372::1 59362 -- 30.86863 -94.83988
```

**Comment by UrDone4** [comment]
Thanks for the quick response. This solved it for me.

**Comment by gastonmorixe** [comment]
I have beta iOS17 beta 6 and the location is set for a brief of less than a second and reverted back to the real hardware.

**Comment by doronz88** [comment]
@gastonmorixe please verify if this fixes your issue
https://github.com/doronz88/pymobiledevice3/pull/539/files
