### ISSUE TITLE
'ERROR: Invalid valid value for --rsd: 2 values are required, but 25 were given'

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#532]
**Steps:** 

1. Install any version of pymobiledevice3 (v2.2.0 to latest)
2. Execute command `pymobiledevice3 developer dvt launch com.apple.mobilesafari --udid <UDID_OF_DEVICE>`

**Actual:** Error message is displayed `'ERROR: Invalid valid value for --rsd: 2 values are required, but 25 were given'`
**Expected:** Should open safari and return process id

**Notes:**
1. Same command works if --udid is not provided
2. Same command works with pymobiledevice3==2.0.4
3. In all the above cases and scenarios same iPhone device was used

**Comment by prashant1507** [comment]
This should be considered as CRITICAL issue as the latest version will not work for automating multiple iPhone devices
Thanks

**Comment by doronz88** [comment]
@prashant1507 thanks for the heads up! Checkout [v2.4.0](https://github.com/doronz88/pymobiledevice3/releases/tag/v2.4.0) for the fix (and several other features)

**Comment by prashant1507** [comment]
hi,
its working now but i see below warning (not sure will it be affect or not)
On running command `pymobiledevice3 developer dvt launch com.apple.mobilesafari --udid <UDID_OF_DEVICE>` i see below warning 

`create_core_device_tunnel_service failed to be imported. Some feature may not work`

**Comment by doronz88** [comment]
That's okay, this just mean your platform won't support the RSD feature on ios17. This is only reported as a warning.
That's currently only supported on macOS with the `openssl@3` homebrew package installed.

**Comment by prashant1507** [comment]
Thanks 👍
