### ISSUE TITLE
Quic Tunnel Bugs

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#557]
I'm using MacBook pro (M1) with MacOS Ventura and testing on iPhone14 with iOS17 beta.

I encountered some issues when running:
```
sudo python3 -m pymobiledevice3 remote start-quic-tunnel
```

- [x] [utils.py](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/remote/utils.py) -> `_get_remoted_process()` - need to catch `psutil.NoSuchProcess` in addition to `psutil.ZombieProcess`. It used to work without it before, but after playing with the library for a while it became a necessity to add this catch (and I'm not sure about the reason...)
- [x] Starting a tunnel, connecting an *unpaired* device and then rejecting the pairing causes an exception. It's probably best to add some handling for pairing rejection:
   ```python
   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 512, in _receive_pairing_data
   return self._receive_plain_response()['event']['_0']['pairingData']['_0']['data']
   KeyError: 'pairingData'
   ```
- [ ] Starting a tunnel, connecting an *unpaired* device, then physically disconnecting the device (before confirming trust) - causes the tunnel to hang. I would expect some kind of exception to be raised because the connection is physically closed... but it just hangs. It hangs at [remotexpc.py](https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/remote/remotexpc.py)  -> `_recvall()` -> `sock.recv` which is kind of weird since the connection is theoretically dropped. Also, I believe this function should handle `recvall` the same way as `service_connection.py`:
   ```python
   if chunk is None or len(chunk) == 0:
       raise ConnectionAbortedError()
   ```
   Though since it just hangs this is not an issue (yet).

**Comment by doronz88** [comment]
I handled the first two issues you mentioned (#558 - please verify), but failed to find out why the `socket.recv()` never returns. I think the only option for the user to handle this programatically is to set a timeout on this socket.

**Comment by vToMy** [comment]
Works great.
Setting a timeout is problematic since it can also trigger while waiting for consent.
Probably the only solution would be to query if the device is connected in parallel and then interrupt the procedure.

**Comment by doronz88** [comment]
So what do you suggest? Closing this issue after the merge and let the people needing this to monitor it separately?

**Comment by vToMy** [comment]
Yeah we can close the issue. The first 2 were the critical ones.
Thanks!
