### ISSUE TITLE
will Access accessibility inspector features be developed

### ISSUE THREAD

**Issue by timwang-ai** [doronz88/pymobiledevice3#561]
Hello, will Access accessibility inspector features be developed? I'm testing it on my iPhone, thanks.

**Comment by doronz88** [comment]
They have already been:
```shell
pymobiledevice3 developer accessibility
```

**Comment by timwang-ai** [comment]
How to enable narration in accessibility

**Comment by doronz88** [comment]
Do you mean the one mentioned in #355 ?

**Comment by timwang-ai** [comment]
Very good.
