### ISSUE TITLE
Need help supporting iOS 17

### ISSUE THREAD

**Issue by morellexf13** [doronz88/pymobiledevice3#562]
Hi doronz, 
I'm working on supporting iOS 17 on my product and currently facing the following:

Basically, I have this function that handles a monitor to check device resources each second

```python
def monitor_thread(self):
        while base_profiler.running:
            logger.debug(f'Get a new lockdown in {self.__class__.__name__} object.')
            lockdown = self.device.get_lockdown()
            try:
                with DvtSecureSocketProxyService(lockdown=lockdown) as dvt:
                    self.monitor_logic(dvt)
            except Exception as exc:
                logger.exception(f'An error occurred executing {self.__class__.__name__}. {exc}')
```

The problem now is that iOS 17 throws an error probably due to the new mechanism to connect the device to the computer.
Based on the README and new changes on pymobiledevice code I'm trying to create this logic: https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/cli/remote.py#L68. As far as I understand I need to get the device RSD interface and use that information to generate an address and a port to create a comunication tunnel but I can't even list the devices using:

```python
def get_device_list() -> List[RemoteServiceDiscoveryService]:
    result = []
    with stop_remoted():
        for address in get_remoted_addresses():
            rsd = RemoteServiceDiscoveryService((address, RSD_PORT))
            rsd.connect()
            result.append(rsd)
    return result
```

because **stop_remoted** raises an **AccessDeniedError**.

-----------------------------------------------------------------------------------------------------------------------
On the other hand... assuming that I currently have the address and port to use in my code with the create_using_remote function:

<img width="1131" alt="Captura de pantalla 2023-09-18 a la(s) 14 57 45" src="https://github.com/doronz88/pymobiledevice3/assets/73654994/3d2adfc3-4533-4f99-9b8a-b02bec294912">

I have the following error (I don't know what that means):
<img width="1285" alt="Captura de pantalla 2023-09-18 a la(s) 14 59 34" src="https://github.com/doronz88/pymobiledevice3/assets/73654994/f9854fc9-6412-469a-b47a-072dee80d597">

Any hint on how can I monitor my resources using iOS 17 now that the comunication between computer - device has changed? Thanks!

**Comment by doronz88** [comment]
- The `stop_remoted` requires `root` permissions in order to stop a system process (`remoted`)
- The error you are getting is from wrong usage of the API. Connecting via RSD isn't using `usbmuxd`. Instead, look at the following example: https://github.com/doronz88/pymobiledevice3#python-api

**Comment by morellexf13** [comment]
I guess my logic for iOS >= 17 should be something like this then:

```python
try:
    host = 'fd30:9355:b54e::1'
    port = 60458
    with RemoteServiceDiscoveryService((host, port)) as rsd:
        with DvtSecureSocketProxyService(rsd) as dvt:
            self.monitor_logic(dvt)
except Exception as exc:
    logger.exception(f'An error occurred executing {self.__class__.__name__}. {exc}')
```

Now I need to figure out how to obtain the host and port programatically if that requires root permissions 🤔

**Comment by doronz88** [comment]
Correct. You could make this a service which runs in the background as root or make it into a standalone executable with `setuid`

**Comment by morellexf13** [comment]
> I guess my logic for iOS >= 17 should be something like this then:
> 
> ```python
> try:
>     host = 'fd30:9355:b54e::1'
>     port = 60458
>     with RemoteServiceDiscoveryService((host, port)) as rsd:
>         with DvtSecureSocketProxyService(rsd) as dvt:
>             self.monitor_logic(dvt)
> except Exception as exc:
>     logger.exception(f'An error occurred executing {self.__class__.__name__}. {exc}')
> ```

Hi @doronz88, 
When I use the above logic I get this error **almost** all times:

```
[2023-09-23 10:11:51,204] [ERROR] generic_monitor.py -> monitor_thread line:41 An error occurred executing IOSPidMonitor. Got RstStreamFrame(stream_id=1, flags=[]): error_code=5
Traceback (most recent call last):
  File "/Users/juan/Documents/Developer/apptim-agent/apptim_agent/profiler/ios/monitors/generic_monitor.py", line 29, in monitor_thread
    with RemoteServiceDiscoveryService((host, port)) as rsd:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 90, in __enter__
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 37, in connect
    self.peer_info = self.service.receive_response()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/remotexpc.py", line 88, in receive_response
    frame = self._receive_next_data_frame()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymobiledevice3/remote/remotexpc.py", line 155, in _receive_next_data_frame
    raise StreamClosedError(f'Got {frame}')
pymobiledevice3.exceptions.StreamClosedError: Got RstStreamFrame(stream_id=1, flags=[]): error_code=5
```

What could be the problem here?

Edit: I have added a retry logic 

```python
try:
    if self.device.version_is_17_or_greater():
        for attempt in range(1, max_retries + 1):
            host, port = ("fd56:d87a:8e52::1", 54336)
            with RemoteServiceDiscoveryService((host, port)) as rsd:
                with DvtSecureSocketProxyService(rsd) as dvt:
                    self.monitor_logic(dvt)
except StreamClosedError as exc:
    logger.warning(f'Connection attempt {attempt} failed: {exc}')
    if attempt < max_retries:
        logger.info(f'Retrying in {retry_delay} seconds...')
        time.sleep(retry_delay)
    else:
        logger.error('Max retries reached. Unable to establish a connection.')
        break
except Exception as exc:
    logger.exception(f'An error occurred executing {self.__class__.__name__}. {exc}')
```

and based on logs, apparently always fails at least 1 time:
```
[2023-09-23 10:28:07,431] [WARNING] generic_monitor.py -> monitor_thread line:46 Connection attempt 1 failed: Got RstStreamFrame(stream_id=1, flags=[]): error_code=5
[2023-09-23 10:28:07,431] [INFO] generic_monitor.py -> monitor_thread line:48 Retrying in 5 seconds...
```
