### ISSUE TITLE
Could you please create a PR to libimobiledevice to fix this problem in iOS17?

### ISSUE THREAD

**Issue by panderman** [doronz88/pymobiledevice3#563]
libimobiledevice cannot mount dmg on iOS 17. You have solved it using python. Can you push a PR to libimobiledeivce to solve this problem? Thank you very much

**Comment by doronz88** [comment]
I'm not planning to re-implement everything in other technologies. If you need help implementing it yourself and having questions regarding the HOWs and WHYs feel free to ask on either our [Discussions board](https://github.com/doronz88/pymobiledevice3/discussions) or the [Discord server](https://discord.gg/52mZGC3JXJ).
