### ISSUE TITLE
Changing location with iOS17 not working on my machine

### ISSUE THREAD

**Issue by chkhu** [doronz88/pymobiledevice3#580]
**👉My environment**

- Macbook Pro 2020, MacOS Ventura 13.5.2 (22G91)
- iPhone 12 Pro Max, iOS17.0

**👉Description of the problem**

I followed the instructions and have:
- installed pymobiledevice3
- created trusted tunnels

<img width="350" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/109655311/5476c39c-03ed-45f5-9918-d1e60b7066df">
<br></br>
<img width="400" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/109655311/d5155e25-c596-457f-bec6-4b7f16531156">

After that I tried to simulate location for my iphone, so I ran:
```
pymobiledevice3 developer dvt simulate-location set --rsd fde4:8c4e:a9ee::1 61143 -- 0 0
```
The result:

<img width="544" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/109655311/3531076f-1049-4d09-8614-42097f168288">

When I hit RETURN, it ended. And I checked my iphone, the location was not changed. 
Should I worry about the message shown here?
```
Readline features including tab completion have been disabled because
no supported version of readline was found. To resolve this, install
pyreadline3 on Windows or gnureadline on Linux/Mac.
```
(I've tried to install gnureadline on my mac but it sugguests there's only a ‘readline‘ available. )

<img width="543" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/109655311/f2524a92-1d4e-4c3e-8e79-4070210fd74a">

<br></br>
**👉Need for help**

What went wrong? What should I do to fix it?
Is the latitude and longitude coordinates required to be in specific form? If so, what is it?

**Comment by doronz88** [comment]
The message is not really a problem. Maybe the message wasn't clear enough - but it should simulate location while the process is running - so hitting RETURN would simply stop it from doing so.

**Comment by chkhu** [comment]
You're right. The location was changed before i hit RETURN.
thx
