### ISSUE TITLE
iOS 17 devices missing com.apple.xcode.developerdomain DeveloperStatus

### ISSUE THREAD

**Issue by torarnv** [doronz88/pymobiledevice3#585]
**Test environment**
macOS 14
iPhone 15 Pro

**Describe the bug**
Prior to iOS 17, devices report a dictionary for `pymobiledevice3 lockdown get com.apple.xcode.developerdomain` with `DeveloperStatus`. This is now empty.

**Expected behavior**
A way to see the developer status for a device.

**Comment by doronz88** [comment]
This was never the official way to do so. Instead:

```shell
pymobiledevice3 amfi developer-mode-status
```

**Comment by torarnv** [comment]
Thanks!
