### ISSUE TITLE
Open URL in Safari Browser

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#588]
# Feature Request

Using current version of pymobiledevice3, I am able to open URL using Automation mode of Safari

Is it possible to open URL in normal safari mode ?

**Comment by doronz88** [comment]
Yes, through javascript.
Try it:

```shell
pymobiledevice3 webinspector js-shell
```

Then:

```javascript
window.location = 'http://github.com'
```

**Comment by prashant1507** [comment]
thank you
