### ISSUE TITLE
starting quic-tunnel without sudo

### ISSUE THREAD

**Issue by martindasilva404** [doronz88/pymobiledevice3#597]
Adding a <user_account> to the sudoers file to eliminate using sudo when starting a quic-tunnel doesn't work. I need to run this on multiple iOS devices within a script without entering passwords.

sudoers file:
<user_account> ALL=(ALL) NOPASSWD: /usr/local/bin/pymobiledevice3

output:
pymobiledevice3 remote start-quic-tunnel
pymobiledevice3.__main__[41015] ERROR This command requires root privileges. Consider retrying with "sudo".

Is there anyway to make this work?

**Comment by doronz88** [comment]
From my understanding for this modification, you'll need to make sure the user account is root and still run the command via sudo - it just won't request a password

**Comment by martindasilva404** [comment]
@doronz88 got it. thank you so much
