### ISSUE TITLE
--no-color option for "remote start-quic-tunnel"

### ISSUE THREAD

**Issue by blakegonzales** [doronz88/pymobiledevice3#603]
Please add a "--color / --no-color" option to "remote start-quic-tunnel" like you already have for "remote rsd-info".

I have a bash script I've written to pull out the "--rsd host port" text so I can use it as arguments for another pymobiledevice3 session.  It works, but all of the color escape codes are a pain to filter out.

OR, is there a simpler way to pull out the "--rsd host port" info that I haven't found.  That would be even better!

Thanks!

**Comment by doronz88** [comment]
Thanks for your feedback! I just added a `--script-mode` option which will only show the `HOST PORT` parameters for a simple parsing. Please update and close the issue if this does provide all your needs.

**Comment by blakegonzales** [comment]
Thanks for the `--script-mode` addition!  This is very helpful and made my scripts so much cleaner. 😀

**I'm curious if anyone has a better way to do this.**

I first run this script to open then tunnel.

> #/bin/bash
> TEMPFILE=/tmp/simulate-location-rsd.txt
> sudo script -q -F $TEMPFILE pymobiledevice3 remote start-quic-tunnel --script-mode

Then I open up another terminal window and run this script:

> #/bin/bash
> TEMPFILE=/tmp/simulate-location-rsd.txt
> pymobiledevice3 developer dvt simulate-location set --rsd \`cat $TEMPFILE | cut -w -f1,2\` -- $1 $2

Any thoughts from the community?

**Comment by doronz88** [comment]
I think this should be either asked the in the discussion board or the discord channel
