### ISSUE TITLE
The get_time_config method in core_profile_session_tap.py is not adapted for iOS17+ ；

### ISSUE THREAD

**Issue by yixiangboy** [doronz88/pymobiledevice3#629]
The get_time_config method in core_profile_session_tap.py is not adapted for iOS17+ ；
usecs_since_epoch and timezone_ for iOS17+ is None

**Comment by doronz88** [comment]
I just added a PR to resolve this issue and in general solve a much greater issue of associating all RSD connections with their corresponding lockdown connections
