### ISSUE TITLE
"remote start-quic-tunnel --script-mode" is again displaying colored text

### ISSUE THREAD

**Issue by blakegonzales** [doronz88/pymobiledevice3#642]
`--script-mode` now has a couple of issues:

(1) it outputs text unrelated to RSD hostname and port
(2) this new text has color codes

Can you go back to just a simple output of the RSD hostname and port number?

Thanks!

**Comment by doronz88** [comment]
This text goes to stderr and not stdout. Is that still a problem?

**Comment by blakegonzales** [comment]
That helps to know what goes to `stderr` and `stdout`.

So my problem now is that `stdout` must be getting buffered, as rsd host/port aren't written to file until after the remote tunnel process is closed.  Obviously, that it too late for the data to be useful.

For instance,

```
% sudo pymobiledevice3 remote start-quic-tunnel --script-mode 1> rsd.txt
2023-11-01 13:40:54 Blakes-MBP pymobiledevice3.cli.remote[57074] INFO tunnel created
```

`cat rsd.txt` is empty at this point.

------------------

Once I `Ctrl-C` I get this on the console
```
^C
Aborted!
```

and `cat rsd.txt` shows `fd13:f8d8:b9f0::1 61529`

**Comment by doronz88** [comment]
Can you verify #646 resolves the issue?
Also, I believe the [new tunneld feature](https://github.com/doronz88/pymobiledevice3#tunneld) should provide a much better experience.

**Comment by blakegonzales** [comment]
`tunneld` rocks!  That makes this whole process so much easier.  Thank you 😊.

Not sure how to test #646 until it's been released, but once it is I'll be happy to provide feedback.

**Comment by blakegonzales** [comment]
I just checked v2.22.0 and stdout gets flushed successfully now. Thanks! `😊`
