### ISSUE TITLE
Add a route to the tunneld service to shutdown

### ISSUE THREAD

**Issue by Valkhes** [doronz88/pymobiledevice3#659]
**Is your feature request related to a problem? Please describe.**
I want to be able to kill tunneld from my python program. The problem is that my program doesn't have superuser access, so I can't just kill it easily. It would mean that I need to tricks to end it (for exemple use a subprocess where I echo my password, then pipe it to the sudo kill command). This is not something I'm really fan.

**Describe the solution you'd like**
I wonder if it's possible to add an API route which would be doing a shutdown on the service, so it just ends. POST on http://127.0.0.1:5555/shutdown for exemple.

**Comment by netanelc305** [comment]
Hi,

I like your solution, but I'm a bit busy right now. I'll implement it as soon as I have more time. In the meantime, you are more than welcome to submit a PR 🙂.

**Comment by Valkhes** [comment]
Hey, thanks for the quick answer

I dont exactly know how you would handle it properly. Uvicorn seems to be running as the main loop and can't be killed gracefully with the current implementation.

The naive solution for me would be using psutil and os to get the pid of the current process and kill it using psutil

```
        @self._app.post('/shutdown')
        async def shutdown_app() -> None:
            await self._tunneld_core.close()
            parent_pid = os.getpid()
            parent = psutil.Process(parent_pid)
            for child in parent.children(recursive=True):
              child.kill()
            parent.kill()
```

It's working, but it's not graceful at all, and there is surely better to do.

Another solution I see would be to change the current behaviour and launch the uvicorn server on a thread that we can stop, or maybe find a way to send a SIG_INT.

If you know how to do it properly, I prefer to let you do it when you have some time, I'm not used to work with this so I would probably do a dirty code here.
