### ISSUE TITLE
Possible shadow ban happens to macOS 14 <=> iOS 17

### ISSUE THREAD

**Issue by jeasinema** [doronz88/pymobiledevice3#664]
**Test environment**
- Host OS version: macOS 14.1
- Target device model and iOS version: iPhone 12 Pro, iOS 17.1.1

**Describe the bug**
I used to have a seamless connection between these two. But since last week, after poking with the `simulate-location` maybe a bit too much (honestly, I just kept sending this command for 20-30 times), I've been encountering the following issues:

1. `python3 -m pymobiledevice3 remote start-quic-tunnel` takes considerably longer to finish than before. I would say at least 10x.
2. `pymobiledevice3 developer dvt simulate-location set` also takes much longer and it does not work or change the location.

I suspect some shadow ban from the iOS side here, but not sure if this mechanism even exists.

LMK if you need more information and thank you for this great project!

Best,
XM

**Comment by doronz88** [comment]
I'm also using macOS Sonoma and iOS 17.2, but not encountering any issues. If can add debug prints, please update what's causing these hangs.

My guess is the bonjour discover. You can test it with:
```shell
sudo pymobiledevice3 remote browse
```

If this one also hangs, then it's probably it.

**Comment by jeasinema** [comment]
Thank you for the reply!

I've tested it, the device info could be shown after hanging a bit.

Not sure if this is a fix, but after rolling back to `2.8.4` (which is the last version I used since update), the hanging issue just disappeared and everything works.

**Comment by lgladdy** [comment]
How long would you expect the `remote browse` to take? I think I have this same issue, where `dvt simulate-location set` seems to take 5-15 seconds to execute.

The `remote browse` command for me through `time` a few times confirms ~14 seconds:
```shell
sudo pymobiledevice3 remote browse  0.66s user 0.13s system 5% cpu 13.778 total
sudo pymobiledevice3 remote browse  0.62s user 0.13s system 5% cpu 13.989 total
sudo pymobiledevice3 remote browse  0.62s user 0.13s system 5% cpu 14.097 total
sudo pymobiledevice3 remote browse  0.61s user 0.11s system 5% cpu 13.986 total
```

**Comment by Htiango** [comment]
I encountered the same issue. roughly 100 seconds on my side

My environment is:
- Host OS version: macOS 14.1
- Target device model and iOS version: iPhone 12 Pro, iOS 17.1.2
- 2.37.0 version of pymobiledevice3

```
sudo pymobiledevice3 remote browse  1.39s user 0.28s system 1% cpu 1:40.80 total
```


and after rollback to version `2.8.4` it's back to normal

```
sudo pymobiledevice3 remote browse  1.63s user 0.29s system 64% cpu 2.979 total
```

**Comment by Htiango** [comment]
FYI I did some local testing and figured out it's this line being way too slow
https://github.com/doronz88/pymobiledevice3/blob/2b64e6c8ddcce14fe21f4eb84ecb9fc630f39c45/pymobiledevice3/remote/remote_service_discovery.py#L56
