### ISSUE TITLE
Would it be possible to get stdout/stderr streamed from `pymobiledevice3 developer dvt launch`

### ISSUE THREAD

**Issue by WaterJuice** [doronz88/pymobiledevice3#666]
With the libimobiiledevice toolset I was able to use `idevicedebug` to launch an app on iPhone and it would stream the stdout/stderr back while the app was running and it would also return the processes return code when it ended.
I would like a way to do this now in iOS 17.
I have two ways of launching an app now on iOS17.

1) Using Xcode 15's: `xcrun devicectl device process launch`
2) Using `pymobiledevice3 developer dvt launch`

Both work in a similar way by launching the app and then returning.

Is there a way existing that I can get stdout/stderr streaming? And if not would it be something that could be added to pymobiledevice3.

Thank you.

**Comment by doronz88** [comment]
I just pushed a PR that might resolve your issue. It doesn't get an event for process termination though

**Comment by sachatt** [comment]
@WaterJuice , a bit new to `pymobiledevice3`. I understand on `xcrun` I launch an app via

```
xcrun devicectl device process launch --device <ID> <BUNDLE_ID> <ARGS>
```

But with `pymobiledevice3` I do not see any possibility to specify the app

**Comment by sachatt** [comment]
@doronz88 , any help with this? When I specify my bundle ID and args it gives errors, interpreting the bundle ID and arguments as arguments to process launch,

**Comment by doronz88** [comment]
If you are encountering issues then please submit an issue @SachaTe
