### ISSUE TITLE
incompatible architecture (have 'x86_64', need 'arm64')

### ISSUE THREAD

**Issue by KingRat0011** [doronz88/pymobiledevice3#668]
**Test environment**
- Sonoma 14.1.1
- iOS 17.1.1 - iPhone14 

**Describe the bug**
Its a MiniMac running a M1 chip, I installed pymobiledevice3 using python3 -m pip install -U pymobiledevice3

Error
Mac-mini:~ $ sudo python3 -m pymobiledevice3 remote tunneld
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 8, in <module>
    from pymobiledevice3.cli.activation import cli as activation_cli
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/activation.py", line 3, in <module>
    from pymobiledevice3.cli.cli_common import Command
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 19, in <module>
    from pymobiledevice3.remote.remote_service_discovery import RemoteServiceDiscoveryService
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 9, in <module>
    from pymobiledevice3.remote.bonjour import DEFAULT_BONJOUR_TIMEOUT, get_remoted_addresses
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/bonjour.py", line 7, in <module>
    from zeroconf import ServiceBrowser, ServiceListener, Zeroconf
  File "/opt/homebrew/lib/python3.11/site-packages/zeroconf/__init__.py", line 25, in <module>
    from ._cache import DNSCache  # noqa # import needed for backwards compat
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Mac-mini:~ $

Any ideas on this please

**Comment by doronz88** [comment]
That's a but with `zeroconf`. Try to update it to latest version

**Comment by KingRat0011** [comment]
Trying

**Comment by KingRat0011** [comment]
Mac-mini:$ python3 -m pip install -U zeroconf
Requirement already satisfied: zeroconf in /opt/homebrew/lib/python3.11/site-packages (0.126.0)
Requirement already satisfied: ifaddr>=0.1.7 in /opt/homebrew/lib/python3.11/site-packages (from zeroconf) (0.2.0)
diginetiots-Mac-mini:bin diginetiot$ python3 -m pip uninstall zeroconf
Found existing installation: zeroconf 0.126.0
Uninstalling zeroconf-0.126.0:
  Would remove:
    /opt/homebrew/lib/python3.11/site-packages/zeroconf-0.126.0.dist-info/*
    /opt/homebrew/lib/python3.11/site-packages/zeroconf/*
Proceed (Y/n)? y
  Successfully uninstalled zeroconf-0.126.0
diginetiots-Mac-mini:bin diginetiot$ python3 -m pip install -U zeroconf
Collecting zeroconf
  Using cached zeroconf-0.126.0-cp311-cp311-macosx_14_0_arm64.whl
Requirement already satisfied: ifaddr>=0.1.7 in /opt/homebrew/lib/python3.11/site-packages (from zeroconf) (0.2.0)
Installing collected packages: zeroconf
Successfully installed zeroconf-0.126.0
diginetiots-Mac-mini:bin diginetiot$ sudo python3 -m pymobiledevice3 remote start-quic-tunnel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 8, in <module>
    from pymobiledevice3.cli.activation import cli as activation_cli
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/activation.py", line 3, in <module>
    from pymobiledevice3.cli.cli_common import Command
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 19, in <module>
    from pymobiledevice3.remote.remote_service_discovery import RemoteServiceDiscoveryService
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 9, in <module>
    from pymobiledevice3.remote.bonjour import DEFAULT_BONJOUR_TIMEOUT, get_remoted_addresses
  File "/opt/homebrew/lib/python3.11/site-packages/pymobiledevice3/remote/bonjour.py", line 7, in <module>
    from zeroconf import ServiceBrowser, ServiceListener, Zeroconf
  File "/opt/homebrew/lib/python3.11/site-packages/zeroconf/__init__.py", line 25, in <module>
    from ._cache import DNSCache  # noqa # import needed for backwards compat
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/zeroconf/_cache.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Mac-mini$

**Comment by doronz88** [comment]
I would try to uninstall and reinstall this extension. Anyhow I'll close this issue since this should be opened at `zeroconf` if it persists.

**Comment by KingRat0011** [comment]
for the record, this is how I fixed it
python3 -m pip uninstall zeroconf
Found existing installation: zeroconf 0.126.0
Uninstalling zeroconf-0.126.0:
  Would remove:
    /opt/homebrew/lib/python3.11/site-packages/zeroconf-0.126.0.dist-info/*
    /opt/homebrew/lib/python3.11/site-packages/zeroconf/*
Proceed (Y/n)? y
  Successfully uninstalled zeroconf-0.126.0

pip3 install zeroconf --compile --force-reinstall
Collecting zeroconf
  Downloading zeroconf-0.127.0.tar.gz (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 11.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ifaddr>=0.1.7 (from zeroconf)
  Using cached ifaddr-0.2.0-py3-none-any.whl (12 kB)
Building wheels for collected packages: zeroconf
  Building wheel for zeroconf (pyproject.toml) ... done
  Created wheel for zeroconf: filename=zeroconf-0.127.0-cp311-cp311-macosx_14_0_arm64.whl size=1660447 sha256=6168a3b1591ad54b5ca7e9f38b604393d57a8c3064c670cbdf35c45e8ff551f0
  Stored in directory: /Users/diginetiot/Library/Caches/pip/wheels/ae/26/a5/05949e2f0dc5cb989b45f872824961e8110ba2a6cf77cd8566
Successfully built zeroconf
Installing collected packages: ifaddr, zeroconf
  Attempting uninstall: ifaddr
    Found existing installation: ifaddr 0.2.0
    Uninstalling ifaddr-0.2.0:
      Successfully uninstalled ifaddr-0.2.0
Successfully installed ifaddr-0.2.0 zeroconf-0.127.0

Then it worked
sudo python3 -m pymobiledevice3 remote start-quic-tunnel
[?] choose device: <RemoteServiceDiscoveryService PRODUCT:iPhone14,7 VERSION:17.1.1 UDID:xxxxx>
 ❯ <RemoteServiceDiscoveryService PRODUCT:iPhone14,7 VERSION:17.1.1 UDID:xxxxxx>
   <RemoteServiceDiscoveryService PRODUCT:iPhone14,7 VERSION:17.1.1 UDID:xxxxxxx>
   <RemoteServiceDiscoveryService PRODUCT:iPhone14,7 VERSION:17.1.1 UDID:xxxxxxx>

2023-11-15 02:05:29 -Mac-pymobiledevice3.cli.remote[83848] INFO tunnel created
UDID: xxxxxxxx
ProductType: iPhone14,7
ProductVersion: 17.1.1
Interface: utun7
RSD Address: xxxxxx
RSD Port: xxxx
Use the follow connection option:
--rsd xxxx xxxx

**Comment by doronz88** [comment]
Thanks for the update!
