### ISSUE TITLE
auto-mount doesn't work for devices with iOS versions with triple digits (16.5.1, 16.6.1, 16.7.2, etc). 

### ISSUE THREAD

**Issue by ICE-FlatLine** [doronz88/pymobiledevice3#669]
**Test environment**
- MacOS Ventura 13.6, Xcode 15.0, python 3.12
- Any iPhone with iOS prior to 17.0, where iOS version has triple digits (16.5.1, 16.6.1, etc.)

**Describe the bug**
When using pymobiledevice3 mounter auto-mount command, it fails to mount developer disk image with the following error:
2023-11-13 12:31:28 Admins-Mac-mini-3.local pymobiledevice3.cli.mounter[32774] ERROR Unable to find the correct DeveloperDiskImage

**Additional context**
It seems like pymobiledevice3 explicitly looking for dev image directory with the exact version of for example 16.5.1, but there isn't a directory like that under /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport anyway.
In the past, it used a lockdown property called lockdown.sanitized_ios_version(or something like that), which would return '16.5' for a device with iOS 16.5.1, and then it would navigate to am existing directory inside Xcode.app. Or, if there wasn't Xcode installed, it would download a dev image of 16.5. But now it tries to download 16.5.1/16.6.1/16.7.2 developer image which doesn't exist.

**Comment by doronz88** [comment]
I don't a device to test it with, but can you verify if the PR I just created solves the issue?

**Comment by ICE-FlatLine** [comment]
Tested, Yeah - that PR solves the issue.
