### ISSUE TITLE
PersonalizedImages in doronz88/DeveloperDiskImage is partialy compatible with iOS17.2

### ISSUE THREAD

**Issue by prife** [doronz88/pymobiledevice3#671]
**Test environment**
- macOS 13.6
- iPhone 13, iOS 17.2 (beta)

**Describe the bug**

when mount with pymobiledevice3, use new Xcode_iOS_DDI_Personalized files downloaded in [https://api.github.com/repos/doronz88/DeveloperDiskImage/git/trees/main?recursive=true](https://api.github.com/repos/doronz88/DeveloperDiskImage/git/trees/main?recursive=true)

some services is missing.  such as `coredevice.appservice`

```
    "com.apple.coredevice.appservice": {
      "Entitlement": "com.apple.private.CoreDevice.canInstallCustomerContent",
      "Port": "49973",
      "Properties": {
        "Features": [
          "com.apple.coredevice.feature.launchapplication",
          "com.apple.coredevice.feature.spawnexecutable",
          "com.apple.coredevice.feature.monitorprocesstermination",
          "com.apple.coredevice.feature.installapp",
          "com.apple.coredevice.feature.uninstallapp",
          "com.apple.coredevice.feature.listroots",
          "com.apple.coredevice.feature.installroot",
          "com.apple.coredevice.feature.uninstallroot",
          "com.apple.coredevice.feature.sendsignaltoprocess",
          "com.apple.coredevice.feature.sendmemorywarningtoprocess",
          "com.apple.coredevice.feature.listprocesses",
          "com.apple.coredevice.feature.rebootdevice",
          "com.apple.coredevice.feature.listapps",
          "com.apple.coredevice.feature.fetchappicons"
        ],
        "ServiceVersion": 1,
        "UsesRemoteXPC": true
      }
    },
```

**To Reproduce**

1.  reboot the phone to make it unmounted
2. mount with pymobiledevice3
3. launch app with pymobiledevice3

**Additional context**

use xcode to mount, then the missing services come back.

**Comment by prife** [comment]
Could you give me some advice, that where did you get  the Xcode_iOS_DDI_Personalized files?

```
$ ls /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/ 
11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2 13.3 13.4 13.5 13.6 13.7 14.0 14.1 14.2 14.3 14.4 14.5 15.0 15.2 15.4 15.5 15.6 16.0
```

there is no the new Personalized files.

**Comment by doronz88** [comment]
All the details are described here:
https://github.com/doronz88/DeveloperDiskImage

If somehow the old DDI is not compatible, please create a PR to this project to update the newer files

**Comment by prife** [comment]
> All the details are described here: https://github.com/doronz88/DeveloperDiskImage
> 
> If somehow the old DDI is not compatible, please create a PR to this project to update the newer files

doronz,  thanks for your reply.

What I mean is, how did you extract these files from Xcode? I need to extract a file that is compatible with iOS version 17.2

**Comment by prife** [comment]
> All the details are described here: https://github.com/doronz88/DeveloperDiskImage
> 
> If somehow the old DDI is not compatible, please create a PR to this project to update the newer files

sorry, I understanded. it is in `~/Library/Developer/DeveloperDiskImages/`

**Comment by prife** [comment]
Sorry, I found that I made a mistake.

It's not a compatibility issue.  A new QUIC tunnel must be created after mounting. Thank you for your answer.
