### ISSUE TITLE
Failing to mount personalized DDI for iPhone12 mini (iPhone13,1)

### ISSUE THREAD

**Issue by tri5m** [doronz88/pymobiledevice3#675]
**Test environment**
- iOS17.1.1.
- Iphone12 mini iOS17.1.1.

**Describe the bug**
Unable to Developer Disk Image via `sudo pymobiledevice3 mounter auto-mount`

**To Reproduce**
An exception is thrown after executing the above command
```
File "/Users/Trifolium/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pymobiledevice3/restore/tss.py", line 777, in send_receive
    message = content.split(b'MESSAGE=', 1)[1].split(b'&', 1)[0].decode()
```
The main reason is the "content" response `401 Authorization Required` in line 777 .
I tried two phones, one of them Iphone13 is fine but this one 12mini has this problem and I still can't get it to work by restarting and unlocking etc.
![image](https://github.com/doronz88/pymobiledevice3/assets/49668053/e2a1e5ae-1927-41d7-a5ed-1cee85558137)

**Comment by doronz88** [comment]
Unfortunately I don't have a iPhone 12 mini to test it with, but my guess is that the ticket on that device is probably sent in wrong form. If you want and can, I can guide you on the [`Discord`](https://discord.gg/52mZGC3JXJ) channel on how to sniff the ticket sent from XCode and compare the two.

**Comment by tri5m** [comment]
Thanks, on my 12mini iOS17.1.1 there was no developer mode option, I turned it on through a third party software and then I had permission to mount the developer image. Now it is possible to mount it normally.

**Comment by doronz88** [comment]
You could also do it using:

```shell
pymobiledevice3 amfi enable-developer-mode
```
