### ISSUE TITLE
DeveloperModeIsNotEnabledError

### ISSUE THREAD

**Issue by chang-chih-yao** [doronz88/pymobiledevice3#686]
I encountered a DeveloperModeIsNotEnabledError when trying to "pymobiledevice3 mounter auto-mount" on my iPhone 8 (iOS 16.7.2). Do I need to make any specific settings on my iPhone? or this library does not support iPhone 8?

**Comment by doronz88** [comment]
```shell
pymobiledevice3 amfi enable-developer-mode
```

**Comment by chang-chih-yao** [comment]
How can I correctly enable the developer mode option on an iPhone that doesn't currently have it?

Should I first execute "pymobiledevice3 mounter auto-mount" and then "pymobiledevice3 amfi enable-developer-mode"? Or is it the other way around? Or is it sufficient to only use "pymobiledevice3 amfi enable-developer-mode"? 

I'm not quite clear on the actual functions of "pymobiledevice3 mounter auto-mount" and "pymobiledevice3 amfi enable-developer-mode".

Thanks~

**Comment by chang-chih-yao** [comment]
Additionally, I have another question. I've already enabled developer mode on my iPhone ( lockdown.developer_mode_status == True ), but I encountered an ERROR when trying to modify the GPS location. What's going on?

########################### PLATFORM ###########################
PC: win10
python 3.8.17

########################### MY PYTHON CODE ###########################
import struct

from pymobiledevice3.lockdown import LockdownClient, create_using_usbmux
from pymobiledevice3.services.lockdown_service import LockdownService

class DtSimulateLocation(LockdownService):
    SERVICE_NAME = 'com.apple.dt.simulatelocation'

    def __init__(self, lockdown: LockdownClient):
        super().__init__(lockdown, self.SERVICE_NAME)

    def clear(self):
        """ stop simulation """
        service = self.lockdown.start_lockdown_developer_service(self.SERVICE_NAME)
        service.sendall(struct.pack('>I', 1))

    def set(self, latitude: float, longitude: float):
        """ stop simulation """
        service = self.lockdown.start_lockdown_developer_service(self.SERVICE_NAME)
        service.sendall(struct.pack('>I', 0))
        latitude = str(latitude).encode()
        longitude = str(longitude).encode()
        service.sendall(struct.pack('>I', len(latitude)) + latitude)
        service.sendall(struct.pack('>I', len(longitude)) + longitude)

my_lockdown = create_using_usbmux()
t = DtSimulateLocation(my_lockdown)
t.set(37.75686807326742, -122.45080704574748)


########################### ERROR LOG ###########################

Traceback (most recent call last):
  File "gps_temp.py", line 27, in <module>
    t = DtSimulateLocation(my_lockdown)
  File "gps_temp.py", line 10, in __init__
    super().__init__(lockdown, self.SERVICE_NAME)
  File "D:\Code\GitHub\ios_sim\test_scripts\pymobiledevice3\services\lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
  File "D:\Code\GitHub\ios_sim\test_scripts\pymobiledevice3\lockdown.py", line 87, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
  File "D:\Code\GitHub\ios_sim\test_scripts\pymobiledevice3\lockdown.py", line 456, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
  File "D:\Code\GitHub\ios_sim\test_scripts\pymobiledevice3\lockdown.py", line 446, in get_service_connection_attributes
    response = self._request('StartService', options)
  File "D:\Code\GitHub\ios_sim\test_scripts\pymobiledevice3\lockdown.py", line 530, in _request
    raise exception_errors.get(error, LockdownError)(error)
pymobiledevice3.exceptions.InvalidServiceError: InvalidService

**Comment by doronz88** [comment]
- As the error clearly says, you must enable developer mode to use mount and other developer features
- In addition, you are not using the correct API to access location services. You can copy it from CLI code:
- https://github.com/doronz88/pymobiledevice3/blob/462a653860ee78fbf421def791e16f36e977de5c/pymobiledevice3/cli/developer.py#L962
