### ISSUE TITLE
Allow `developer dvt pkill` to kill by bundleIdentifier 

### ISSUE THREAD

**Issue by corrrso** [doronz88/pymobiledevice3#687]
Right now, `pymobiledevice3 developer dvt pkill` checks for an expression match in the name of the process to kill it.

Since the `bundleIdentifier` attribute is available as well in the proclist, and since it's already used to launch a process (E.G. `pymobiledevice3 developer dvt launch com.company.appbundle`), I think it would make a nice addition to allow a bundle identifier as a parameter.

Also, the `pkill` command is one of the few commands that wants the **rsd argument first** and only then an actual command parameter, which might be a bit confusing .

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
- `pkill` should recive its argument afterwards also. If not it's a bug. I just tested it and it works as intended
- what would you prefer the command would receive? another flag option `--bundle`? or a separate command?

**Comment by corrrso** [comment]
Oh, actually the arguments work in the order you intended already. I got caught off by the help output which seems to invert them. Sorry about this, apparently it was just the help command pushing out the wrong thing.

```
pymobiledevice3 developer dvt pkill -h                            
Usage: pymobiledevice3 developer dvt pkill [OPTIONS] EXPRESSION

kill all processes containing `expression` in their name.

Options:
  --rsd <TEXT INTEGER>...  RSD hostname and port number NOTE: This argument is
                           mutually exclusive with  arguments:
                           [rsd_service_provider_using_tunneld].
  --tunnel TEXT            Either an empty string to force tunneld device
                           selection, or a UDID of a tunneld discovered device
                           NOTE: This argument is mutually exclusive with
                           arguments: [rsd_service_provider_manually].
  --usbmux TEXT            usbmuxd listener address (in the form of either
                           /path/to/unix/socket OR HOST:PORT
  --udid TEXT              Device unique identifier. You may pass
                           PYMOBILEDEVICE3_UDID environment variable to pass
                           this option as well
  -v, --verbose
  -h, --help               Show this message and exit.

```

As for the bundleIdentifier, I think it makes sense to add an additional flag. There are already `kill` and `pkill`, maybe it can get confusing to add a third command to kill.

I would love to collaborate, but I have very limited knowledge of Python unfortunately. Thanks for the support though, really appreciate it.

**Comment by doronz88** [comment]
I just looked and haven't found a direct way to get the pid from the bundle-identifier. no exported API directly retrieves this value.

**Comment by corrrso** [comment]
Hum...

If I try to run `pymobiledevice3 developer dvt proclist`, I see all these information are retrievable. I wonder if this is enough to get the PID from a bundleIdentifier

```
{
        "bundleIdentifier": "com.apple.TVSystemUIService",
        "foregroundRunning": true,
        "isApplication": true,
        "name": "TVSystemUIService",
        "pid": 156,
        "realAppName": "/Applications/TVSystemUIService.app/TVSystemUIService",
        "startDate": "2023-11-22 14:23:11.276152"
}
```

Maybe I'm missing something that won't allow this?

**Comment by doronz88** [comment]
This is not cross ios versions. for example on my ios17.2 i'm getting:
```
    {
        "isApplication": false,
        "name": "bookassetd",
        "pid": 317,
        "realAppName": "/System/Library/PrivateFrameworks/BookLibraryCore.framework/Support/bookassetd",
        "startDate": "2023-11-17 09:39:34.710299"
    },
```

**Comment by corrrso** [comment]
I don't think you're looking at an application installed by the user. If the user installs an app bundle, you'll notice that `isApplication` is true and that a `bundleIdentifier` will then be present.

It would be enough to do something like `if (app.isApplication == true && app.bundleIdentifier != null && app.bundleIdentifier == argument) => pid = app.pid`

That's why I think it would be very useful for a user to target that, it would make sense to use the same way of targeting a specific application (Launch, kill etc...).

But, if this is too troublesome or if it would not work with older OS versions, then it's OK how it is right now.

Tested this on a tvOS 17.1.

**Comment by doronz88** [comment]
Okay I missed only some had this attribute. Can you verify #714 works as you would expect?

**Comment by corrrso** [comment]
Sure, I will ASAP. Thank you!

**Comment by corrrso** [comment]
@doronz88 Just tested both with a pre-installed Apple app and with an app I installed manually, works properly with both.
Thank you for your effort.
