### ISSUE TITLE
Problem with pymobiledevice3 screenshot on Windows or also other commands

### ISSUE THREAD

**Issue by Giteshkongre** [doronz88/pymobiledevice3#724]
**Environment:**
- Operating System: Windows 10
- Python Version: 3.x
- iOS Device Version: 17.1.3

**Describe the bug**
1]I m encountering an error when trying to capture a screenshot from an iOS device using pymobiledevice3 on Windows. 
2]Firstly i make sure that DeveloperDiskImage/PersonalizedImage is mounted. By running the following command:
python3 -m pymobiledevice3 mounter auto-mount. Than it was showing the an error for : - 
2023-12-06 12:17:38 UTS-GEETESHK pymobiledevice3.__main__[18308] ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
3]It's mentioned that Apple might have removed the service you're trying to access. Ensure that the service you are trying to use is still supported by Apple. please also correct me if this service is removeded

**Steps to Reproduce:**
1. Ran the command: `pymobiledevice3 mounter auto-mount`
2. Attempted to capture a screenshot with: `pymobiledevice3 developer dvt screenshot C:\Windows\System32\cmd.exe\screen.png`

**Expected behavior**
I expected to capture a screenshot from my iOS device using pymobiledevice3 on Windows.

**Actual Behavior:**
I encountered an error message when running the screenshot command, as detailed in my previous message.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Duplicate #569
