### ISSUE TITLE
Issues with --stream option and timestamp crashing

### ISSUE THREAD

**Issue by sachatt** [doronz88/pymobiledevice3#727]
**Test environment**
- iOS17.1.1
- iPad8, 9
-
**Describe the bug**
The `datetime.datetime.fromtimestamp(message[2].value)` line within class `OutputReceivedEvent` method `create` in `process_control.py` crashes due to an incorrect timestamp, with error;
```
ValueError: year 207343 is out of range
```

**To Reproduce**
1. Simply running `python3 -m pymobiledevice3 developer dvt launch --kill-existing --stream --rsd <ADDRESS> <PORT> <BUNDLE_ID>`

**Expected behavior**
We should at least have a sort of try catch

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

**Comment by doronz88** [comment]
I'm not encountering the error and therefore cannot reproduce. Please provide clear and concise steps to reproduce. I guess you're set to some specific date.
Also, feel free to treat this error yourself and submit a PR :)

**Comment by sachatt** [comment]
I tried to submit a PR but I get access rights issues

**Comment by doronz88** [comment]
PRs on public repositories require you to fork the repo and then submit a PR from the remote fork
