### ISSUE TITLE
"sudo python3 -m pymobiledevice3 remote start-tunnel" can not run iOS17 by via wifi

### ISSUE THREAD

**Issue by ltDino** [doronz88/pymobiledevice3#729]
**Test environment**
- macOS14.1.1
- iPad13,18; iOS17.1.1

**Describe the bug**
I can not get rsd info by command `sudo python3 -m pymobiledevice3 remote start-tunnel`
when I make Mac and Iphone connect to the same wifi, and config connect via network in xcode
But every thing work normal when I make mac and iphone connect by usb

**To Reproduce**
1. run `pymobiledevice3 lockdown wifi-connections on`
2. and run `pymobiledevice3 usbmux list` it can display device info, connectionType=network
![image](https://github.com/doronz88/pymobiledevice3/assets/57250557/288095a6-645d-459a-85df-9e9107b58719)
3. `sudo python3 -m pymobiledevice3 remote start-tunnel` it doesn't work, `ERROR Device is not connected`
![image](https://github.com/doronz88/pymobiledevice3/assets/57250557/a5534a10-fcd7-4681-ad93-b610d10f116c)

**Comment by doronz88** [comment]
You cannot start tunnel over wifi by design
