### ISSUE TITLE
`pymobiledevice3 remote start-tunnel` won't terminate after tunnel unexpectedly closes

### ISSUE THREAD

**Issue by corrrso** [doronz88/pymobiledevice3#734]
**Test environment**
Tested on tvOS 17.1

**Describe the bug**
The process created by the command `pymobiledevice3 remote start-tunnel` seems to stay active indefinitely even after connection with the device is lost. When this happens, this output is printed `pymobiledevice3.cli.remote[13516] INFO tunnel was closed` but then the process doesn't exit, even if it's impossible for the tunnel to re-open in the same process.

**To Reproduce**
1. `pymobiledevice3 remote start-tunnel -p quic`
2. Tunnel created successfully
3. Disconnect the device from the internet / physically
4. See the output `pymobiledevice3.cli.remote[13516] INFO tunnel was closed`
5. Notice how the process hangs forever instead of closing

**Expected behavior**
At point 5, I would expect the process to be terminated together with the tunnel.

**Comment by doronz88** [comment]
I wasn't able to reproduce this error. Just wondering if it occurs even on `--max-idle-timeout 1`

**Comment by corrrso** [comment]
I tried both with the default timeout value and with `--max-idle-timeout 1` and it happens in both cases.
I tried replicating by shutting down the device and it works as well. Maybe it makes life easier for you to replicate this.

Question: while trying to replicate, did you reach the point where you get `pymobiledevice3.cli.remote[13516] INFO tunnel was closed` or you didn't reach this yet? Just wanted to see if the issue is that you can't close the tunnel of if you can close it but the tunnel actually recovers the connection.

Next years good resolutions: learn python a bit so I can understand more the source code :D

**Comment by doronz88** [comment]
Can you verify again with latest version?

**Comment by doronz88** [comment]
Seems like this issue is stale and probably resolved. Feel free to reopen if not
