### ISSUE TITLE
Make it happen make it happen make it happen

### ISSUE THREAD

**Issue by ajlchiban** [doronz88/pymobiledevice3#735]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by ajlchiban** [comment]
Make it happen make it happen

**Comment by doronz88** [comment]
I don't even know what you want - but being so rude will just prevent me from helping you
