### ISSUE TITLE
tunneld hangs when pair dialog is shown

### ISSUE THREAD

**Issue by martindasilva404** [doronz88/pymobiledevice3#739]
**Test environment**
- Host OS version: Ventura 13.6
- Target device model and iOS version: all iOS 17.x devices

**Describe the bug**
Upon launching tunneld daemon, when several devices are connected and at least 1 is not paired to the mac, all other paired devices cannot take a screenshot.

**To Reproduce**
1. Connect several devices thru a usb hub and unpair 1 device
2. Execute: `sudo pymobiledevice3 remote tunneld -d`
3. Take a screenshot of a paired device: `pymobiledevice3 developer dvt screenshot ./test.png --tunnel <serial>`
4. The screenshot command will not complete and just hang up

**Expected behavior**
Tunneld should disregard unpaired devices and not affect all others when executing commands.

**Comment by doronz88** [comment]
This would require a rewrite of tunneld - which would probably occur sometime in the future.
The design fix we thought about was:

- To scan for network adapters update
- Each newly created will initiate an asyncio task to start RSD handshake and thus not block other discovery

It will take time till I have time to get to it. Meanwhile, you're more then welcome to submit a PR

**Comment by martindasilva404** [comment]
Thank you. Will just wait for the fix whenever its done. Device pairing will be advised to our users

**Comment by doronz88** [comment]
I reopened just to keep track and remember to make this happen :)

**Comment by doronz88** [comment]
@mds2018 can you verify #938 solves the issue?

**Comment by martindasilva404** [comment]
> @mds2018 can you verify #938 solves the issue?

@doronz88 we haven't had this issue since v2.46.1. I suppose this could provide further improvements as well. Thank you!
