### ISSUE TITLE
can not show device via wifi

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#741]
step
1.set wifi-connections on 
2.disconnect iPhone By USB
3.show usbmux list
![image](https://github.com/doronz88/pymobiledevice3/assets/12728951/a011ac53-161c-4814-b0de-5861e83e22db)

**Comment by doronz88** [comment]
Please try to set the wifi-connections attribute via Finder and test this again since if it's a bug, it's probably in setting this attribute

**Comment by nyz110** [comment]
sorry, I don't know how to  set the wifi-connections attribute via Finder , which option?

**Comment by doronz88** [comment]
https://support.apple.com/en-il/guide/mac-help/mchlada1d602/mac#:~:text=In%20the%20Finder%20on%20your,on%20Wi%2DFi%E2%80%9D%20checkbox.

**Comment by nyz110** [comment]
I turn on this option ,but not work，usbmux list didn't show my iPhone device

**Comment by doronz88** [comment]
What about finder? does it list it?

**Comment by nyz110** [comment]
finder do not list it too

**Comment by doronz88** [comment]
Then this is an apple bug. pymobile relies on `usbmuxd` which is an apple daemon
