### ISSUE TITLE
how to detect current device DeveloperDiskImage has been mounted?

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#753]
`python3 -m pymobiledevice3 mounter list ` show mounter list ,but I don't know whether current device was mounted。 what is the relationship between the two。

**Comment by doronz88** [comment]
I failed to understand your question. Between the two what?

**Comment by nyz110** [comment]
device and mounter image .

**Comment by nyz110** [comment]
if a device has not been mounted ，i will  auto-mounnt  image .but if the device has been mounted, i will do nothine.
I just want to judge whether a device has been mounted

**Comment by doronz88** [comment]
I still cannot understand. The device isn't mounted anywhere. The DDI is the one being mounted.
If the list command shows it's been mounted then it's been mounted.

**Comment by nyz110** [comment]
I have two device ，and mounted one at pre time . now, the list command shows one  mounted image， but i don't know which device has been mounted

**Comment by doronz88** [comment]
If the workstation detects more then one device then you will be prompted to choose for which to query

**Comment by nyz110** [comment]
ok，thx
