### ISSUE TITLE
mounter device error with ios 17.2.1

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#754]
**Test environment**
- Host OS version. macOS 14.1.2
- Target device model and iOS version.  iOS17.2.1

**Describe the bug**
mounter device error

**To Reproduce**
1.` sudo python3 -m pymobiledevice3 remote start-tunnel`
2. `python3 -m pymobiledevice3 mounter auto-mount --rsd fd25:91a4:86aa::1 59171`

**Expected behavior**
run with error

**Logs**
xxx@MacBook-Pro neocollectorconfig % python3 -m pymobiledevice3 mounter auto-mount --rsd fd25:91a4:86aa::1 59171
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 149, in <module>
    main()
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 101, in main
    cli()
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 134, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/mounter.py", line 122, in mounter_auto_mount
    auto_mount(service_provider, xcode=xcode, version=version)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 362, in auto_mount
    auto_mount_personalized(lockdown)
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/services/mobile_image_mounter.py", line 348, in auto_mount_personalized
    repo = DeveloperDiskImageRepository.create()
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/developer_disk_image/repo.py", line 30, in create
    return cls(cls._query(DEVELOPER_DISK_IMAGE_REPO_TREE_URL)['tree'])
  File "/Users/xxx/Library/Python/3.9/lib/python/site-packages/developer_disk_image/repo.py", line 63, in _query
    raise GithubRateLimitExceededError()
developer_disk_image.exceptions.GithubRateLimitExceededError

**Comment by doronz88** [comment]
Yeah well I'm using the free tier of github's REST API so you'll have to wait before trying again

**Comment by nyz110** [comment]
how long will free API usage refresh .  what's the free limit count per day?

**Comment by doronz88** [comment]
You're welcome to read:
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api

**Comment by rob-X1** [comment]
A few minutes ago I also ran into the GithubRateLimitExceededError

The [GitHub documentation](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28
) mentions that authenticated requests have a different limit:
> If you want a higher primary rate limit, consider making authenticated requests instead of unauthenticated requests. Authenticated requests have a significantly higher rate limit than unauthenticated requests.

Is there a way to provide credentials to the `pymobiledevice3 mounter auto-mount` command to avoid being locked-out by the rate limit?

**Comment by doronz88** [comment]
I wouldn't want to include my own credentials for it. If you wish, feel free to include your own with a pr, or somehow provide an alternative way to download these images

**Comment by rob-X1** [comment]
Of course, hard-coded credentials would only lead to misusing them. I was asking to provide own credentials. 

Digging through your code the relevant endpoint seems to be `.../DeveloperDiskImage/git/trees/main?recursive=true` in https://github.com/doronz88/DeveloperDiskImage/blob/01a67171dbb60d230600e1a3769d9b341e4f46f5/developer_disk_image/repo.py#L11

If I call https://api.github.com/rate_limit I see that the current rate limit is "60" for `core`. If I perform `pymobiledevice3  mounter auto-mount` the `used` value increases and the `remaining` value decreases just as expected. 

If I make the same request using a just created [fine-grained personal access token](https://github.com/settings/personal-access-tokens/new) for "Public repositories" and without any "Account Permissions" and use it in a REST call

```
GET https://api.github.com/rate_limit HTTP/1.1
User-Agent: Fiddler
Accept: application/vnd.github+json
Authorization: Bearer <my personal access token>
X-GitHub-Api-Version: 2022-11-28
Host: api.github.com
```

The "core" limitation increases to 5000. 

I used the same headers for a call in a raw call (outside Python in a HTTP tool) to  `.../DeveloperDiskImage/git/trees/main?recursive=true` and checked afterward the `rate_limit` again and `used` value increased and the `remaining` value decreased by one. So in general it seems to work. 

So if I understand your code correctly everything that is needed to perform authenticated calls is adding those headers in the request here: https://github.com/doronz88/DeveloperDiskImage/blob/01a67171dbb60d230600e1a3769d9b341e4f46f5/developer_disk_image/repo.py#L61

What would be the preferred way to configure the GitHub access token? For command-line the PAT would be a bit long (mine has 93 characters). So better an ENV variable or a configuration file?

**Comment by rob-X1** [comment]
Just for the record: Every `mounter auto-mount` makes 4 API calls. The unauthenticated maximum API rate is 60 requests in ~1 hour (per IP?). That allows you to perform 15 mount operations (only considering requests caused by `mounter auto-mount` and assuming your IP is not shared with other users because of a NAT gateway).

**Comment by doronz88** [comment]
Probably the best way will be to fetch it from GitHub directly without using the official API since then we have no limitations, but then the implementation becomes more difficult. I think the solution suggested in your PR is okay. I don't think there is any other much better way to do this since there is no official way to downloaded these images

**Comment by rob-X1** [comment]
Looking at the code of `auto_mount_personalized` method I have recognized that the API rate problem is (in my case) in the end a problem with the personalized disk image caching algo.

Pymobiledevice3 ignores all cached files in `Xcode_iOS_DDI_Personalized` that do not have the hard-coded ProductBuildVersion of `16A242d` (hardcoded in the source code of pymobiledevice3). 
The cached version on my disk has a ProductBuildVersion of `16E5121h` which means every downloaded image is only used exactly one time, thus the cache has no effect at all.

In my opinion there should be an additional time based check, that checks the cached file date/time on disk and compares it to the local time. 

If the cached files are younger than e.g. 2 hours then they are used without trying to redownload them. That would massively reduce the number of GitHub API calls. Even in a situation where a large number users share the same IP the chance running into an GithubRateLimitExceededError should be extremely low with this time based cache.

**Comment by doronz88** [comment]
With each product apple releases, they also release a new ddi to support it. If pymobile won't verify you have the latest ddi before trying to work with the device you might encounter an exception trying to mount it saying its not compatible with your exact device.

**Comment by rob-X1** [comment]
But the images are downloaded every time, even if they are not necessary at all (if the device has already mounted images) causing totally unnecessary traffic and GitHub API requests. 

I have changed the update logic a bit to only check every 6 hours:
https://github.com/rob-X1/pymobiledevice3/commit/7d0b68c4068dc649724b5e8811867805d889e691

Is there a chance that you would accept this commit when I open a PR?

**Comment by doronz88** [comment]
Oh thanks for letting me know I haven't updated `16E5121h` to the correct version!
I'll create a fix for that.
I don't want to add additional random behavior, since it will lead to different bugs for different people using a different version of the DDI.

**Comment by rob-X1** [comment]
Ok, I don't really like the way the code is at the moment but if you don't want to change the caching system I have to accept that. 

But in my opinion we should make it transparent to the user if the downloaded personalized image is not the expected version and thus the cache doesn't work. 

Please see my [PR](https://github.com/doronz88/pymobiledevice3/pull/1434) which shows a warning to the user if the downloaded personalized image is not as expected. With those changes the user will be warned that the cache does not work as expected. And it even helps you to identify situation where the personalized image has been updated but the `LATEST_DDI_BUILD_ID` has not adapted.
