### ISSUE TITLE
Backup Failed to fully upload (Input/output error)

### ISSUE THREAD

**Issue by derkrasseleo** [doronz88/pymobiledevice3#755]
**Test environment**
- Arch Linux (package pymobiledevice3 2.36.0, installed using Python 3.11.5)
- iPhone XR / iOS 17.2.1
 
**Describe the bug**
I can't seem to backup without I/O errors and I'm not sure if it's my drive or a problem with this package.

**To Reproduce**
`pymobiledevice3 backup2 backup --full "$drive_1"/Backup/iPhone/`

**Expected behavior**
No error

**Logs**
`/home/leo/.local/pipx/venvs/pymobiledevice3/lib/python3.11/site-packages/pymobiledevice3/services/device_link.py:136: UserWarning: Failed to fully upload: 00008020-001B24560AD8003A/Snapshot/49/49128ab470583769cf58eb2e9fe2eb47983afac3. Device file name: /var/mobile/Library/Application Support/FileProvider/backup/backup_manifest.db. Reason: Input/output error (5)
  warnings.warn(f'Failed to fully upload: {file_name}. Device file name: {device_name}. Reason: '`

**Additional context**
I have had successful backups before.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This is the expected behavior since Apple introduced this bug. This doesn't prevent the backup from fully working

**Comment by derkrasseleo** [comment]
Good to know, thanks! So that means I have a working backup even though I ran into this error?

**Comment by doronz88** [comment]
Correct 😃
