### ISSUE TITLE
What iP address do I need to use to mount personalised DDI?

### ISSUE THREAD

**Issue by Vercixx** [doronz88/pymobiledevice3#756]
**Test environment**
- Windows 10 22H1
- iPhone 12 mini(iPhone 13,1), iOS 17.1.1.

**Describe the bug**
Is mounting DDI requires SSH or what iP address and port I need to use?

**Expected behavior**
I'm trying to mount DDI with --rsd options but it requires iP and port

**Logs**
```
(base) C:\User\user\Downloads>pymobiledevice3 mounter auto-mount --rsd
Error: Option '--rsd' requires 2 arguments.
```

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
https://github.com/doronz88/pymobiledevice3?tab=readme-ov-file#working-with-developer-tools-ios--170
