### ISSUE TITLE
Unable to take screenshot

### ISSUE THREAD

**Issue by Sam-Neale** [doronz88/pymobiledevice3#758]
**Test environment**
- macOS Sonoma 14.3 Developer Beta
- iOS 17.3 Developer Beta

**Describe the bug**
Unable to use the screenshot service. Successfully opened the tunnel and installed developer image though.

**To Reproduce**
Command: ``python3 -m pymobiledevice3 developer screenshot ~/Developer/base.png``

**Expected behavior**

**Logs**
<img width="820" alt="Screenshot 2023-12-30 at 9 09 34 pm" src="https://github.com/doronz88/pymobiledevice3/assets/46592881/d06b95e2-a6dc-4fb9-ae89-f05eb7d68a95">

**Additional context**
Device was originally showing as not connected for tunnel creation, after unplugging cable it worked though.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Sam-Neale** [comment]
<img width="842" alt="Screenshot 2023-12-30 at 9 12 45 pm" src="https://github.com/doronz88/pymobiledevice3/assets/46592881/1528cfd7-ef24-44c0-97d6-699671d024e7">

Also didn't work if I included the RSD in the subcommand itself

**Comment by doronz88** [comment]
The correct commaand for ios 17 is:

```shell
pymobiledevice3 developer dvt screentshot
```

This of course also requires an rsd option

**Comment by Sam-Neale** [comment]
Thanks, might submit a PR in the morning to make that a bit clearer in the docs.
