### ISSUE TITLE
launch iOS app without killing it when app was opened before

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#762]
**Test environment**
- Host OS version.  any
- Target device model and iOS version.  any

**Describe the bug**
I use `python3 -m pymobiledevice3 developer dvt launch myappbundleid` command to launch my app. but when my app was opened before, the command will kill and launch my app . I just want to open my app without killing it,  how to do that?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Add the `--no-kill-existing` flag
