### ISSUE TITLE
FEATURE REQUEST: get app list with simple info

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#763]
**Test environment**
- Host OS version. any
- Target device model and iOS version. any

**Describe the bug**
I use `python3 -m pymobiledevice3 apps list --user` command to get install apps.  the command taked about 1-2 second to exec, and stdout log has too many infomations. I want to get install app list with bundleID only ,or info.plist content without Entitlements info.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Can you verify if #771 works fast enough?

**Comment by nyz110** [comment]
how to install this version?

**Comment by doronz88** [comment]
In general, as described in here:
https://github.com/doronz88/pymobiledevice3

But since I just released a version with this update, you can simply update the package now

**Comment by nyz110** [comment]
> Can you verify if #771 works fast enough?

yes, the new version works fast, the command cost less than 1 second,👍🏻
