### ISSUE TITLE
No commands except version, command not found

### ISSUE THREAD

**Issue by scha384** [doronz88/pymobiledevice3#764]
**Test environment**
- macOS Sonoma 14.2.1 (23C71) - pymobiledevice3 2.36.2 (with `/usr/local/bin/python3`)
- iPhone 15 (A3090) - iOS 17.3 Beta (21D5026f)

When attempting to run any command (except `.../python3 -m pymobiledevice3 version`) like `.../python3 -m pymobiledevice3 usbmux list` I get the following error message:
```
Usage: python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...
Try 'python -m pymobiledevice3 -h' for help.

Error: No such command 'usbmux'.
```

When running with `-h` I get:
```
Usage: python -m pymobiledevice3 [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  version  get installed package version
```
If I understand correctly, more commands should be listed here.

**Reproduce**
1. Have `pymobiledevice3` installed
2. Run `python3 -m pymobiledevice3 usbmux list`

**Expected behavior**
The command should exist and list connected devices.

**Comment by doronz88** [comment]
I cannot reproduce it
Please try changing the try-except to print the error you're getting:
https://github.com/doronz88/pymobiledevice3/blob/5f52015b7de9ee71fe169c9497c7251eacab6a68/pymobiledevice3/__main__.py#L82-L85

**Comment by scha384** [comment]
I did and got the same error as issue #668 which I fixed with `python3 -m pip install pymobiledevice3 --force-reinstall`.

Thanks!
