### ISSUE TITLE
`dvt simulate-location` doesn't self exit after running command

### ISSUE THREAD

**Issue by lgladdy** [doronz88/pymobiledevice3#767]
**Test environment**
iOS 17.3 beta 2, pymobiledevice 2.36.2

**Describe the bug**
When running a simulate-location task via RSD on iOS 17.3, pymobiledevice3 doesn't self quit are running the command, and hangs until you send an interrupt. I'm not sure if this is intended behaviour, but can't find any documentation on ways around it.

**To Reproduce**
1. Open an RSD tunnel
2. Call `pymobiledevice3 developer dvt simulate-location set --rsd [addr] [port] -- 60 60`
3. The command will execute after a few seconds, then the process will hang awaiting an interrupt to quit, but you can't seem to send any other commands in the process.

**Expected behavior**
The command executes, and the process quits.

**Logs**
```shell
/pymobiledevice3 developer dvt simulate-location set --rsd [addr] [port] -- 60 60
Press Ctrl+C to send a SIGINT or use 'kill' command to send a SIGTERM
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
This is the expected behavior. When the process exits, the simulation ends.
