### ISSUE TITLE
FEATURE REQUEST: how to query whether install an app with bundleid

### ISSUE THREAD

**Issue by nyz110** [doronz88/pymobiledevice3#770]
**Is your feature request related to a problem? Please describe.**
query whether install an app with bundleid

**Describe the solution you'd like**
command like `python3 -m pymobiledevice3 apps query bundleid`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by nyz110** [comment]
and how to detect  whether device screen was locked if device has password to unlock

**Comment by doronz88** [comment]
Please test #781 
Also, please separate different issues/requests so it's easier to track

**Comment by nyz110** [comment]
OK

> Please test #781 Also, please separate different issues/requests so it's easier to track

**Comment by nyz110** [comment]
I install pymobiledevice3 with master branch, install log: Successfully installed pymobiledevice3-2.37.1 
when I run `python3 -m pymobiledevice3 apps query -h  ` ,
err0r with log
Usage: python -m pymobiledevice3 apps [OPTIONS] COMMAND [ARGS]...
Try 'python -m pymobiledevice3 apps -h' for help.

**Comment by doronz88** [comment]
This change is not on master but instead on my PR

**Comment by nyz110** [comment]
refactor/installation-proxy  this branch works fine 👍🏻
