### ISSUE TITLE
DVT commands require a remount after a certain amount

### ISSUE THREAD

**Issue by codeskyblue** [doronz88/pymobiledevice3#784]
Service: com.apple.instruments.server.services.deviceinfo
Function: runningProcesses

After 250 consecutive calls on the following models, a socket connection failure occurs, and restarting the device restores it

Test Models

- iPhone XR (16.6)
- iPhone SE (15.8)

Very stable, still normal after 500 rounds

Test Models
- iPhone 13 Pro (iPhone13,3) (17.2)

Test code

```bash
for i in $(seq 300)
do
    echo $i
    pymobiledevice3 developer dvt proclist
done

**Comment by doronz88** [comment]
That is right and unfortunately the expected bahvior. `DTServiceHub` has a kqueue leak, leading to too many open FDs. The only solution is to either reboot afterwards or remount the DDI.

**Comment by corrrso** [comment]
Hi @doronz88 , I just met the same issue, but unfortunately remounting the DDI is not fixing it. Is there anything else that can be done without having to reboot the device?

**Comment by doronz88** [comment]
@corrrso I don't believe so. 
I believe this issue was fixed on iOS 17
