### ISSUE TITLE
Encountering Installation Error for pymobiledevice3 on macOS Monterey (Assistance Needed ASAP)

### ISSUE THREAD

**Issue by Rayray1099** [doronz88/pymobiledevice3#810]
**Test Environment:**
- Host OS Version: macOS Monterey VMware Virtual Machine
- Target Device: iPad Pro 2022

**Bug Description:**
Encountering an installation error when attempting to install pymobiledevice3 on macOS VM for **AltStore JIT**. The issue is illustrated in the provided screenshot.
<img width="681" alt="螢幕擷取畫面 2024-01-27 142011" src="https://github.com/doronz88/pymobiledevice3/assets/95627112/1baf2adc-62f1-436e-8dfe-0011fed2921e">

**Steps to Reproduce:**
1. Open 'Terminal'.
2. Execute the command: `python3 -m pip install pymobiledevice3==2.30.0 construct==2.10.69`
3. Observe the error as shown in the screenshot.

**Expected Behavior:**
The expected outcome should match the details presented in the screenshot.

**Logs:**
Logs are attached in the provided screenshot.

**Additional Context:**
No additional context provided.

## For Community
⬇️ **Please click the 👍 reaction instead of leaving a `+1` or 👍 comment**

**Comment by doronz88** [comment]
Never submit an issue for an OLD version of the project you are asking help for
