### ISSUE TITLE
Windows tunnel improvements

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#818]
Currently the windows rsd tunnel implementation relies on this project: https://github.com/DsoTsin/wintun
Which is based on: https://www.wintun.net/ and also adds:
1. Python bindings for wintun
2. Installation of the wetest driver

For better maintainability I suggest the following:
1. Create a new project that adds python bindings to `wintun` based on the prebuilt binaries from https://www.wintun.net/
   * without `wintun` source code - only rely on pre-built binaries and add python bindings (and add a ci build process for all architectures)
   * no wetest driver installation
   * This is easier to maintain if `wintun` has an update - just replace the pre-built binaries and update python bindings if API changed.
2. Add wetest driver installation as a prerequisite section in the readme. It's as simple as running this command:
   `pnputil.exe /add-driver %s /install`
   * this way we're not tied to one specific driver, so if apple/microsoft add native support in the future, we can skip this step.

**Comment by doronz88** [comment]
This sounds like the better way to go about the whole process, though will require quite a lot of work, so hope to have the time for it. PRs are very much welcome

**Comment by vToMy** [comment]
It might be possible to code a windows driver using this project as a base:
https://github.com/microsoft/NCM-Driver-for-Windows
And applying something similar to the patch provided for the linux kernel here:
https://github.com/doronz88/pymobiledevice3/issues/566#issuecomment-1850486679

**Comment by doronz88** [comment]
Since we can now establish tunnels over both wifi and lockdown, I think we should now avoid all the driver installations and rely solely on the prebuilt wintun binaries.

I hope someone is up for the job of wrapping this as a python package.

**Comment by doronz88** [comment]
Also, I think we can technically just use `ctypes.windll` based on this code:
https://github.com/DsoTsin/wintun/blob/master/api/pybinding.c

If anyone is interested in helping, please reach me out

**Comment by doronz88** [comment]
I created a skeleton project, but I won't have the time to also maintain this project:

https://github.com/doronz88/pywintun/blob/master/main.py

**Comment by doronz88** [comment]
I created a WIP PR for this:

https://github.com/doronz88/pytun-pmd3/pull/5/files

Couldn't manage to get it to work. I lack knowledge in win development
