### ISSUE TITLE
[Help Wanted] Need help with pcap output

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#819]
How can I save the output of  `pymobiledevice3 pcap --no-color > FILE_NAME.EXTENSION`  so I can open it with the WireShark app?

- I tried to save it in a .pcap file but got the error not a valid file

(Note: what should be an extension of the file)

**Comment by doronz88** [comment]
```shell
pymobiledevice3 pcap outfile.pcap
```

**Comment by prashant1507** [comment]
Thanks .. it generates proper .pcap file
