### ISSUE TITLE
Issue with 'sudo pymobiledevice3 remote tunneld'

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#823]
**Steps  To Reproduce:**

1. Connect a device
2. Run command 'sudo pymobiledevice3 remote tunneld --host 127.0.0.1 --port 8080 -v'
3. Device RSD detail is available
4. tunneld is running 
5. Reboot the device
6. Wait for device to start
7. Device is turned on

**Actual:** The device is not available in `remote tunneld` but its available when running `pymobiledevice3 lockdown get` 

Device Used: iPhone 12 Pro Max 17.0.3

In Verbose logs it says -> removed interface when device is restarting but never adds again
Also, the issue is  random .... like reproducible 7 times out of 10 times

Also if I run sudo pymobiledevice3 remote start-tunnel then randomly getting error ... (trying to find the steps)

**Comment by prashant1507** [comment]
Also if I run `sudo pymobiledevice3 remote start-tunnel` then randomly getting error ... (trying to find the steps)

**Comment by doronz88** [comment]
please test #825 to verify if it resolves the issue

**Comment by prashant1507** [comment]
is there any reference you can provide so i can try to build the pip package 
Thanks

**Comment by doronz88** [comment]
Just checkout and install locally using -e

**Comment by prashant1507** [comment]
The fix is working as expected. Thanks .
Will wait for new version :)
