### ISSUE TITLE
[Need Help] Need help with `pymobiledevice3 webinspector js-shell`

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#824]
Hi,

What I am trying to achieve?
- Open Safari (not the Remote Automation)
- Open URL

Using `pymobiledevice3 webinspector js-shell` I need to choose the tab/window and then type `window.location = 'https://www.github.com'`

I want to do the above steps by passing `window.location = 'https://www.github.com'` along with the command and wait for some seconds and once page is loaded return the output 

Please suggest me how can I achieve this 
Thanks 

What I tried ? 
To simulate enter key to select first id, `echo '\n' | pymobiledevice3 webinspector js-shell` and similar using expect but getting exception 
`termios.error: (25, 'Inappropriate ioctl for device'`

**Comment by doronz88** [comment]
we currently don't have an optional `EVALUATE_EXPERSSION` (PRs are always welcome)
you can also achieve this by writing your own python script using our API

**Comment by prashant1507** [comment]
Can you please share a sample python code to use js-shell 

I was trying to find the right Class and function but seems doing some mistakes and getting exception like InvalidService

**Comment by doronz88** [comment]
In general, the cli module acts as the base of all examples:
https://github.com/doronz88/pymobiledevice3/blob/20cbb184d92fef9da716cb525e073137b8d07edf/pymobiledevice3/cli/webinspector.py#L229

**Comment by prashant1507** [comment]
Hi,
I tried but now my execution just hangs and never terminates 

  ```
  async def open_url_using_js_shell():
      lockdown = create_using_usbmux(serial)
      inspector = WebinspectoreService(lockdown)
      inspector.connect(timeout=40)
      safari = inspector.open_app(SAFARI)
      reload_pages(inspector)
      available_pages = list(inspector.get_open_pages('Safari', []))
      page = available_pages[0]
      session_protocol = SessionProtocol(inspector, safari.id_, safari, page)
      inspector_session = InspectorSession(session_protocol)
      inspector_js_shell = InspectorJsShell(inspector_session)
  
      # Try 1
      asyncio.run(inspector_js_shell.navigate('www.google.com'))
  
      # Try 2
      # asyncio.run(inspector_js_shell.evalute_expression('window.location = "www.google.com"'))\
  
      # Try 3
      # async with inspector_js_shell.create(lockdown, 10, SAFARI) as js:
      #     await js.start(www.google.com)
```

Please can you help me to find out where I m doing wrong . (Manage await)

Thanks

**Comment by prashant1507** [comment]
For now I'm able to achieve this using expect script

```
set stty_int "-echo"
set timeout 10
spawn pymobiledevice3 webinspector js-shell --udid SERIAL
expect "js>"
sleep 2
send "\r"
sleep 5
send "window.location = 'https://www.github.com'
sleep 3
send "\r"
sleep 7
expect eof
puts 'URL Opened Successfully'

```

`expect script_name.exp`
