### ISSUE TITLE
[Need Help] wintun tunnel was immediately closed

### ISSUE THREAD

**Issue by chang-chih-yao** [doronz88/pymobiledevice3#832]
**Test environment**
- Windows 10 22H2 (19045.3930)
- iPhone 14 pro, iOS 17.2

**Describe the bug**
After the Wintun tunnel was established, it was immediately closed.

**To Reproduce**
1. pymobiledevice3 remote start-tunnel

**Logs**
02-13 13:04:27 -          wintun - WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
02-13 13:04:27 -          wintun - WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.
02-13 13:04:27 -          wintun - use existing WeTestUsbFilter driver.
02-13 13:04:27 -          wintun - use existing WeTestUsbNcm driver.
02-13 13:04:33 -          wintun - Failed to find matching adapter name: 元素找不到。 (Code 0x00000490)
02-13 13:04:40 -          wintun - Waiting for existing driver to unload from kernel
02-13 13:06:13 -          wintun - Failed to unload existing driver, which means a reboot will likely be required
02-13 13:06:13 -          wintun - Removing existing driver 0.14
02-13 13:06:13 -          wintun - Installing driver 15.14
02-13 13:06:13 -          wintun - Extracting driver
02-13 13:06:13 -          wintun - Installing driver
02-13 13:06:14 -          wintun - Creating adapter
02-13 13:06:14 -          wintun - tunnel created
fd26:db18:f1db::1 56092
02-13 13:06:14 -          wintun - tunnel was closed
02-13 13:06:15 -          wintun - Removed orphaned adapter "wintun 1"

**Additional context**
1. This windows device had previously installed the iAnyGo software (iOS 17).
2. The log "02-13 13:06:13 -          wintun - Failed to unload existing driver, which means a reboot will likely be required" , I had already rebooted my computer many times.

**Comment by doronz88** [comment]
As all tunneld been completely refactored, I'm closing this issue now. Feel free to reopen if the issue persists on latest release
