### ISSUE TITLE
Can't start tunneld on Windows

### ISSUE THREAD

**Issue by Vercixx** [doronz88/pymobiledevice3#833]
**Test environment**
- Host OS version. Windows 10 22H2
- Target device model and iOS version. iPhone 12 mini, iOS 17.2.1

**Describe the bug**
Trying to start tunneld on Windows, but it gives an error

**To Reproduce**
1. Open 'Run as Administrator' terminal
2. Run `python3 -m pymobiledevice3 remote rsd-info --tunnel ''`
3. Get the error message

**Expected behavior**

**Logs**
```
C:\Windows\system32>python3 -m pymobiledevice3 remote rsd-info --tunnel ''
2024-02-15 20:43:02 DESKTOP-I7LAC44 __main__[19012] ERROR Device is not connected
```

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Starting a tunneld is done by:

```shell
pymobiledevice3 remote tunneld
```
