### ISSUE TITLE
[BUG?] Can't read output from `start-server` when using pymobiledevice3 programatically

### ISSUE THREAD

**Issue by wojciech-kulik** [doronz88/pymobiledevice3#849]
I'm using this command programatically:
```
pymobiledevice3 developer debugserver start-server 65123 --udid SOME_ID 
```

However, for some reason I don't receive any stdout/stderr. 

I started investigating the problem and it turns out that if I call from CMD:
```
pymobiledevice3 developer debugserver start-server 65123 --udid SOME_ID > output.txt
```
The file is empty until I kill the process.

Any idea if it is possible to flush the output before killing the process? I'm not sure why it's not producing it before, even though I can see it from CLI. Maybe the main thread is frozen?

For a different command that behaves similarly, it works as expected:
```
sudo pymobiledevice3 remote start-tunnel > output.txt
```
The `output.txt` is updated as soon as it appears.

**Comment by doronz88** [comment]
Can you test if `sys.stdout.flush()` fixes the problem? If it does, please submit a PR :)

**Comment by wojciech-kulik** [comment]
It worked :) I created PR.
