### ISSUE TITLE
Feature Request: Homebrew distribution

### ISSUE THREAD

**Issue by wojciech-kulik** [doronz88/pymobiledevice3#854]
Would you consider providing this tool via Homebrew? 
Most people on macOS use this package manager and it's easy to track updates having one source of dependencies.

Thank you in advance.

**Comment by doronz88** [comment]
I'm not what is the best way to achieve this. I guess I could make this repository brew-tap-compliant, but then the best way would be to install pymobiledevice3 in a venv to not mess up with other user packages. Maybe it's very simple, but I'm not familiar enough with everthing that is required to achieve this.
If you are willing to submit a PR that makes this possible I'll be more then happy to merge it :)

**Comment by wojciech-kulik** [comment]
To be honest I'm not sure either how to distribute via Homebrew. Maybe we'll find someone who has a knowledge in this matter :D. Also, I'm not familiar with python, so I'm not sure what could it break and how it should be configured.

**Comment by doronz88** [comment]
It's always nice to learn new stuff. Today I learned how to create my own tap and create a github action that can automatically deploy my package to it 😁

https://github.com/doronz88/pymobiledevice3?tab=readme-ov-file#installation

**Comment by wojciech-kulik** [comment]
Wow! Seriously, you are rocket-fueled 🚀 Thank you for your amazing work!

**Comment by wojciech-kulik** [comment]
@doronz88 I tried switching to homebrew but I get some errors:

```
╰─ pymobiledevice3 version
Traceback (most recent call last):
  File "/opt/homebrew/bin/pymobiledevice3", line 5, in <module>
    from pymobiledevice3.__main__ import main
  File "/opt/homebrew/Cellar/pymobiledevice3/2.43.8/libexec/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by doronz88** [comment]
Okay, after researching more about it I arrived at the following:

https://docs.brew.sh/Python-for-Formula-Authors

> **Homebrew generally won’t accept libraries that can be installed correctly with pip install foo**. Bindings may be installed for packages that provide them, especially if equivalent functionality isn’t available through pip. Similarly, libraries that have non-trivial amounts of native code and have a long compilation as a result can be good candidates. If in doubt, though: do not package libraries.
**Applications should unconditionally bundle all their Python-language dependencies and libraries and should install any unsatisfied dependencies; these strategies are discussed in depth in the following sections.**

This makes this approach non-relevant since it means it woun't manage my dependencies as `pip` does - making it much harder to maintain

**Comment by wojciech-kulik** [comment]
Understandable, so maybe in this case we should abandon the idea of Homebrew distribution
