### ISSUE TITLE
The process 'python3' returned unexpected output

### ISSUE THREAD

**Issue by Niraj61** [doronz88/pymobiledevice3#857]
**Test environment**
- Host OS version.
- Target device model and iOS version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
That is not a clear and concise issue
