### ISSUE TITLE
[Critical] Fail to execute developer command even on providing rsd details

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#868]
**Steps:**
1. Start RSD either using start-tunnel or tunneld as sudo
2. Run pymobiledevice3 developer screenshot x.png --rsd XXXXX XXXXX

**Actual:** getting error failed to start service possible reasons are: for iOS >=18.0 provide --rsd ......
**Expected:** Should take screenshot

**Comment by doronz88** [comment]
The correct command is `pymobiledevice3 developer dvt screenshot` on ios 17

**Comment by prashant1507** [comment]
thanks. i missed the dvt part 
sorry for the confusion
