### ISSUE TITLE
Device is not connected

### ISSUE THREAD

**Issue by coder-woo** [doronz88/pymobiledevice3#872]
Using the "usbmux list" can discover devices, but using "start-tunnel" report "ERROR Device is not connected"
Where are the possible issues? Thank you!!

**Test environment**
- Host OS version. 
Ubuntu 20.04.4 LTS
- Target device model and iOS version.
 iOS-17.3.1

logs:
root@ubuntu:/home/wutao# pymobiledevice3 usbmux list
[
    {
        "BuildVersion": "19E258",
        "ConnectionType": "USB",
        "DeviceClass": "iPhone",
        "DeviceName": "tao\u7684iPhone",
        "Identifier": "00008101-000A3C210CE0001E",
        "ProductType": "iPhone13,2",
        "ProductVersion": "15.4.1"
    },
    {
        "BuildVersion": "21D61",
        "ConnectionType": "USB",
        "DeviceClass": "iPhone",
        "DeviceName": "Woo",
        "Identifier": "00008130-000A710E3AF2001C",
        "ProductType": "iPhone16,2",
        "ProductVersion": "17.3.1"
    }
]

root@ubuntu:/home/wutao# python3 -m pymobiledevice3 remote start-tunnel
2024-03-04 16:44:31 ubuntu __main__[3435] ERROR Device is not connected

**Comment by doronz88** [comment]
Duplicate #566
