### ISSUE TITLE
pymobiledevice3: command not found

### ISSUE THREAD

**Issue by beckietech** [doronz88/pymobiledevice3#88]
**Test environment**
- Host OS version. Debian 9 Stretch
- Target device model and iOS version. iOS14.6 on iPhone XR

**Describe the bug**
This is great project and I looked up pymobiledevice and found this project:
followed installation using pip install successful, but got pymobiledevice3: command not found

and I also tried in cmd line and got the following commands, I dont know if it's installed right?
py3clean            pycompile           pyfilerelay         pymobilebackup      python2.7           python3.5m-config
py3compile          pydeviceinfo        pygettext           pymobilebackup2     python2.7-config    python3-config
py3versions         pydiagnosticsrelay  pygettext2.7        pymobileconfig      python2-config      python3m
pyafc               pydoc               pygettext3          pypcapd             python3             python3m-config
pyappsmanager       pydoc2.7            pygettext3.5        pyscreenshotr       python3.5           python-config
pybuild             pydoc3              pyhousearrest       python              python3.5-config    pyversions
pyclean             pydoc3.5            pylockdown          python2             python3.5m   

Any ideas is welcomed, thanks!

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

**Comment by matan1008** [comment]
Thanks for the review!
What version of click did you install?
Do you use Bash, Zsh or Fish?

**Comment by doronz88** [comment]
First of all - that's not how you submit a bug report. The template is there to guide you to give all the important information so we can understand the bug you are issuing. What you posted achieves the opposite.

Anyhow, I'm guessing (just by reading your title, because the rest is unreadable) your problem is that the python binary directory isn't in your user's PATH. On my mac it's
```
~/Library/Python/3.9/bin
```

**Comment by beckietech** [comment]
> Thanks for the review!
> What version of click did you install?
> Do you use Bash, Zsh or Fish?

I use bash, thanks, but I also have trouble figuring out the following:
# python-click<8.0
eval "$(_PYMOBILEDEVICE3_COMPLETE=source_zsh pymobiledevice3)"
# python-click>=8.0
eval "$(_PYMOBILEDEVICE3_COMPLETE=zsh_source pymobiledevice3)"

**Comment by beckietech** [comment]
> First of all - that's not how you submit a bug report. The template is there to guide you to give all the important information so we can understand the bug you are issuing. What you posted achieves the opposite.
> 
> Anyhow, I'm guessing (just by reading your title, because the rest is unreadable) your problem is that the python binary directory isn't in your user's PATH. On my mac it's
> 
> ```
> ~/Library/Python/3.9/bin
> ```

Thank you, after adding python to path, I can run pymobiledevice3 with following error:
pymobiledevice3
Traceback (most recent call last):
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pymobiledevice3 1.2 (/home/beckibox/.local/lib/python3.5/site-packages), Requirement.parse('pymobiledevice3==1.9.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pymobiledevice3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 770, in resolve

May I know what am I missing? Thanks

**Comment by doronz88** [comment]
> I use bash, thanks, but I also have trouble figuring out the following:

You can just change `zsh` to `bash` for bash to work.
This is also just for autocompletion and not mandatory.

Please read about markdown before posting any more replies so your replies are readable.

**Comment by doronz88** [comment]
> > First of all - that's not how you submit a bug report. The template is there to guide you to give all the important information so we can understand the bug you are issuing. What you posted achieves the opposite.
> > Anyhow, I'm guessing (just by reading your title, because the rest is unreadable) your problem is that the python binary directory isn't in your user's PATH. On my mac it's
> > ```
> > ~/Library/Python/3.9/bin
> > ```
> 
> Thank you, after adding python to path, I can run pymobiledevice3 with following error:
> pymobiledevice3
> Traceback (most recent call last):
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 567, in _build_master
> ws.require(**requires**)
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 884, in require
> needed = self.resolve(parse_requirements(requirements))
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 775, in resolve
> raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (pymobiledevice3 1.2 (/home/beckibox/.local/lib/python3.5/site-packages), Requirement.parse('pymobiledevice3==1.9.1'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/pymobiledevice3", line 6, in
> from pkg_resources import load_entry_point
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3238, in
> @_call_aside
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3222, in _call_aside
> f(*args, **kwargs)
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3251, in _initialize_master_working_set
> working_set = WorkingSet._build_master()
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 569, in _build_master
> return cls._build_from_requirements(**requires**)
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 582, in _build_from_requirements
> dists = ws.resolve(reqs, Environment())
> File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 770, in resolve
> 
> May I know what am I missing? Thanks

Seems like you have two different installations of `pymobiledevice3` (1.2 and 1.9.1).
You need to uninstall the other one.

```shell
python3 -m pip uninstall pymobiledevice3
```

And make sure `pymobiledevice3` can no longer be imported before trying to reinstall.

**Comment by beckietech** [comment]
> > > First of all - that's not how you submit a bug report. The template is there to guide you to give all the important information so we can understand the bug you are issuing. What you posted achieves the opposite.
> > > Anyhow, I'm guessing (just by reading your title, because the rest is unreadable) your problem is that the python binary directory isn't in your user's PATH. On my mac it's
> > > ```
> > > ~/Library/Python/3.9/bin
> > > ```
> > 
> > 
> > Thank you, after adding python to path, I can run pymobiledevice3 with following error:
> > pymobiledevice3
> > Traceback (most recent call last):
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 567, in _build_master
> > ws.require(**requires**)
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 884, in require
> > needed = self.resolve(parse_requirements(requirements))
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 775, in resolve
> > raise VersionConflict(dist, req).with_context(dependent_req)
> > pkg_resources.VersionConflict: (pymobiledevice3 1.2 (/home/beckibox/.local/lib/python3.5/site-packages), Requirement.parse('pymobiledevice3==1.9.1'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/usr/local/bin/pymobiledevice3", line 6, in
> > from pkg_resources import load_entry_point
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3238, in
> > @_call_aside
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3222, in _call_aside
> > f(*args, **kwargs)
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 3251, in _initialize_master_working_set
> > working_set = WorkingSet._build_master()
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 569, in _build_master
> > return cls._build_from_requirements(**requires**)
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 582, in _build_from_requirements
> > dists = ws.resolve(reqs, Environment())
> > File "/home/beckibox/.local/lib/python3.5/site-packages/pkg_resources/**init**.py", line 770, in resolve
> > May I know what am I missing? Thanks
> 
> Seems like you have two different installations of `pymobiledevice3` (1.2 and 1.9.1).
> You need to uninstall the other one.
> 
> ```shell
> python3 -m pip uninstall pymobiledevice3
> ```
> 
> And make sure `pymobiledevice3` can no longer be imported before trying to reinstall.

Thank you so much! after uninstalled unnecessaries and reinstall, I finally got it work! Great project!
