### ISSUE TITLE
Failed Simulate Location

### ISSUE THREAD

**Issue by YesidMarin** [doronz88/pymobiledevice3#883]
Hello everybody.

**Test environment**
- MacOS 14.4
- iOS 17.4

**Describe the bug**
I tried to simulate the location by adding the --rsd flag but it didn't work.

**To Reproduce**
1. Set command `python3 -m pymobiledevice3 developer dvt simulate-location set --rsd xxxxxxx::1 XXXXX -- XXXXXX -X.XXX`
**Expected behavior**
Update location in device.

**Logs**

![image](https://github.com/doronz88/pymobiledevice3/assets/29234631/e9d2d17a-0ac8-4d02-b8cc-8dcbf5171870)

**Comment by doronz88** [comment]
Make sure the device is in developer mode
