### ISSUE TITLE
[Need help]call tunneld failed with Python API

### ISSUE THREAD

**Issue by li8911255** [doronz88/pymobiledevice3#885]
def start_tunneld():
    host = TUNNELD_DEFAULT_ADDRESS[0]
    port = TUNNELD_DEFAULT_ADDRESS[1]
    tunneld_runner = partial(TunneldRunner.create,
                             host,
                             port,
                             TunnelProtocol.QUIC.value)
    tunneld_runner()

When I call start_tunneld , always get the error below: 

  File "/Users/leo/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 125, in handle_new_ip
    async with start_tunnel(rsd, protocol=self.protocol) as tun:
  File "/Users/leo/.pyenv/versions/3.11.8/lib/python3.11/contextlib.py", line 212, in __aenter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

So what is the correct way to invoke TunneldRunner.create?

I really appreciate that.

**Comment by doronz88** [comment]
Simply copy the code of `cli_tunneld()`
