### ISSUE TITLE
“Device is not connected” if I run "start-tunnel" twice

### ISSUE THREAD

**Issue by moonlight824** [doronz88/pymobiledevice3#887]
**Test environment**
- Host OS version: win10
- Target device model and iOS version: iphone15 plus, ios 17.1.1

**Describe the bug**
When I run "python -m pymobiledevice remote start-tunnel" first time, it works right and can print rsd info. But if I stop the process and run this command the second time, it will print "Device is not connected". After I replug the device, it will continue the loop: works right at the first time and can not work after the second time.

**To Reproduce**
1. plug in the device
2. run "python -m pymobiledevice3 remote start-tunnel"
3. stop the process
4. run the command agin: it will print "Device is not connected"
5. replug in the device and goto the step 2, continue

**Comment by ValentinAbrutskiZap** [comment]
I have similar issue, But replug help just sometimes

Any workaround?

**Comment by doronz88** [comment]
Checkout latest version. This windows bug was recently fixed
