### ISSUE TITLE
pymobiledevice3 lockdown pair is not working

### ISSUE THREAD

**Issue by StephenDev0** [doronz88/pymobiledevice3#900]
**Test environment**
- Host OS version: macOS 14.3.1
- Target device model and iOS version: iPhone 13 Pro Max iOS 17.2.1

**Describe the bug**
Running pymobiledevice3 lockdown pair does not work

**To Reproduce**
1. Plug in device
2. Run pymobiledevice3 lockdown pair 

**Expected behavior**
The Device should pair

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.
See Photo

**Additional context**
I tried brew python and non brew python.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by StephenDev0** [comment]
<img width="1147" alt="Screenshot 2024-03-31 at 9 50 59 AM" src="https://github.com/doronz88/pymobiledevice3/assets/158498287/4248ca9b-6121-498f-9e77-ddca68317d0c">

**Comment by doronz88** [comment]
That's a very generic SSL error. Please check the device datetime is configured the same as the host. If that doesn't solve, try to remove the pair record from `~/.pymobiledevice3`.

**Comment by doronz88** [comment]
@TheTreeTops I was able to reproduce your error while messing with the pair-records removal on-device. Please verify #901 solves the issue

**Comment by StephenDev0** [comment]
@doronz88 Hey, how do I test that?

**Comment by doronz88** [comment]
```shell
git clone git@github.com:doronz88/pymobiledevice3.git
cd pymobiledevice3
git checkout bugfix/pair-record-removal-on-device
python3 -m pip install -e .
```
