### ISSUE TITLE
Error when using developer commands

### ISSUE THREAD

**Issue by kschernopiatova** [doronz88/pymobiledevice3#908]
**Test environment**
- Host OS version. MacOS 14.4.1
- Target device model and iOS version. iPhone 13Pro, iOS 17.4.1

**Describe the bug**
I started tunnel using `'sudo python3 -m pymobiledevice3 remote tunneld'` command
Then I tried to run `'pymobiledevice3 developer dvt device-information'` with --rsd option
**Expected behavior**
The device information logs in terminal
**Logs**
Error: Illegal usage: `rsd_service_provider_manually` is mutually exclusive with arguments `rsd_service_provider_using_tunneld`.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Couldn't reproduce your issue. Are you using the latest version?
Also, assuming you use `tunneld`, you don't need to specify the RSD option

**Comment by kschernopiatova** [comment]
thank you, just not correctly understood
