### ISSUE TITLE
CLI pymobiledevice3.exceptions.InvalidServiceError turns into "Error: No such option: --tunnel" on start-tunnel command

### ISSUE THREAD

**Issue by briankrznarich** [doronz88/pymobiledevice3#913]
See: #912 for most details.

InvalidServiceError exceptions are currently thrown in the presense of older devices on the same host.  In `__main__.py` there is a try/catch that does this:

```
    except InvalidServiceError:
        if '--tunnel' not in sys.argv:
            sys.argv += ['--tunnel', '']
            return main()
        logger.error(INVALID_SERVICE_MESSAGE)
```

Except that if `--tunnel` is not a valid argument for the command being invoked (as it isn't for the `start-tunnel` command), the arg parsing library takes over and just prints:

```
$ sudo python3 -m pymobiledevice3 remote start-tunnel
Usage: python -m pymobiledevice3 remote start-tunnel [OPTIONS]
Try 'python -m pymobiledevice3 remote start-tunnel -h' for help.

Error: No such option: --tunnel
```

**Comment by doronz88** [comment]
Nice catch. What solution do you advise to treat this? I thought about blacklisting the `remote` command group

**Comment by briankrznarich** [comment]
Blacklisting incompatible commands, of course, would solve the immediate issue.

Alternatively, if it's true that `(almost) all of pymobiledevice3 accept an additional --rsd/--tunnel` , then maybe just add `--tunnel` to the remaining commands and make it a no-op. (this has error-swallowing consequences though, as we've seen)

An upside is that users don't have to give any thought to the "special" commands where that arg is invalid.  Just define `--tunnel` as "use rsd tunnel if applicable`.  

However since you asked, I'm not sure I like the behavior of magically falling from one error path into another.  I totally get why you did it, and I might have done it too.   Still, as has been noted, pymobiledevice3 probably should avoid rsd with <= iOS16.  Now, if iOS16 triggers an InvalidServiceError exception for any reason, pymobiledevice3 is going to push it into the RSD path, and the user will end up with some other unrelated error, and probably lose the original stack trace. (pymobiledevice3 could of course log it, but if a stack-trace appears before retrying with --tunnel, no one will like that)

In my case I'm specifically not using tunneld.  So `--tunnel` would never work for me anyway.

I'm biased because I work with a lot of older devices for testing, and I would definitely want a way to say "if this fails, don't try the tunnel option".  Auto-adding `--tunnel` almost necessitates a parallel option `--no-tunnel` to stop that from happening.  Having nothing to do with pymobiledevice3, iOS devices fail for lots of reasons, and anything that obscures the underlying error just makes troubleshooting more difficult.

I'm afraid I don't know the entire rationale for auto-adding `--tunnel`, so I may be overlooking something significant here.  For what I'm doing, I just switch on iOS version.  >=17.0 I create a tunnel with `start-tunnel` and use rsd calls,  <17 I don't.  This check is scripted.  I included a "force" option to try RSD on 16.x, but I've never had a reason to use it. The "old ways" seem to still work fine on older devices.

It seems like pymobiledevice3 could do the same iOS version check, but if it doesn't I just assume there are good reasons for that.  People have different use cases than I do.

I'm just musing since you asked.  Whatever seems good to you I'm pretty sure I can work with.

**Comment by doronz88** [comment]
The problem is I don't want to validate the device version in the argparse level and find the correct course of action accordingly. Explicit is always better, but since too many people are having trouble figuring out how things connect I decided on this implicit approach. I does add some "voodoo" into the command handling, so instead I'll later add a refactor to just try it for the developer commands (whitelist) and modify the developer help about this behavior
