### ISSUE TITLE
Fix in #913 is unreachable?  --tunnel defaults to "" as long as "--rsd" not specified

### ISSUE THREAD

**Issue by briankrznarich** [doronz88/pymobiledevice3#916]
I was trying to reproduce the test/logic in __main__ that I brought up in #913 before submitting a PR for #912. I was working towards triggering this logic to make sure I hadn't broken anything:
```
    except InvalidServiceError:
        if 'developer' in sys.argv and '--tunnel' not in sys.argv:
            sys.argv += ['--tunnel', '']
            return main()
        logger.error(INVALID_SERVICE_MESSAGE)
```
But even commenting the whole block out, I couldn't get pymobiledevice3 to *not* connect to `tunneld`.  It didn't matter whether I passed the `--tunnel` argument or not, it would unconditionally connect.   In other words, dynamically adding  `['--tunnel', '']` and retrying will never have any effect.

I had to dig around, and eventually found the default set here:
```
#./pymobiledevice3/cli/cli_common.py
    def handle_parse_result(self, ctx, opts, args):
        if (isinstance(ctx.command, RSDCommand) and not (isinstance(ctx.command, Command)) and
                ('rsd_service_provider_using_tunneld' not in opts) and ('rsd_service_provider_manually' not in opts)):
            # defaulting to `--tunnel ''` if no remote option was specified
            opts['rsd_service_provider_using_tunneld'] = ''
```

Am I missing something?

Example command:
`python3 -m pymobiledevice3 developer core-device list-apps`

**Comment by doronz88** [comment]
Looks like something else is wrong in your enviroment. Tunneld isn't accessed unless it's asked to

**Comment by briankrznarich** [comment]
When you run `python3 -m pymobiledevice3 developer core-device list-apps` on your machine, what happens? I get:
`ERROR Unable to connect to Tunneld. You can start one using:
sudo python3 -m pymobiledevice3 remote tunneld`

Which is odd, because I didn't use `--tunnel ""`

The code I quoted previously appears to default "--tunnel" to [empty string].  I traced debug the code into `tunneld()`, and got here:

```
  def tunneld(self, ctx, param: str, udid: Optional[str] = None) -> Optional[RemoteServiceDiscoveryService]:
        if udid is None:  #<--------
            return

        rsds = get_tunneld_devices()
        if len(rsds) == 0:
            raise NoDeviceConnectedError()

        if udid != '':
```

Where I put the arrow `#<---------`, udid was the empty string, exactly as set in `cli_common.py`.  It was not `None`, so the code ran. 

My environment is just a `git clone` of this repo, I'm not sure what would be strange about it.

**Comment by briankrznarich** [comment]
Small update... That message appears even when no devices are plugged into the machine.

```
~/git/master.old/pymobiledevice3$ git log |head -n 6
commit 969ab090968d111d928ab710c7dae142626aa97b
Merge: 185c263 4c64292
Author: doronz88 <doron88@gmail.com>
Date:   Sun Apr 7 08:53:12 2024 +0300

    Merge pull request #915 from doronz88/bugfix/tunneld-get-prohibited
~/git/master.old/pymobiledevice3$ git diff
~/git/master.old/pymobiledevice3$ idevice_id
~/git/master.old/pymobiledevice3$ python -m pymobiledevice3 usbmux list
[]

~/git/master.old/pymobiledevice3$ python3 -m pymobiledevice3 developer core-device list-apps
2024-04-08 11:49:29 Brians-MacBook-Air.local __main__[3801] ERROR Unable to connect to Tunneld. You can start one using:
sudo python3 -m pymobiledevice3 remote tunneld
~/git/master.old/pymobiledevice3$ python3 -m pymobiledevice3 developer core-device list-apps --tunnel ""
2024-04-08 11:49:37 Brians-MacBook-Air.local __main__[3802] ERROR Unable to connect to Tunneld. You can start one using:
sudo python3 -m pymobiledevice3 remote tunneld
```

**Comment by doronz88** [comment]
That is the expected behavior. You requested a developer device which is not availble on usbmux

**Comment by briankrznarich** [comment]
We are saying the same thing back and forth to each other 😂  Yes, I asked for a `developer` command, so it automatically defaulted to `--tunnel ""`.  Now look at this:

```
if 'developer' in sys.argv and '--tunnel' not in sys.argv:
            sys.argv += ['--tunnel', '']
            return main()
```

Your recent commit added `developer' in sys.argv and ...`.  You only add `['--tunnel', '']` for `developer` commands.  Which already have `--tunnel ""` by default.  Which is the expected behavior.  So this block of code doesn't do anything.

I'm going to feel quite embarrassed if I am missing something here...

**Comment by doronz88** [comment]
I'm totally confused. What are you running? what error are you getting?

**Comment by briankrznarich** [comment]
I am not getting an error.   To be clear, what I am suggesting is that you delete that block of code entirely.  I'm suggesting that it appears to have absolutely no effect. 

This is my question to you: Even if you could get into that `if` statement, what do you expect it do?  `--tunnel ""` is **already the default** for all `developer` commands.  Only `developer` commands can get into the `if` statement.

===
Why am I reporting this?   

In my PR I was changing how/when `InvalidServiceError` exceptions were being thrown.  This line in `main` is the only place `InvalidServiceError` is specifically handled.  I wanted to generate a test to validate that I had not broken the existing code. 

I eventually realized the code does nothing, so I couldn't test it.

 I think your change in March adding 
```
            # defaulting to `--tunnel ''` if no remote option was specified
            opts['rsd_service_provider_using_tunneld'] = ''
```
has made it obsolete.

**Comment by doronz88** [comment]
If I remove this if statement then I get:

```
user@users-MacBook-Pro ~/dev @ pymobiledevice3 developer dvt ls /
2024-04-09 14:16:00 users-MacBook-Pro.local pymobiledevice3.__main__[63515] ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
          https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

- Apple removed this service

- A bug. Please file a bug report:
  https://github.com/doronz88/pymobiledevice3/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
```

Instead, I want the users to have an easier life and not needing to pass this option for the developer commands

**Comment by briankrznarich** [comment]
Sorry for taking so much of your time on this.    I did not realize the distinction between `RSDCommand` and `Command`, and that the default of `""` that I noticed only applies to certain developer commands, but not others.  I should have figured that out on my own.

I figured you probably knew what you were doing, I just didn't understand what I was missing.  😅　I appreciate your patience.
