### ISSUE TITLE
Windows does not support multiple tunnel initiation, but mac does

### ISSUE THREAD

**Issue by cyrilchans** [doronz88/pymobiledevice3#920]
Hi，On Windows, it's always the same interface :wintun, while on mac, the interface is digitally overlaid, like untun7, untun8.  As a result, only one tunnel can be opened on Windows forever, and macos can open multiple tunnels.  Can you solve the problem that only one tunnel can be opened on Windows
win：
![window](https://github.com/doronz88/pymobiledevice3/assets/74752545/83985564-3fe0-4742-8f58-2e0580f5ff7c)
mac：
<img width="982" alt="mac" src="https://github.com/doronz88/pymobiledevice3/assets/74752545/6098de0a-dde8-4601-8c91-ff0304f0a764">

**Comment by doronz88** [comment]
Can you please verify if #922 solves the issue?

**Comment by cyrilchans** [comment]
I'm sorry this branch failed to run on my side
![企业微信截图_17127200133901](https://github.com/doronz88/pymobiledevice3/assets/74752545/e9d0086a-028e-4f78-9052-8e148ccb7dc2)
I modified the source code of 3.3.1 by referring to the code you submitted. But when the second tunnel starts, the first tunnel reports an error and ends
![error1](https://github.com/doronz88/pymobiledevice3/assets/74752545/60b52b4b-aa11-443b-ad2d-13f30c99fbab)

![error2](https://github.com/doronz88/pymobiledevice3/assets/74752545/79282f6e-9aa2-47a9-8b38-802e4b555623)

**Comment by cyrilchans** [comment]
Hopefully Windows can support multiple tunnels like mac

**Comment by doronz88** [comment]
I checked and it is possible, but will require someone to wrap `wintun.dll` using python. I created a template project and referenced. Hopeful someone will one day make it happen:

https://github.com/doronz88/pymobiledevice3/issues/818

Till then we wait

**Comment by doronz88** [comment]
I'm pretty sure this PR solves this issue aswell.
@cyrilchans can you verify?

https://github.com/doronz88/pymobiledevice3/pull/924

**Comment by cyrilchans** [comment]
Super-duper, I have verified that the windows now allows multiple tunnels, Thanks

**Comment by cyrilchans** [comment]
Super cool, I have verified that the windows now allows multiple tunnels, Thanks
