### ISSUE TITLE
Can I run this library for multiple devices using UDID of iOS device

### ISSUE THREAD

**Issue by tyrocoding** [doronz88/pymobiledevice3#93]
How can I run the pymobiledevice3 on all attached devices to machine using UDID ?

**Comment by doronz88** [comment]
Simultaneously or selecting a specific one to work on?

**Comment by tyrocoding** [comment]
Yes Simultaneously. Basically I am trying to run `pymobiledevice3 developer dvt sysmon process single` to get resource usage stats.

**Comment by doronz88** [comment]
We don't have this feature, but you can implement this one programatically:

```python
from pymobiledevice3 import usbmux
from pymobiledevice3.lockdown import LockdownClient

mux = usbmux.USBMux()
mux.process()
for device in mux.devices:
    # iterate all connected devices
    udid = device.serial
    lockdown = LockdownClient(udid)
    
    with DvtSecureSocketProxyService(lockdown=lockdown) as dvt:
        with Sysmontap(dvt) as sysmon:
            for process_snapshot in sysmon.iter_processes():
                print(process_snapshot)  # just print each process
```

**Comment by tyrocoding** [comment]
> We don't have this feature, but you implement this one programatically:
> 
> ```python
> from pymobiledevice3 import usbmux
> from pymobiledevice3.lockdown import LockdownClient
> 
> mux = usbmux.USBMux()
> mux.process()
> for device in mux.devices:
>     # iterate all connected devices
>     udid = device.serial
>     lockdown = LockdownClient(udid)
>     
>     with DvtSecureSocketProxyService(lockdown=lockdown) as dvt:
>         with Sysmontap(dvt) as sysmon:
>             for process_snapshot in sysmon.iter_processes():
>                 print(process_snapshot)  # just print each process
> ```

Thank you I will give a try.
