### ISSUE TITLE
Lockdown SavePairRecord

### ISSUE THREAD

**Issue by nanoscopic** [doronz88/pymobiledevice3#956]
**Is your feature request related to a problem? Please describe.**
On MacOS lockdown.py saves pair records directly to disk instead of properly storing them "within usbmuxd" using the SavePairRecord usbmuxd request. This can result in needing to pair multiple times.

**Describe the solution you'd like**
Save the pair request properly using SavePairRecord.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by nanoscopic** [comment]
See https://github.com/libimobiledevice/libusbmuxd/blob/a7f0543fb1ecb20ac7121c0fd77297200e0e43fc/src/libusbmuxd.c#L813 for an example.

**Comment by doronz88** [comment]
Pymobile saves it to both usbmuxd and to disk. The second prompt is probably because of the remotexpc pairing which is a seperate record entirely

**Comment by nanoscopic** [comment]
Nevermind I see that it does do it. I was looking in the wrong place. I will only add that it's a little confusing that this only happens when the device was paired using pmd3. If you pair with idevicepair the local cached copy does not appear.

Is there a reason to create the extra copy in .pmd3 folder on MacOS?
