### ISSUE TITLE
GPL 3.0 Compliance

### ISSUE THREAD

**Issue by nanoscopic** [doronz88/pymobiledevice3#972]
This project does not appear to adhere to or possibly be protected by the license set within GitHub of "GPL 3.0".
Please correct the issues as the jeopardize the proper open source nature of the project.

As per the GPL 3.0 license:
"Developers that use the GNU GPL protect your rights with two steps... 1. Assert Copyright" No Copyright is asserted within this project as it should be. Copyrights from the original base project of "Copyright (c) 2012-2014 "dark[-at-]gotohack.org"" have been removed. Who is asserting Copyright of the project and what is their legal identity and country of origin? Without such assertion the license itself states it doesn't apply.

"The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices"."
The Copyright notices and license notices in each file by original pymobiledevice have been removed. This violates the license. They must be put back.

"If the work has interactive user interfaces, each must display
    Appropriate Legal Notices"
Help output from the CLI program should display a notice.

As per the license of original pymobiledevice, you must cease use of original licensed GPL 3.0 work if you do not resolve these issues within 30 days. Now... I'm not the Copyright holder of the original project, so this technically doesn't apply, but I'd suggest resolving this anyway.

**Comment by nanoscopic** [comment]
This commit broke the license: https://github.com/doronz88/pymobiledevice3/commit/89286b4427f05f393c434871d5f26138bb490b92

"GotoHack" is a real person. Their name is clear: "Mathieu Renard". Mathieu is asserting Copyright.

A bit of investigation shows he worked or works for a French company "SOGETI-ESEC", as so the jurisdiction and validity of the original Copyright is mostly clear.

**Comment by doronz88** [comment]
The original author already agreed there is no violation.
1. He created the issue: https://github.com/doronz88/pymobiledevice3/issues/143
2. I created a PR asking for his approval if it was okay: https://github.com/doronz88/pymobiledevice3/pull/144

This license change is a literal copy-paste from what the original author requested

**Comment by doronz88** [comment]
If I understand correctly, you are asking to include copyright notice within the `--help` command, right?
Or should I also include a small header in each file detailing who has contributed to it?

**Comment by nanoscopic** [comment]
I'm not actually clear whether CLI commands require the notice or not. I think it might be a good idea but that isn't the main thing I am asking for.

I can also make the changes and submit a PR for it if you like.

The main change I want is just the Copyright notices returned for ca.py, usbmux.py and lockdown.py

For ca.py:
```
# Copyright (c) 2012-2023 Mathieu Renard
# License GPL 3.0
```

For usbmux.py:
```
# Copyright (c) 2009 Hector Martin "marcan" <hector@marcansoft.com>
# License GPL 3.0
```

For lockdown.py:
```
# Copyright (c) 2012-2023 Mathieu Renard
# License GPL 3.0
```

These are the only remaining files that are definitely mostly forks of the original work.

For the rest of the files, I'm asking you to place some Copyright at the top of each file. Such as:
```
# Copyright (c) 2024 doronz <something@somewhere.com>
# License GPL 3.0
```

Since I have now forked your project, I want this so I can put the notices crediting you for your work in.
I have added many bits now in AGPL 3.0, so my fork is now AGPL 3.0 overall.
Since I'm mixing in derivatives of your work, I need to at least place these notices in each file that is a derivative of your work.

If you don't want to put Copyright notices in each file, that's likely fine, but you need to at least say somewhere ( such as the readme somewhere ) that you do in fact claim Copyright for your work.

In some countries you "gain Copyright automatically" without having to explicitly state it, but it depends on your nationality. This is why I am complaining it is unclear where you are from, because you aren't actually "asserting Copyright".

If you are willing, I'd prefer to be able to actually refer to you by your name instead of "doronz", but I'm assuming you are intentionally staying anonymous for some reason. You can still assert Copyright anonmously, but you should at the very least provide some way to contact you.

I can appreciate removing the huge blocks of junk at the tops of files, but any Copyright notice that was there originally needs to stay in the derivative works.

It's possible you can assert Copyright with just "doronz" by itself, but if you do that at least please state what country you are asserting Copyright in. I have no way to verify it, so you can just state USA I guess. I just want something to be able to reasonably understand what law is governing this work.

**Comment by nanoscopic** [comment]
The request for the original author to "upgrade to GPL 3.0" may or may not even be legitimate by itself. I of course prefer to have GPL 3.0 since it is what enables me to make AGPL 3.0 additions.

For it to move from GPL 2.0 to 3.0 permission would have had to been given by all the original contributors. It's unclear if that actually occurred. Just accepting a merge proves nothing.

Let's assume at the moment that it was actually legally moved to GPL 3.0.

Even with that, that doesn't give the ability to remove the Copyright attribution of the original authors. Those have to stay unless the authors actually legally assign Copyright to you with a signed document. It's certainly not sufficient for them to have accepted a merge of removing the Copyright notice, as it is clear who they are by their Github commits ( they are stating their real names )

I certainly don't believe they transferred Copyright of their work to you.

**Comment by doronz88** [comment]
Just created a PR specifying the original authors. I've included myself since these files went though huge refactors over time.
Does it look okay? If so, I'll just add other headers for the people that have mostly written all these parts (some enitre modules for example were submitted through a PR)

**Comment by doronz88** [comment]
Also, if it's just enough to include them in the README just by names it would be much less of a hassle

**Comment by nanoscopic** [comment]
README is sufficient.

I've added notices in the same style you have to match how you added your Copyright. See https://github.com/dryark/py_ios_rsd_tunnel/commit/270fbd68eed05126254b6b3488d1e4ee51aadc2b

It is all imperfect due to other people sending in PRs. I agree they own Copyright on their portions, and in theory they would need to be consulted on any attempt to change license. That is why projects use a CLA.

It is sufficient from my perspective just to have some easy trail to the primary authors.

Thank you for making these adjustments.

To my knowledge the majority of the iOS 17 work was done by you and thank you for that as well. You've done a lot more than just refactor.

**Comment by nanoscopic** [comment]
By the way, my intended path now ( which is not going to be done anytime soon ) is to:
1. Change the license on iosif to AGPL 3.0 https://github.com/dryark/iosif
2. Port iosif to use libusbmuxd
3. Adapt portions of py_ios_rsd_device to C to extent iosif to work with iOS 17 devices

This is all pretty hopeful and imaginative, but is what I want to do. I just have a ton of work to do besides this...

You are welcome to utilize whatever changes you may like and want to use in py_ios_rsd_device, just be aware that I've put my additions into AGPL 3.0 to ensure my competitors don't take the work, improve it, and use it to compete with me. As long as they actually contribute back improvements I'm okay with AGPL 3.0 for what I can reasonably contribute to the community.

I have now placed py_cf_mdns into AGPL 3.0 for example, which is my minimal code that implements mdns quickly without using something slow and gigantic like Zeroconf. https://github.com/dryark/py_cf_mdns/

**Comment by doronz88** [comment]
Thanks for explaining the required steps for requirement. Feel free to reopen the issue if you believe these are other required steps.

And yeah, all the R&D regarding iOS 17 modifications to the DDI and the tunnel service was my own.

**Comment by nanoscopic** [comment]
Thank you for figuring that stuff out. Having spent all too much time myself fiddling with lockdown and trying to understand all the possible options I can sympathize with how massively difficult / painful it is to do any of this.

Someone has to do all of this stuff first and be willing to share what they learned, and it has been a continual battle as most companies don't want to share any of the useful stuff they figure out.
