### ISSUE TITLE
[Linux] Device not recognized

### ISSUE THREAD

**Issue by aftercares0** [doronz88/pymobiledevice3#977]
**Test environment**
- Debian 12.
- iPad Pro 11 inch 2nd gen running iOS 17.3.1.

**Describe the bug**
pymobiledevice3 does not recognize device

**To Reproduce**
1. Install pymobiledevice3
2. Plug in device
3. Run `sudo pymobiledevice3 remote start-tunnel`

**Expected behavior**
Open a debug tunnel

**Logs**
```
qwerty@local:~/AltServer/iOS17-JIT-WIN $ pymobiledevice3 version
2.35.0
qwerty@local:~/AltServer/iOS17-JIT-WIN $ sudo pymobiledevice3 usbmux list
[
    {
        "BuildVersion": "21D61",
        "ConnectionType": "USB",
        "DeviceClass": "iPad",
        "DeviceName": "iPad (2)",
        "Identifier": "00008027-001E61413A0A402E",
        "ProductType": "iPad8,10",
        "ProductVersion": "17.3.1",
        "UniqueDeviceID": "00008027-001E61413A0A402E"
    }
]

qwerty@local:~/AltServer/iOS17-JIT-WIN $ sudo pymobiledevice3 remote start-tunnel
2024-05-06 04:39:24 local pymobiledevice3.__main__[5485] ERROR Device is not connected
qwerty@local:~/AltServer/iOS17-JIT-WIN $
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
You can either:
- Update to 17.4
- Build your own kernel support: https://github.com/doronz88/pymobiledevice3/issues/566
