### ISSUE TITLE
ERROR Device is not connected when remote start-tunnel via Wi-Fi

### ISSUE THREAD

**Issue by 2088669827** [doronz88/pymobiledevice3#980]
**Test environment**
- Host OS version. macOS Sonoma 14.4.1，Apple M2 Pro.
- Target device model and iOS version. iPhone XR, 17.3.1.

**Describe the bug**
The iPhone is connected to my Mac via Wi-Fi, and I want to start tunnel for further commands such as launch app.
But tunnel started fail and the error shows:
<img width="631" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/5855afea-d3cd-466e-acfd-5a6de3865527">
<img width="630" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/6a0ee7e9-b08e-4f93-bd5d-ad251332a134">

However, it works perfect when I connected with USB cable.
<img width="632" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/1ad4885d-2056-4fee-b580-920e5a9228ce">
<img width="630" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/e54887f0-98ce-4979-a5f3-34036cdfe06b">

**To Reproduce**
1. Connect iPhone to PC with USB
2. Unplug cable
3. Check device connected with pymobiledevice3 usbmux list, "ConnectionType": "Network"
4. sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel, or, sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel -t wifi

**Expected behavior**
Error doesn't apear and tunnel starts successfully.

**Logs**

**Additional context**
1. No error occurs: "python3 -m pymobiledevice3 lockdown wifi-connections on"
2. "sudo /usr/bin/python3 -m pymobiledevice3 remote browse", sometimes it doesn't produce any results for a long time, sometimes it's successful and outputs like this:
<img width="624" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/da6b5a49-606d-499d-8570-bda9beeed5e3">

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
usbmux is completely unrelated to tunneling os iOS < 17.4
Please read the docs
