### ISSUE TITLE
How can the backup and recovery function correctly back up and restore applications？

### ISSUE THREAD

**Issue by shamrock33** [doronz88/pymobiledevice3#982]
How can the backup and recovery function correctly back up and restore applications? I find that the backup file is indeed the content of the application, but the application does not appear on the phone after recovery

**Comment by doronz88** [comment]
_In general, questions such as this should be published in the [discussions](https://github.com/doronz88/pymobiledevice3/discussions) section._

Regarding your question, that's correct - Apple do not provide any API to download the applications binary - only data. The application binaries can only be downloaded from AppStore.
