### ISSUE TITLE
How can I start tunnel for devices that are iOS>=17.4 and iOS<17.4 connected by Wi-Fi?

### ISSUE THREAD

**Issue by 2088669827** [doronz88/pymobiledevice3#983]
**Test environment**
- Host OS version. macOS Sonoma 14.4.1，Apple M2 Pro.
- Target device model and iOS version. iPhone XR, 17.3.1.

**Describe the bug**
I want to start tunnel for devices connected by Wi-Fi, but the command "sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel -t wifi" does't work at all.
When I run "sudo /usr/bin/python3 -m pymobiledevice3 remote tunneld --wifi", it also reports error that tunneld not ready for device.
<img width="631" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/996349b8-fb73-4a97-9e41-1757d4909400">
<img width="500" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/ff281118-9c1a-47f5-b262-65830fffe18e">

**To Reproduce**

1. Connect iPhone to PC with USB
2. Unplug cable
3. Check device connected with pymobiledevice3 usbmux list, "ConnectionType": "Network"
4. sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel, or, sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel -t wifi

**Expected behavior**
I want to start tunnel for devices connected by Wi-Fi, both for iOS>=17.4 and iOS<17.4.

**Logs**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
You are confusing lockdown-wifi with remote-wifi which is something entirely different (as documented in the project's documentation).

In general, you need to first pair the device over USB since `remoted` doesn't support wifi-pairing.
Read further on:

https://github.com/doronz88/pymobiledevice3/blob/master/misc/understanding_idevice_protocol_layers.md#remotexpc

**Comment by 2088669827** [comment]
As you said, I lockdown pair the device over USB successfully. And then I run remote tunneld, but it still doesn't work.
<img width="630" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/7c857f77-5dd5-4a28-8aa4-b2bf54041179">

And when I remote pair the device over USB, it reports error that No devices were found during bonjour browse.
<img width="628" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/3ca6a952-687e-4d0e-ac13-3325cace3fd8">

**Comment by doronz88** [comment]
That is not pairing over remoted. For pairing over remoted (USB) you need:
```shell
sudo pymobiledevice3 remote start-tunnel
```

**Comment by 2088669827** [comment]
Yes, I run this over USB, and it's normal like this, but then I unplug the cable to switch to Wi-Fi, it outputs error:
<img width="635" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/1e1b7181-e2c7-4182-96f5-fab3ea01d8a3">

Exactly, my motion is to run **commands related to developer**, like app launch and `pymobiledevice3 developer dvt screenshot ~/1.png`, in condition that the device is connected over **Wi-Fi**, but whatever I do, it always outputs error like this:
<img width="632" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/04cb782d-18f5-40e1-b117-589451888deb">
<img width="633" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/a33f70c1-79ca-4042-81d8-9ea6095f29bc">

**Comment by 2088669827** [comment]
It seems that it doesn't work to start tunnel over wifi at all?  https://github.com/doronz88/pymobiledevice3/issues/729

**Comment by doronz88** [comment]
@2088669827 u didnt start tunneld

**Comment by 2088669827** [comment]
I found a pattern!
**1. When USB connected**
`sudo /usr/bin/python3 -m pymobiledevice3 remote tunneld` not only runs the uvicorn, but also automatically start the usb task to start tunnel. 

<img width="490" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/ebdc17cd-8024-4ca9-bd81-446a0c3decaf">

In this case, `curl http://127.0.0.1:49151` prints the connected device. And app launch and screenshot can work normally.
<img width="488" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/550986fd-d6b6-46c8-ae3b-2c654d44687e">


**2. When Wi-Fi connected**
`sudo /usr/bin/python3 -m pymobiledevice3 remote tunneld` only runs a uvicorn, but does not automatically start the wifi task to start tunnel. 

<img width="487" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/33999a6d-c789-404e-85a9-f9b836460424">


In this case, `curl http://127.0.0.1:49151` outputs an empty '{}'.

To start the wifi task to start tunnel, first need to run **`curl http://127.0.0.1:49151/start-tunnel\?udid\=00008020-0011119A22F8003A`**. Now, `curl http://127.0.0.1:49151` prints the connected device, and app launch and screenshot can work normally.

<img width="490" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/88ef9358-0a34-4f25-b125-82a0caacdf91">
<img width="490" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/47168e17-572b-4d12-a140-81a9dc069f06">




**Are these two different ways your special design? The way to start tunnel over Wi-Fi is not simple enough, should it to be improved?**

**Comment by doronz88** [comment]
on my workstation everything works on both wifi and not. if u have a reproduceable issue, feel free to submit a PR

**Comment by 2088669827** [comment]
I see what the problem is.
There are two pair records in my dir ~/.pymobiledevice3. But the first device is offline.
When I run `sudo /usr/bin/python3 -m pymobiledevice3 remote tunneld`, pmd3 first pairs with the first device, and then the second one, but it's stuck there.

<img width="1075" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/1b27a92d-7dd3-4800-9dac-6f6d489c0685">

Correctly, if I run `sudo /usr/bin/python3 -m pymobiledevice3 remote start-tunnel -t wifi --udid 00008020-0011119A22F8003A` , or if I remove the pair record of the offline device, `remote start-tunnel` and `remote tunneld` both work normally.

<img width="1087" alt="image" src="https://github.com/doronz88/pymobiledevice3/assets/50981894/fc6f4200-f22a-4767-83a5-23540b522a27">

**Comment by doronz88** [comment]
Recent releases of pymobile check if it run over `sudo` and chown the pair records accordingly. Probably u had a pair record from an older version
