### ISSUE TITLE
TunnelError("pmd3 start-tunnel empty response")

### ISSUE THREAD

**Issue by dusk0504** [doronz88/pymobiledevice3#984]
**Test environment**
- Host OS version.
- Target device model and iOS version.
17.4.1

**Describe the bug**
TunnelError("pmd3 start-tunnel empty response")

**To Reproduce**
sudo python3 -m pymobiledevice3 remote tunneld

**Expected behavior**

**Logs**
If applicable, add logs including backtraces for the given error that help explain your problem.

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
I have no idea what were u trying to report

**Comment by dusk0504** [comment]
Execute command “sudo python3 -m pymobiledevice3 remote tunneld” and report error “TunnelError("pmd3 start-tunnel empty response")”.
Please tell me the reason for the error
